/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AddRatesV1200ResponseData : The ID of the rate card to which the rates were added.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddRatesV1200ResponseData {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
}

impl AddRatesV1200ResponseData {
    /// The ID of the rate card to which the rates were added.
    pub fn new(id: uuid::Uuid) -> AddRatesV1200ResponseData {
        AddRatesV1200ResponseData {
            id,
        }
    }
}

