/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AggregationTypeForEventsSearch : Specifies the type of aggregation performed on matching events. Includes \"custom_sql\" for events search endpoint responses.
/// Specifies the type of aggregation performed on matching events. Includes \"custom_sql\" for events search endpoint responses.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AggregationTypeForEventsSearch {
    #[serde(rename = "count")]
    Count,
    #[serde(rename = "Count")]
    Count2,
    #[serde(rename = "COUNT")]
    Count3,
    #[serde(rename = "latest")]
    Latest,
    #[serde(rename = "Latest")]
    Latest2,
    #[serde(rename = "LATEST")]
    Latest3,
    #[serde(rename = "max")]
    Max,
    #[serde(rename = "Max")]
    Max2,
    #[serde(rename = "MAX")]
    Max3,
    #[serde(rename = "sum")]
    Sum,
    #[serde(rename = "Sum")]
    Sum2,
    #[serde(rename = "SUM")]
    Sum3,
    #[serde(rename = "unique")]
    Unique,
    #[serde(rename = "Unique")]
    Unique2,
    #[serde(rename = "UNIQUE")]
    Unique3,
    #[serde(rename = "custom_sql")]
    CustomSql,

}

impl std::fmt::Display for AggregationTypeForEventsSearch {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Count => write!(f, "count"),
            Self::Count2 => write!(f, "Count"),
            Self::Count3 => write!(f, "COUNT"),
            Self::Latest => write!(f, "latest"),
            Self::Latest2 => write!(f, "Latest"),
            Self::Latest3 => write!(f, "LATEST"),
            Self::Max => write!(f, "max"),
            Self::Max2 => write!(f, "Max"),
            Self::Max3 => write!(f, "MAX"),
            Self::Sum => write!(f, "sum"),
            Self::Sum2 => write!(f, "Sum"),
            Self::Sum3 => write!(f, "SUM"),
            Self::Unique => write!(f, "unique"),
            Self::Unique2 => write!(f, "Unique"),
            Self::Unique3 => write!(f, "UNIQUE"),
            Self::CustomSql => write!(f, "custom_sql"),
        }
    }
}

impl Default for AggregationTypeForEventsSearch {
    fn default() -> AggregationTypeForEventsSearch {
        Self::Count
    }
}

