/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlertSpecifier {
    /// A list of custom field filters for notification types that support advanced filtering
    #[serde(rename = "custom_field_filters", skip_serializing_if = "Option::is_none")]
    pub custom_field_filters: Option<Vec<models::AlertSpecifierInclusiveCustomFieldFilter>>,
    /// If provided, the specifier will not apply to balances that matches the inclusion criteria and any of the excluding values.
    #[serde(rename = "exclude", skip_serializing_if = "Option::is_none")]
    pub exclude: Option<Vec<models::ExcludeAlertSpecifier>>,
}

impl AlertSpecifier {
    pub fn new() -> AlertSpecifier {
        AlertSpecifier {
            custom_field_filters: None,
            exclude: None,
        }
    }
}

