/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArchiveCreditV2Request {
    /// ID of the customer whose credit is being archived
    #[serde(rename = "customer_id")]
    pub customer_id: uuid::Uuid,
    /// ID of the credit to archive
    #[serde(rename = "credit_id")]
    pub credit_id: uuid::Uuid,
}

impl ArchiveCreditV2Request {
    pub fn new(customer_id: uuid::Uuid, credit_id: uuid::Uuid) -> ArchiveCreditV2Request {
        ArchiveCreditV2Request {
            customer_id,
            credit_id,
        }
    }
}

