/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArchiveContractPayload {
    /// ID of the customer whose contract is to be archived
    #[serde(rename = "customer_id")]
    pub customer_id: uuid::Uuid,
    /// ID of the contract to archive
    #[serde(rename = "contract_id")]
    pub contract_id: uuid::Uuid,
    /// If false, the existing finalized invoices will remain after the contract is archived.
    #[serde(rename = "void_invoices")]
    pub void_invoices: bool,
}

impl ArchiveContractPayload {
    pub fn new(customer_id: uuid::Uuid, contract_id: uuid::Uuid, void_invoices: bool) -> ArchiveContractPayload {
        ArchiveContractPayload {
            customer_id,
            contract_id,
            void_invoices,
        }
    }
}

