/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArchiveAlertV1404Response {
    #[serde(rename = "message")]
    pub message: String,
}

impl ArchiveAlertV1404Response {
    pub fn new(message: String) -> ArchiveAlertV1404Response {
        ArchiveAlertV1404Response {
            message,
        }
    }
}

