/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArchiveAlertPayload {
    /// The Metronome ID of the threshold notification
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// If true, resets the uniqueness key on this threshold notification so it can be re-used
    #[serde(rename = "release_uniqueness_key", skip_serializing_if = "Option::is_none")]
    pub release_uniqueness_key: Option<bool>,
}

impl ArchiveAlertPayload {
    pub fn new(id: uuid::Uuid) -> ArchiveAlertPayload {
        ArchiveAlertPayload {
            id,
            release_uniqueness_key: None,
        }
    }
}

