/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ArchiveProductListItemPayload {
    /// ID of the product to be archived
    #[serde(rename = "product_id")]
    pub product_id: uuid::Uuid,
}

impl ArchiveProductListItemPayload {
    pub fn new(product_id: uuid::Uuid) -> ArchiveProductListItemPayload {
        ArchiveProductListItemPayload {
            product_id,
        }
    }
}

