/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BalanceFilter {
    /// The balance type to filter by.
    #[serde(rename = "balance_types", skip_serializing_if = "Option::is_none")]
    pub balance_types: Option<Vec<BalanceTypes>>,
    /// Specific IDs to compute balance across.
    #[serde(rename = "ids", skip_serializing_if = "Option::is_none")]
    pub ids: Option<Vec<uuid::Uuid>>,
    /// Custom fields to compute balance across. Must match all custom fields
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<std::collections::HashMap<String, String>>,
}

impl BalanceFilter {
    pub fn new() -> BalanceFilter {
        BalanceFilter {
            balance_types: None,
            ids: None,
            custom_fields: None,
        }
    }
}
/// The balance type to filter by.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BalanceTypes {
    #[serde(rename = "PREPAID_COMMIT")]
    PrepaidCommit,
    #[serde(rename = "POSTPAID_COMMIT")]
    PostpaidCommit,
    #[serde(rename = "CREDIT")]
    Credit,
}

impl Default for BalanceTypes {
    fn default() -> BalanceTypes {
        Self::PrepaidCommit
    }
}

