/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseUsageFilter {
    #[serde(rename = "group_key")]
    pub group_key: String,
    #[serde(rename = "group_values")]
    pub group_values: Vec<String>,
    #[serde(rename = "starting_at", skip_serializing_if = "Option::is_none")]
    pub starting_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl BaseUsageFilter {
    pub fn new(group_key: String, group_values: Vec<String>) -> BaseUsageFilter {
        BaseUsageFilter {
            group_key,
            group_values,
            starting_at: None,
        }
    }
}

