/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BillingProviderSettingsType {
    #[serde(rename = "stripe")]
    Stripe,

}

impl std::fmt::Display for BillingProviderSettingsType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Stripe => write!(f, "stripe"),
        }
    }
}

impl Default for BillingProviderSettingsType {
    fn default() -> BillingProviderSettingsType {
        Self::Stripe
    }
}

