/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CommitPaymentGateConfigPrecalculatedTaxConfig : Only applicable if using PRECALCULATED as your tax type.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommitPaymentGateConfigPrecalculatedTaxConfig {
    /// Amount of tax to be applied. This should be in the same currency and denomination as the commit's invoice schedule
    #[serde(rename = "tax_amount")]
    pub tax_amount: f64,
    /// Name of the tax to be applied. This may be used in an invoice line item description.
    #[serde(rename = "tax_name", skip_serializing_if = "Option::is_none")]
    pub tax_name: Option<String>,
}

impl CommitPaymentGateConfigPrecalculatedTaxConfig {
    /// Only applicable if using PRECALCULATED as your tax type.
    pub fn new(tax_amount: f64) -> CommitPaymentGateConfigPrecalculatedTaxConfig {
        CommitPaymentGateConfigPrecalculatedTaxConfig {
            tax_amount,
            tax_name: None,
        }
    }
}

