/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommitHierarchyConfiguration {
    #[serde(rename = "child_access")]
    pub child_access: Box<models::CommitHierarchyConfigurationChildAccess>,
}

impl CommitHierarchyConfiguration {
    pub fn new(child_access: models::CommitHierarchyConfigurationChildAccess) -> CommitHierarchyConfiguration {
        CommitHierarchyConfiguration {
            child_access: Box::new(child_access),
        }
    }
}

