/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CommitInvoiceContract : The contract that this commit will be billed on.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommitInvoiceContract {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
}

impl CommitInvoiceContract {
    /// The contract that this commit will be billed on.
    pub fn new(id: uuid::Uuid) -> CommitInvoiceContract {
        CommitInvoiceContract {
            id,
        }
    }
}

