/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractWithoutAmendmentsSpendTrackersInnerApplicableSpendSpecifiersInner {
    #[serde(rename = "spend_type")]
    pub spend_type: SpendType,
    #[serde(rename = "sources")]
    pub sources: Vec<Sources>,
    #[serde(rename = "discounted", skip_serializing_if = "Option::is_none")]
    pub discounted: Option<Discounted>,
}

impl ContractWithoutAmendmentsSpendTrackersInnerApplicableSpendSpecifiersInner {
    pub fn new(spend_type: SpendType, sources: Vec<Sources>) -> ContractWithoutAmendmentsSpendTrackersInnerApplicableSpendSpecifiersInner {
        ContractWithoutAmendmentsSpendTrackersInnerApplicableSpendSpecifiersInner {
            spend_type,
            sources,
            discounted: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SpendType {
    #[serde(rename = "COMMIT_PURCHASE")]
    CommitPurchase,
}

impl Default for SpendType {
    fn default() -> SpendType {
        Self::CommitPurchase
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Sources {
    #[serde(rename = "THRESHOLD_RECHARGE")]
    ThresholdRecharge,
    #[serde(rename = "MANUAL")]
    Manual,
}

impl Default for Sources {
    fn default() -> Sources {
        Self::ThresholdRecharge
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Discounted {
    #[serde(rename = "ANY")]
    Any,
    #[serde(rename = "DISCOUNTED_ONLY")]
    DiscountedOnly,
    #[serde(rename = "UNDISCOUNTED_ONLY")]
    UndiscountedOnly,
}

impl Default for Discounted {
    fn default() -> Discounted {
        Self::Any
    }
}

