/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ContractsBillingProviderType {
    #[serde(rename = "aws_marketplace")]
    AwsMarketplace,
    #[serde(rename = "azure_marketplace")]
    AzureMarketplace,
    #[serde(rename = "gcp_marketplace")]
    GcpMarketplace,
    #[serde(rename = "stripe")]
    Stripe,
    #[serde(rename = "netsuite")]
    Netsuite,

}

impl std::fmt::Display for ContractsBillingProviderType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AwsMarketplace => write!(f, "aws_marketplace"),
            Self::AzureMarketplace => write!(f, "azure_marketplace"),
            Self::GcpMarketplace => write!(f, "gcp_marketplace"),
            Self::Stripe => write!(f, "stripe"),
            Self::Netsuite => write!(f, "netsuite"),
        }
    }
}

impl Default for ContractsBillingProviderType {
    fn default() -> ContractsBillingProviderType {
        Self::AwsMarketplace
    }
}

