/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractHierarchyConfigurationInputParentBehavior {
    /// Indicates the desired behavior of consolidated invoices generated by the parent in a customer hierarchy  **CONCATENATE**: Statements on the invoices of child customers will be appended to the consolidated invoice  **NONE**: Do not generate consolidated invoices
    #[serde(rename = "invoice_consolidation_type", skip_serializing_if = "Option::is_none")]
    pub invoice_consolidation_type: Option<InvoiceConsolidationType>,
}

impl ContractHierarchyConfigurationInputParentBehavior {
    pub fn new() -> ContractHierarchyConfigurationInputParentBehavior {
        ContractHierarchyConfigurationInputParentBehavior {
            invoice_consolidation_type: None,
        }
    }
}
/// Indicates the desired behavior of consolidated invoices generated by the parent in a customer hierarchy  **CONCATENATE**: Statements on the invoices of child customers will be appended to the consolidated invoice  **NONE**: Do not generate consolidated invoices
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InvoiceConsolidationType {
    #[serde(rename = "CONCATENATE")]
    Concatenate,
    #[serde(rename = "NONE")]
    None,
    #[serde(rename = "concatenate")]
    Concatenate2,
    #[serde(rename = "none")]
    None2,
}

impl Default for InvoiceConsolidationType {
    fn default() -> InvoiceConsolidationType {
        Self::Concatenate
    }
}

