/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractProjectionSummary {
    #[serde(rename = "customer_id")]
    pub customer_id: uuid::Uuid,
    #[serde(rename = "contract_id")]
    pub contract_id: uuid::Uuid,
    #[serde(rename = "starting_at")]
    pub starting_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "ending_before", skip_serializing_if = "Option::is_none")]
    pub ending_before: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "archived_at", skip_serializing_if = "Option::is_none")]
    pub archived_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl ContractProjectionSummary {
    pub fn new(customer_id: uuid::Uuid, contract_id: uuid::Uuid, starting_at: chrono::DateTime<chrono::FixedOffset>) -> ContractProjectionSummary {
        ContractProjectionSummary {
            customer_id,
            contract_id,
            starting_at,
            ending_before: None,
            archived_at: None,
        }
    }
}

