/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateContractV1RequestResellerRoyaltiesInner {
    #[serde(rename = "reseller_type")]
    pub reseller_type: ResellerType,
    #[serde(rename = "fraction")]
    pub fraction: f64,
    #[serde(rename = "netsuite_reseller_id")]
    pub netsuite_reseller_id: String,
    /// Must provide at least one of applicable_product_ids or applicable_product_tags.
    #[serde(rename = "applicable_product_ids", skip_serializing_if = "Option::is_none")]
    pub applicable_product_ids: Option<Vec<uuid::Uuid>>,
    /// Must provide at least one of applicable_product_ids or applicable_product_tags.
    #[serde(rename = "applicable_product_tags", skip_serializing_if = "Option::is_none")]
    pub applicable_product_tags: Option<Vec<String>>,
    #[serde(rename = "starting_at")]
    pub starting_at: String,
    #[serde(rename = "ending_before", skip_serializing_if = "Option::is_none")]
    pub ending_before: Option<String>,
    #[serde(rename = "reseller_contract_value", skip_serializing_if = "Option::is_none")]
    pub reseller_contract_value: Option<f64>,
    #[serde(rename = "aws_options", skip_serializing_if = "Option::is_none")]
    pub aws_options: Option<Box<models::ChargeSeatsV1200ResponseResellerRoyaltyAwsOptions>>,
    #[serde(rename = "gcp_options", skip_serializing_if = "Option::is_none")]
    pub gcp_options: Option<Box<models::ChargeSeatsV1200ResponseResellerRoyaltyGcpOptions>>,
}

impl CreateContractV1RequestResellerRoyaltiesInner {
    pub fn new(reseller_type: ResellerType, fraction: f64, netsuite_reseller_id: String, starting_at: String) -> CreateContractV1RequestResellerRoyaltiesInner {
        CreateContractV1RequestResellerRoyaltiesInner {
            reseller_type,
            fraction,
            netsuite_reseller_id,
            applicable_product_ids: None,
            applicable_product_tags: None,
            starting_at,
            ending_before: None,
            reseller_contract_value: None,
            aws_options: None,
            gcp_options: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ResellerType {
    #[serde(rename = "AWS")]
    Aws,
    #[serde(rename = "AWS_PRO_SERVICE")]
    AwsProService,
    #[serde(rename = "GCP")]
    Gcp,
    #[serde(rename = "GCP_PRO_SERVICE")]
    GcpProService,
}

impl Default for ResellerType {
    fn default() -> ResellerType {
        Self::Aws
    }
}

