/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateContractV1RequestHierarchyConfiguration {
    #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
    pub parent: Option<Box<models::GetContractV1200ResponseDataInitialHierarchyConfigurationOneOfChildrenInner>>,
    /// Indicates which customer should pay for the child's invoice charges  **SELF**: The child pays for its own invoice charges  **PARENT**: The parent pays for the child's invoice charges
    #[serde(rename = "payer", skip_serializing_if = "Option::is_none")]
    pub payer: Option<Payer>,
    /// Indicates the behavior of the child's invoice statements on the parent's invoices.  **CONSOLIDATE**: Child's invoice statements will be added to parent's consolidated invoices  **SEPARATE**: Child's invoice statements will appear not appear on parent's consolidated invoices
    #[serde(rename = "usage_statement_behavior", skip_serializing_if = "Option::is_none")]
    pub usage_statement_behavior: Option<UsageStatementBehavior>,
    #[serde(rename = "parent_behavior", skip_serializing_if = "Option::is_none")]
    pub parent_behavior: Option<Box<models::CreateContractV1RequestHierarchyConfigurationParentBehavior>>,
}

impl CreateContractV1RequestHierarchyConfiguration {
    pub fn new() -> CreateContractV1RequestHierarchyConfiguration {
        CreateContractV1RequestHierarchyConfiguration {
            parent: None,
            payer: None,
            usage_statement_behavior: None,
            parent_behavior: None,
        }
    }
}
/// Indicates which customer should pay for the child's invoice charges  **SELF**: The child pays for its own invoice charges  **PARENT**: The parent pays for the child's invoice charges
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Payer {
    #[serde(rename = "SELF")]
    VariantSelf,
    #[serde(rename = "PARENT")]
    Parent,
    #[serde(rename = "self")]
    VariantSelf2,
    #[serde(rename = "parent")]
    Parent2,
}

impl Default for Payer {
    fn default() -> Payer {
        Self::VariantSelf
    }
}
/// Indicates the behavior of the child's invoice statements on the parent's invoices.  **CONSOLIDATE**: Child's invoice statements will be added to parent's consolidated invoices  **SEPARATE**: Child's invoice statements will appear not appear on parent's consolidated invoices
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UsageStatementBehavior {
    #[serde(rename = "CONSOLIDATE")]
    Consolidate,
    #[serde(rename = "SEPARATE")]
    Separate,
    #[serde(rename = "consolidate")]
    Consolidate2,
    #[serde(rename = "separate")]
    Separate2,
}

impl Default for UsageStatementBehavior {
    fn default() -> UsageStatementBehavior {
        Self::Consolidate
    }
}

