/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreatePackageV1RequestUsageStatementScheduleInvoiceGenerationStartingAtOffset : The offset at which Metronome should start generating usage invoices, relative to the contract start date.  If unspecified, contract start date will be used. This is useful to set if you want to import historical invoices via our 'Create Historical Invoices' API rather than having Metronome automatically generate them.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePackageV1RequestUsageStatementScheduleInvoiceGenerationStartingAtOffset {
    #[serde(rename = "value")]
    pub value: i32,
    #[serde(rename = "unit")]
    pub unit: Unit,
}

impl CreatePackageV1RequestUsageStatementScheduleInvoiceGenerationStartingAtOffset {
    /// The offset at which Metronome should start generating usage invoices, relative to the contract start date.  If unspecified, contract start date will be used. This is useful to set if you want to import historical invoices via our 'Create Historical Invoices' API rather than having Metronome automatically generate them.
    pub fn new(value: i32, unit: Unit) -> CreatePackageV1RequestUsageStatementScheduleInvoiceGenerationStartingAtOffset {
        CreatePackageV1RequestUsageStatementScheduleInvoiceGenerationStartingAtOffset {
            value,
            unit,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Unit {
    #[serde(rename = "DAYS")]
    Days,
    #[serde(rename = "WEEKS")]
    Weeks,
    #[serde(rename = "MONTHS")]
    Months,
    #[serde(rename = "YEARS")]
    Years,
}

impl Default for Unit {
    fn default() -> Unit {
        Self::Days
    }
}

