/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreatePackageV1RequestCommitsInnerAccessScheduleScheduleItemsInnerDuration : Offset relative to the start of this segment indicating when it should end.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePackageV1RequestCommitsInnerAccessScheduleScheduleItemsInnerDuration {
    #[serde(rename = "value")]
    pub value: i32,
    #[serde(rename = "unit")]
    pub unit: Unit,
}

impl CreatePackageV1RequestCommitsInnerAccessScheduleScheduleItemsInnerDuration {
    /// Offset relative to the start of this segment indicating when it should end.
    pub fn new(value: i32, unit: Unit) -> CreatePackageV1RequestCommitsInnerAccessScheduleScheduleItemsInnerDuration {
        CreatePackageV1RequestCommitsInnerAccessScheduleScheduleItemsInnerDuration {
            value,
            unit,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Unit {
    #[serde(rename = "DAYS")]
    Days,
    #[serde(rename = "WEEKS")]
    Weeks,
    #[serde(rename = "MONTHS")]
    Months,
    #[serde(rename = "YEARS")]
    Years,
}

impl Default for Unit {
    fn default() -> Unit {
        Self::Days
    }
}

