/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePackageV1RequestCreditsInner {
    /// displayed on invoices
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "product_id")]
    pub product_id: uuid::Uuid,
    #[serde(rename = "access_schedule")]
    pub access_schedule: Box<models::CreatePackageV1RequestCreditsInnerAccessSchedule>,
    /// Used only in UI/API. It is not exposed to end customers.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Which products the credit applies to. If both applicable_product_ids and applicable_product_tags are not provided, the credit applies to all products.
    #[serde(rename = "applicable_product_ids", skip_serializing_if = "Option::is_none")]
    pub applicable_product_ids: Option<Vec<uuid::Uuid>>,
    /// Which tags the credit applies to. If both applicable_product_ids and applicable_product_tags are not provided, the credit applies to all products.
    #[serde(rename = "applicable_product_tags", skip_serializing_if = "Option::is_none")]
    pub applicable_product_tags: Option<Vec<String>>,
    /// List of filters that determine what kind of customer usage draws down a commit or credit. A customer's usage needs to meet the condition of at least one of the specifiers to contribute to a commit's or credit's drawdown. This field cannot be used together with `applicable_product_ids` or `applicable_product_tags`.
    #[serde(rename = "specifiers", skip_serializing_if = "Option::is_none")]
    pub specifiers: Option<Vec<models::GetContractV1200ResponseDataInitialPrepaidBalanceThresholdConfigurationCommitAllOfSpecifiersInner>>,
    /// If multiple credits are applicable, the one with the lower priority will apply first.
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<f64>,
    #[serde(rename = "rate_type", skip_serializing_if = "Option::is_none")]
    pub rate_type: Option<RateType>,
    /// Custom fields to be added eg. { \"key1\": \"value1\", \"key2\": \"value2\" }
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<std::collections::HashMap<String, String>>,
}

impl CreatePackageV1RequestCreditsInner {
    pub fn new(product_id: uuid::Uuid, access_schedule: models::CreatePackageV1RequestCreditsInnerAccessSchedule) -> CreatePackageV1RequestCreditsInner {
        CreatePackageV1RequestCreditsInner {
            name: None,
            product_id,
            access_schedule: Box::new(access_schedule),
            description: None,
            applicable_product_ids: None,
            applicable_product_tags: None,
            specifiers: None,
            priority: None,
            rate_type: None,
            custom_fields: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RateType {
    #[serde(rename = "COMMIT_RATE")]
    CommitRate,
    #[serde(rename = "commit_rate")]
    CommitRate2,
    #[serde(rename = "LIST_RATE")]
    ListRate,
    #[serde(rename = "list_rate")]
    ListRate2,
}

impl Default for RateType {
    fn default() -> RateType {
        Self::CommitRate
    }
}

