/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateBillableMetricV1V1Request {
    /// The display name of the billable metric.
    #[serde(rename = "name")]
    pub name: String,
    /// The SQL query associated with the billable metric. This field is mutually exclusive with aggregation_type, event_type_filter, property_filters, aggregation_key, and group_keys. If provided, these other fields must be omitted.
    #[serde(rename = "sql", skip_serializing_if = "Option::is_none")]
    pub sql: Option<String>,
    #[serde(rename = "event_type_filter", skip_serializing_if = "Option::is_none")]
    pub event_type_filter: Option<Box<models::CreateBillableMetricV1V1RequestEventTypeFilter>>,
    /// A list of filters to match events to this billable metric. Each filter defines a rule on an event property. All rules must pass for the event to match the billable metric.
    #[serde(rename = "property_filters", skip_serializing_if = "Option::is_none")]
    pub property_filters: Option<Vec<models::CreateBillableMetricV1V1RequestPropertyFiltersInner>>,
    /// Specifies the type of aggregation performed on matching events.
    #[serde(rename = "aggregation_type", skip_serializing_if = "Option::is_none")]
    pub aggregation_type: Option<AggregationType>,
    /// Specifies the type of aggregation performed on matching events. Required if `sql` is not provided.
    #[serde(rename = "aggregation_key", skip_serializing_if = "Option::is_none")]
    pub aggregation_key: Option<String>,
    /// Property names that are used to group usage costs on an invoice. Each entry represents a set of properties used to slice events into distinct buckets.
    #[serde(rename = "group_keys", skip_serializing_if = "Option::is_none")]
    pub group_keys: Option<Vec<Vec<String>>>,
    /// Custom fields to attach to the billable metric.
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<std::collections::HashMap<String, String>>,
}

impl CreateBillableMetricV1V1Request {
    pub fn new(name: String) -> CreateBillableMetricV1V1Request {
        CreateBillableMetricV1V1Request {
            name,
            sql: None,
            event_type_filter: None,
            property_filters: None,
            aggregation_type: None,
            aggregation_key: None,
            group_keys: None,
            custom_fields: None,
        }
    }
}
/// Specifies the type of aggregation performed on matching events.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AggregationType {
    #[serde(rename = "count")]
    Count,
    #[serde(rename = "Count")]
    Count2,
    #[serde(rename = "COUNT")]
    Count3,
    #[serde(rename = "latest")]
    Latest,
    #[serde(rename = "Latest")]
    Latest2,
    #[serde(rename = "LATEST")]
    Latest3,
    #[serde(rename = "max")]
    Max,
    #[serde(rename = "Max")]
    Max2,
    #[serde(rename = "MAX")]
    Max3,
    #[serde(rename = "sum")]
    Sum,
    #[serde(rename = "Sum")]
    Sum2,
    #[serde(rename = "SUM")]
    Sum3,
    #[serde(rename = "unique")]
    Unique,
    #[serde(rename = "Unique")]
    Unique2,
    #[serde(rename = "UNIQUE")]
    Unique3,
}

impl Default for AggregationType {
    fn default() -> AggregationType {
        Self::Count
    }
}

