/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateContractV1RequestPackageCustomizationsModifySubscriptionsInner {
    /// ID of the template subscription on the package to customize. Provide exactly one of template_subscription_id or subscription_alias.
    #[serde(rename = "template_subscription_id", skip_serializing_if = "Option::is_none")]
    pub template_subscription_id: Option<uuid::Uuid>,
    /// Human-readable alias of the template subscription on the package to customize, as an alternative to template_subscription_id. Provide exactly one of the two.
    #[serde(rename = "subscription_alias", skip_serializing_if = "Option::is_none")]
    pub subscription_alias: Option<String>,
    /// The initial quantity for the subscription. Must be a non-negative value. Provide for a QUANTITY_ONLY subscription.
    #[serde(rename = "initial_quantity", skip_serializing_if = "Option::is_none")]
    pub initial_quantity: Option<f64>,
    /// Seat identifiers to assign at the start of a SEAT_BASED subscription.
    #[serde(rename = "initial_seat_ids", skip_serializing_if = "Option::is_none")]
    pub initial_seat_ids: Option<Vec<String>>,
    /// Number of unassigned seats to provision at the start of a SEAT_BASED subscription.
    #[serde(rename = "initial_unassigned_seats", skip_serializing_if = "Option::is_none")]
    pub initial_unassigned_seats: Option<f64>,
}

impl CreateContractV1RequestPackageCustomizationsModifySubscriptionsInner {
    pub fn new() -> CreateContractV1RequestPackageCustomizationsModifySubscriptionsInner {
        CreateContractV1RequestPackageCustomizationsModifySubscriptionsInner {
            template_subscription_id: None,
            subscription_alias: None,
            initial_quantity: None,
            initial_seat_ids: None,
            initial_unassigned_seats: None,
        }
    }
}

