/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateContractV1RequestTransitionFutureInvoiceBehavior {
    /// Controls whether future trueup invoices are billed or removed. Default behavior is AS_IS if not specified.
    #[serde(rename = "trueup", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub trueup: Option<Option<Trueup>>,
}

impl CreateContractV1RequestTransitionFutureInvoiceBehavior {
    pub fn new() -> CreateContractV1RequestTransitionFutureInvoiceBehavior {
        CreateContractV1RequestTransitionFutureInvoiceBehavior {
            trueup: None,
        }
    }
}
/// Controls whether future trueup invoices are billed or removed. Default behavior is AS_IS if not specified.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Trueup {
    #[serde(rename = "remove")]
    Remove,
    #[serde(rename = "as_is")]
    AsIs,
    #[serde(rename = "REMOVE")]
    Remove2,
    #[serde(rename = "AS_IS")]
    AsIs2,
}

impl Default for Trueup {
    fn default() -> Trueup {
        Self::Remove
    }
}

