/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePackagePayload {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "contract_name", skip_serializing_if = "Option::is_none")]
    pub contract_name: Option<String>,
    /// Prevents the creation of duplicates. If a request to create a record is made with a previously used uniqueness key, a new record will not be created and the request will fail with a 409 error.
    #[serde(rename = "uniqueness_key", skip_serializing_if = "Option::is_none")]
    pub uniqueness_key: Option<String>,
    #[serde(rename = "net_payment_terms_days", skip_serializing_if = "Option::is_none")]
    pub net_payment_terms_days: Option<f64>,
    #[serde(rename = "rate_card_id", skip_serializing_if = "Option::is_none")]
    pub rate_card_id: Option<uuid::Uuid>,
    /// Selects the rate card linked to the specified alias as of the contract's start date.
    #[serde(rename = "rate_card_alias", skip_serializing_if = "Option::is_none")]
    pub rate_card_alias: Option<String>,
    /// Reference this alias when creating a contract. If the same alias is assigned to multiple packages, it will reference the package to which it was most recently assigned. It is not exposed to end customers.
    #[serde(rename = "aliases", skip_serializing_if = "Option::is_none")]
    pub aliases: Option<Vec<models::PackageAlias>>,
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<Box<models::RelativeDate>>,
    #[serde(rename = "commits", skip_serializing_if = "Option::is_none")]
    pub commits: Option<Vec<models::CommitTemplateInput>>,
    #[serde(rename = "credits", skip_serializing_if = "Option::is_none")]
    pub credits: Option<Vec<models::CreditTemplateInput>>,
    #[serde(rename = "recurring_commits", skip_serializing_if = "Option::is_none")]
    pub recurring_commits: Option<Vec<models::RecurringCommitTemplateInput>>,
    #[serde(rename = "recurring_credits", skip_serializing_if = "Option::is_none")]
    pub recurring_credits: Option<Vec<models::RecurringCreditTemplateInput>>,
    /// Defaults to LOWEST_MULTIPLIER, which applies the greatest discount to list prices automatically. EXPLICIT prioritization requires specifying priorities for each multiplier; the one with the lowest priority value will be prioritized first. If tiered overrides are used, prioritization must be explicit.
    #[serde(rename = "multiplier_override_prioritization", skip_serializing_if = "Option::is_none")]
    pub multiplier_override_prioritization: Option<MultiplierOverridePrioritization>,
    #[serde(rename = "overrides", skip_serializing_if = "Option::is_none")]
    pub overrides: Option<Vec<models::OverrideTemplateInput>>,
    #[serde(rename = "scheduled_charges", skip_serializing_if = "Option::is_none")]
    pub scheduled_charges: Option<Vec<models::ScheduledChargeTemplateInput>>,
    #[serde(rename = "scheduled_charges_on_usage_invoices", skip_serializing_if = "Option::is_none")]
    pub scheduled_charges_on_usage_invoices: Option<models::ScheduledChargesOnUsageInvoices>,
    #[serde(rename = "usage_statement_schedule", skip_serializing_if = "Option::is_none")]
    pub usage_statement_schedule: Option<Box<models::UsageStatementScheduleTemplateInput>>,
    #[serde(rename = "billing_provider", skip_serializing_if = "Option::is_none")]
    pub billing_provider: Option<models::ContractsBillingProviderType>,
    #[serde(rename = "delivery_method", skip_serializing_if = "Option::is_none")]
    pub delivery_method: Option<models::BillingProviderDeliveryMethodType>,
    #[serde(rename = "spend_threshold_configuration", skip_serializing_if = "Option::is_none")]
    pub spend_threshold_configuration: Option<Box<models::SpendThresholdConfiguration>>,
    #[serde(rename = "prepaid_balance_threshold_configuration", skip_serializing_if = "Option::is_none")]
    pub prepaid_balance_threshold_configuration: Option<Box<models::PrepaidBalanceThresholdConfiguration>>,
    #[serde(rename = "spend_trackers", skip_serializing_if = "Option::is_none")]
    pub spend_trackers: Option<Vec<models::SpendTrackerInput>>,
    #[serde(rename = "subscriptions", skip_serializing_if = "Option::is_none")]
    pub subscriptions: Option<Vec<models::SubscriptionTemplateInput>>,
}

impl CreatePackagePayload {
    pub fn new(name: String) -> CreatePackagePayload {
        CreatePackagePayload {
            name,
            contract_name: None,
            uniqueness_key: None,
            net_payment_terms_days: None,
            rate_card_id: None,
            rate_card_alias: None,
            aliases: None,
            duration: None,
            commits: None,
            credits: None,
            recurring_commits: None,
            recurring_credits: None,
            multiplier_override_prioritization: None,
            overrides: None,
            scheduled_charges: None,
            scheduled_charges_on_usage_invoices: None,
            usage_statement_schedule: None,
            billing_provider: None,
            delivery_method: None,
            spend_threshold_configuration: None,
            prepaid_balance_threshold_configuration: None,
            spend_trackers: None,
            subscriptions: None,
        }
    }
}
/// Defaults to LOWEST_MULTIPLIER, which applies the greatest discount to list prices automatically. EXPLICIT prioritization requires specifying priorities for each multiplier; the one with the lowest priority value will be prioritized first. If tiered overrides are used, prioritization must be explicit.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MultiplierOverridePrioritization {
    #[serde(rename = "LOWEST_MULTIPLIER")]
    LowestMultiplier,
    #[serde(rename = "lowest_multiplier")]
    LowestMultiplier2,
    #[serde(rename = "EXPLICIT")]
    Explicit,
    #[serde(rename = "explicit")]
    Explicit2,
}

impl Default for MultiplierOverridePrioritization {
    fn default() -> MultiplierOverridePrioritization {
        Self::LowestMultiplier
    }
}

