/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateContractV1RequestRecurringCommitsInnerAllOfAccessAmount : The amount of commit to grant.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateContractV1RequestRecurringCommitsInnerAllOfAccessAmount {
    /// Indicates how the balance of child commits is drawn down. `SPEND` deducts the dollar cost of usage. `QUANTITY` deducts the number of units used.
    #[serde(rename = "access_type", skip_serializing_if = "Option::is_none")]
    pub access_type: Option<AccessType>,
    #[serde(rename = "unit_price")]
    pub unit_price: f64,
    /// This field is required unless a subscription is attached via `subscription_config`.
    #[serde(rename = "quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<f64>,
    /// Defaults to USD (cents) if not passed
    #[serde(rename = "credit_type_id", skip_serializing_if = "Option::is_none")]
    pub credit_type_id: Option<uuid::Uuid>,
}

impl CreateContractV1RequestRecurringCommitsInnerAllOfAccessAmount {
    /// The amount of commit to grant.
    pub fn new(unit_price: f64) -> CreateContractV1RequestRecurringCommitsInnerAllOfAccessAmount {
        CreateContractV1RequestRecurringCommitsInnerAllOfAccessAmount {
            access_type: None,
            unit_price,
            quantity: None,
            credit_type_id: None,
        }
    }
}
/// Indicates how the balance of child commits is drawn down. `SPEND` deducts the dollar cost of usage. `QUANTITY` deducts the number of units used.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccessType {
    #[serde(rename = "SPEND")]
    Spend,
    #[serde(rename = "QUANTITY")]
    Quantity,
    #[serde(rename = "spend")]
    Spend2,
    #[serde(rename = "quantity")]
    Quantity2,
}

impl Default for AccessType {
    fn default() -> AccessType {
        Self::Spend
    }
}

