/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateHistoricalContractUsageInvoicesV1RequestInvoicesInnerUsageLineItemsInner {
    #[serde(rename = "product_id")]
    pub product_id: uuid::Uuid,
    #[serde(rename = "inclusive_start_date")]
    pub inclusive_start_date: String,
    #[serde(rename = "exclusive_end_date")]
    pub exclusive_end_date: String,
    #[serde(rename = "quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<f64>,
    #[serde(rename = "pricing_group_values", skip_serializing_if = "Option::is_none")]
    pub pricing_group_values: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "presentation_group_values", skip_serializing_if = "Option::is_none")]
    pub presentation_group_values: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "subtotals_with_quantity", skip_serializing_if = "Option::is_none")]
    pub subtotals_with_quantity: Option<Vec<models::CreateHistoricalContractUsageInvoicesV1RequestInvoicesInnerUsageLineItemsInnerSubtotalsWithQuantityInner>>,
}

impl CreateHistoricalContractUsageInvoicesV1RequestInvoicesInnerUsageLineItemsInner {
    pub fn new(product_id: uuid::Uuid, inclusive_start_date: String, exclusive_end_date: String) -> CreateHistoricalContractUsageInvoicesV1RequestInvoicesInnerUsageLineItemsInner {
        CreateHistoricalContractUsageInvoicesV1RequestInvoicesInnerUsageLineItemsInner {
            product_id,
            inclusive_start_date,
            exclusive_end_date,
            quantity: None,
            pricing_group_values: None,
            presentation_group_values: None,
            subtotals_with_quantity: None,
        }
    }
}

