/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePackageV1RequestSubscriptionsInnerSeatConfig {
    /// The property name, sent on usage events, that identifies the seat ID associated with the usage event. For example, the property name might be seat_id or user_id. The property must be set as a group key on billable metrics and a presentation/pricing group key on contract products. This allows linked recurring credits with an allocation per seat to be consumed by only one seat's usage.
    #[serde(rename = "seat_group_key")]
    pub seat_group_key: String,
    /// The initial amount of unassigned seats on this subscription.
    #[serde(rename = "initial_unassigned_seats", skip_serializing_if = "Option::is_none")]
    pub initial_unassigned_seats: Option<f64>,
}

impl CreatePackageV1RequestSubscriptionsInnerSeatConfig {
    pub fn new(seat_group_key: String) -> CreatePackageV1RequestSubscriptionsInnerSeatConfig {
        CreatePackageV1RequestSubscriptionsInnerSeatConfig {
            seat_group_key,
            initial_unassigned_seats: None,
        }
    }
}

