/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateContractV1200ResponseDataContract : The created contract.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateContractV1200ResponseDataContract {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "customer_id")]
    pub customer_id: uuid::Uuid,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "created_by")]
    pub created_by: String,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// ID of the package this contract was created from, if applicable.
    #[serde(rename = "package_id", skip_serializing_if = "Option::is_none")]
    pub package_id: Option<uuid::Uuid>,
    /// Optional uniqueness key to prevent duplicate contract creations.
    #[serde(rename = "uniqueness_key", skip_serializing_if = "Option::is_none")]
    pub uniqueness_key: Option<String>,
    #[serde(rename = "rate_card_id", skip_serializing_if = "Option::is_none")]
    pub rate_card_id: Option<uuid::Uuid>,
    #[serde(rename = "starting_at")]
    pub starting_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "ending_before", skip_serializing_if = "Option::is_none")]
    pub ending_before: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "net_payment_terms_days", skip_serializing_if = "Option::is_none")]
    pub net_payment_terms_days: Option<f64>,
    /// Defaults to LOWEST_MULTIPLIER, which applies the greatest discount to list prices automatically. EXPLICIT prioritization requires specifying priorities for each multiplier; the one with the lowest priority value will be prioritized first.
    #[serde(rename = "multiplier_override_prioritization", skip_serializing_if = "Option::is_none")]
    pub multiplier_override_prioritization: Option<MultiplierOverridePrioritization>,
    /// Determines which scheduled and commit charges to consolidate onto the Contract's usage invoice. The charge's `timestamp` must match the usage invoice's `ending_before` date for consolidation to occur. This field cannot be modified after a Contract has been created. If this field is omitted, charges will appear on a separate invoice from usage charges.
    #[serde(rename = "scheduled_charges_on_usage_invoices", skip_serializing_if = "Option::is_none")]
    pub scheduled_charges_on_usage_invoices: Option<ScheduledChargesOnUsageInvoices>,
    /// Custom fields to be added eg. { \"key1\": \"value1\", \"key2\": \"value2\" }
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "usage_statement_schedule")]
    pub usage_statement_schedule: Box<models::GetContractV1200ResponseDataInitialUsageStatementSchedule>,
    #[serde(rename = "usage_filter")]
    pub usage_filter: Vec<models::CreateContractV1200ResponseDataContractUsageFilterInner>,
    #[serde(rename = "commits")]
    pub commits: Vec<models::GetContractV1200ResponseDataInitialCommitsInner>,
    #[serde(rename = "credits", skip_serializing_if = "Option::is_none")]
    pub credits: Option<Vec<models::GetContractV1200ResponseDataInitialCreditsInner>>,
    #[serde(rename = "has_more", skip_serializing_if = "Option::is_none")]
    pub has_more: Option<Box<models::CreateContractV1200ResponseDataContractHasMore>>,
    #[serde(rename = "recurring_commits", skip_serializing_if = "Option::is_none")]
    pub recurring_commits: Option<Vec<models::GetContractV1200ResponseDataInitialRecurringCommitsInner>>,
    #[serde(rename = "recurring_credits", skip_serializing_if = "Option::is_none")]
    pub recurring_credits: Option<Vec<models::GetContractV1200ResponseDataInitialRecurringCreditsInner>>,
    #[serde(rename = "overrides")]
    pub overrides: Vec<models::GetContractV1200ResponseDataInitialOverridesInner>,
    #[serde(rename = "scheduled_charges")]
    pub scheduled_charges: Vec<models::GetContractV1200ResponseDataInitialScheduledChargesInner>,
    #[serde(rename = "transitions")]
    pub transitions: Vec<models::GetContractV1200ResponseDataInitialTransitionsInner>,
    /// List of subscriptions on the contract.
    #[serde(rename = "subscriptions", skip_serializing_if = "Option::is_none")]
    pub subscriptions: Option<Vec<models::GetContractV1200ResponseDataSubscriptionsInner>>,
    #[serde(rename = "customer_billing_provider_configuration", skip_serializing_if = "Option::is_none")]
    pub customer_billing_provider_configuration: Option<Box<models::GetCustomerBillingProviderConfigurationsV1200ResponseDataInner>>,
    #[serde(rename = "spend_threshold_configuration", skip_serializing_if = "Option::is_none")]
    pub spend_threshold_configuration: Option<Box<models::GetContractV1200ResponseDataInitialSpendThresholdConfiguration>>,
    #[serde(rename = "prepaid_balance_threshold_configuration", skip_serializing_if = "Option::is_none")]
    pub prepaid_balance_threshold_configuration: Option<Box<models::GetContractV1200ResponseDataInitialPrepaidBalanceThresholdConfiguration>>,
    #[serde(rename = "hierarchy_configuration", skip_serializing_if = "Option::is_none")]
    pub hierarchy_configuration: Option<Box<models::GetContractV1200ResponseDataInitialHierarchyConfiguration>>,
}

impl CreateContractV1200ResponseDataContract {
    /// The created contract.
    pub fn new(id: uuid::Uuid, customer_id: uuid::Uuid, created_at: chrono::DateTime<chrono::FixedOffset>, created_by: String, starting_at: chrono::DateTime<chrono::FixedOffset>, usage_statement_schedule: models::GetContractV1200ResponseDataInitialUsageStatementSchedule, usage_filter: Vec<models::CreateContractV1200ResponseDataContractUsageFilterInner>, commits: Vec<models::GetContractV1200ResponseDataInitialCommitsInner>, overrides: Vec<models::GetContractV1200ResponseDataInitialOverridesInner>, scheduled_charges: Vec<models::GetContractV1200ResponseDataInitialScheduledChargesInner>, transitions: Vec<models::GetContractV1200ResponseDataInitialTransitionsInner>) -> CreateContractV1200ResponseDataContract {
        CreateContractV1200ResponseDataContract {
            id,
            customer_id,
            created_at,
            created_by,
            name: None,
            package_id: None,
            uniqueness_key: None,
            rate_card_id: None,
            starting_at,
            ending_before: None,
            net_payment_terms_days: None,
            multiplier_override_prioritization: None,
            scheduled_charges_on_usage_invoices: None,
            custom_fields: None,
            usage_statement_schedule: Box::new(usage_statement_schedule),
            usage_filter,
            commits,
            credits: None,
            has_more: None,
            recurring_commits: None,
            recurring_credits: None,
            overrides,
            scheduled_charges,
            transitions,
            subscriptions: None,
            customer_billing_provider_configuration: None,
            spend_threshold_configuration: None,
            prepaid_balance_threshold_configuration: None,
            hierarchy_configuration: None,
        }
    }
}
/// Defaults to LOWEST_MULTIPLIER, which applies the greatest discount to list prices automatically. EXPLICIT prioritization requires specifying priorities for each multiplier; the one with the lowest priority value will be prioritized first.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MultiplierOverridePrioritization {
    #[serde(rename = "LOWEST_MULTIPLIER")]
    LowestMultiplier,
    #[serde(rename = "lowest_multiplier")]
    LowestMultiplier2,
    #[serde(rename = "EXPLICIT")]
    Explicit,
    #[serde(rename = "explicit")]
    Explicit2,
}

impl Default for MultiplierOverridePrioritization {
    fn default() -> MultiplierOverridePrioritization {
        Self::LowestMultiplier
    }
}
/// Determines which scheduled and commit charges to consolidate onto the Contract's usage invoice. The charge's `timestamp` must match the usage invoice's `ending_before` date for consolidation to occur. This field cannot be modified after a Contract has been created. If this field is omitted, charges will appear on a separate invoice from usage charges.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ScheduledChargesOnUsageInvoices {
    #[serde(rename = "ALL")]
    All,
}

impl Default for ScheduledChargesOnUsageInvoices {
    fn default() -> ScheduledChargesOnUsageInvoices {
        Self::All
    }
}

