/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateContractV1Request {
    #[serde(rename = "customer_id")]
    pub customer_id: uuid::Uuid,
    /// If provided, provisions a customer on a package instead of creating a traditional contract. When specified, only customer_id, starting_at, package_id, uniqueness_key, transition, and custom_fields are allowed.
    #[serde(rename = "package_id", skip_serializing_if = "Option::is_none")]
    pub package_id: Option<uuid::Uuid>,
    /// Selects the package linked to the specified alias as of the contract's start date. Mutually exclusive with package_id.
    #[serde(rename = "package_alias", skip_serializing_if = "Option::is_none")]
    pub package_alias: Option<String>,
    #[serde(rename = "package_customizations", skip_serializing_if = "Option::is_none")]
    pub package_customizations: Option<Box<models::CreateContractV1RequestPackageCustomizations>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Prevents the creation of duplicates. If a request to create a record is made with a previously used uniqueness key, a new record will not be created and the request will fail with a 409 error.
    #[serde(rename = "uniqueness_key", skip_serializing_if = "Option::is_none")]
    pub uniqueness_key: Option<String>,
    /// This field's availability is dependent on your client's configuration.
    #[serde(rename = "netsuite_sales_order_id", skip_serializing_if = "Option::is_none")]
    pub netsuite_sales_order_id: Option<String>,
    /// This field's availability is dependent on your client's configuration.
    #[serde(rename = "salesforce_opportunity_id", skip_serializing_if = "Option::is_none")]
    pub salesforce_opportunity_id: Option<String>,
    #[serde(rename = "net_payment_terms_days", skip_serializing_if = "Option::is_none")]
    pub net_payment_terms_days: Option<f64>,
    #[serde(rename = "rate_card_id", skip_serializing_if = "Option::is_none")]
    pub rate_card_id: Option<uuid::Uuid>,
    /// Selects the rate card linked to the specified alias as of the contract's start date.
    #[serde(rename = "rate_card_alias", skip_serializing_if = "Option::is_none")]
    pub rate_card_alias: Option<String>,
    /// This field's availability is dependent on your client's configuration.
    #[serde(rename = "total_contract_value", skip_serializing_if = "Option::is_none")]
    pub total_contract_value: Option<f64>,
    /// inclusive contract start time
    #[serde(rename = "starting_at")]
    pub starting_at: chrono::DateTime<chrono::FixedOffset>,
    /// exclusive contract end time
    #[serde(rename = "ending_before", skip_serializing_if = "Option::is_none")]
    pub ending_before: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "commits", skip_serializing_if = "Option::is_none")]
    pub commits: Option<Vec<models::CreateContractV1RequestPackageCustomizationsAddCommitsInner>>,
    #[serde(rename = "credits", skip_serializing_if = "Option::is_none")]
    pub credits: Option<Vec<models::CreateContractV1RequestPackageCustomizationsAddCreditsInner>>,
    #[serde(rename = "recurring_commits", skip_serializing_if = "Option::is_none")]
    pub recurring_commits: Option<Vec<models::CreateContractV1RequestPackageCustomizationsAddRecurringCommitsInner>>,
    #[serde(rename = "recurring_credits", skip_serializing_if = "Option::is_none")]
    pub recurring_credits: Option<Vec<models::CreateContractV1RequestPackageCustomizationsAddRecurringCreditsInner>>,
    /// Defaults to LOWEST_MULTIPLIER, which applies the greatest discount to list prices automatically. EXPLICIT prioritization requires specifying priorities for each multiplier; the one with the lowest priority value will be prioritized first. If tiered overrides are used, prioritization must be explicit.
    #[serde(rename = "multiplier_override_prioritization", skip_serializing_if = "Option::is_none")]
    pub multiplier_override_prioritization: Option<MultiplierOverridePrioritization>,
    #[serde(rename = "overrides", skip_serializing_if = "Option::is_none")]
    pub overrides: Option<Vec<models::CreateContractV1RequestPackageCustomizationsAddOverridesInner>>,
    /// This field's availability is dependent on your client's configuration.
    #[serde(rename = "discounts", skip_serializing_if = "Option::is_none")]
    pub discounts: Option<Vec<models::CreateContractV1RequestDiscountsInner>>,
    /// This field's availability is dependent on your client's configuration.
    #[serde(rename = "professional_services", skip_serializing_if = "Option::is_none")]
    pub professional_services: Option<Vec<models::CreateContractV1RequestProfessionalServicesInner>>,
    /// This field's availability is dependent on your client's configuration.
    #[serde(rename = "reseller_royalties", skip_serializing_if = "Option::is_none")]
    pub reseller_royalties: Option<Vec<models::CreateContractV1RequestResellerRoyaltiesInner>>,
    #[serde(rename = "scheduled_charges", skip_serializing_if = "Option::is_none")]
    pub scheduled_charges: Option<Vec<models::CreateContractV1RequestPackageCustomizationsAddScheduledChargesInner>>,
    /// Determines which scheduled and commit charges to consolidate onto the Contract's usage invoice. The charge's `timestamp` must match the usage invoice's `ending_before` date for consolidation to occur. This field cannot be modified after a Contract has been created. If this field is omitted, charges will appear on a separate invoice from usage charges.
    #[serde(rename = "scheduled_charges_on_usage_invoices", skip_serializing_if = "Option::is_none")]
    pub scheduled_charges_on_usage_invoices: Option<ScheduledChargesOnUsageInvoices>,
    #[serde(rename = "transition", skip_serializing_if = "Option::is_none")]
    pub transition: Option<Box<models::CreateContractV1RequestTransition>>,
    #[serde(rename = "usage_filter", skip_serializing_if = "Option::is_none")]
    pub usage_filter: Option<Box<models::GetContractV1200ResponseDataInitialUsageFilterInitial>>,
    #[serde(rename = "usage_statement_schedule", skip_serializing_if = "Option::is_none")]
    pub usage_statement_schedule: Option<Box<models::CreateContractV1RequestUsageStatementSchedule>>,
    /// Custom fields to be added eg. { \"key1\": \"value1\", \"key2\": \"value2\" }
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "billing_provider_configuration", skip_serializing_if = "Option::is_none")]
    pub billing_provider_configuration: Option<Box<models::CreateContractV1RequestBillingProviderConfiguration>>,
    #[serde(rename = "revenue_system_configuration", skip_serializing_if = "Option::is_none")]
    pub revenue_system_configuration: Option<Box<models::CreateContractV1RequestRevenueSystemConfiguration>>,
    #[serde(rename = "spend_threshold_configuration", skip_serializing_if = "Option::is_none")]
    pub spend_threshold_configuration: Option<Box<models::GetContractV1200ResponseDataInitialSpendThresholdConfiguration>>,
    #[serde(rename = "prepaid_balance_threshold_configuration", skip_serializing_if = "Option::is_none")]
    pub prepaid_balance_threshold_configuration: Option<Box<models::GetContractV1200ResponseDataInitialPrepaidBalanceThresholdConfiguration>>,
    /// Spend trackers to attach to this contract. Aliases must be unique within a contract.
    #[serde(rename = "spend_trackers", skip_serializing_if = "Option::is_none")]
    pub spend_trackers: Option<Vec<models::CreateContractV1RequestPackageCustomizationsAddSpendTrackersInner>>,
    /// Optional list of [subscriptions](https://docs.metronome.com/manage-product-access/create-subscription/) to add to the contract.
    #[serde(rename = "subscriptions", skip_serializing_if = "Option::is_none")]
    pub subscriptions: Option<Vec<models::CreateContractV1RequestPackageCustomizationsAddSubscriptionsInner>>,
    #[serde(rename = "hierarchy_configuration", skip_serializing_if = "Option::is_none")]
    pub hierarchy_configuration: Option<Box<models::CreateContractV1RequestHierarchyConfiguration>>,
}

impl CreateContractV1Request {
    pub fn new(customer_id: uuid::Uuid, starting_at: chrono::DateTime<chrono::FixedOffset>) -> CreateContractV1Request {
        CreateContractV1Request {
            customer_id,
            package_id: None,
            package_alias: None,
            package_customizations: None,
            name: None,
            uniqueness_key: None,
            netsuite_sales_order_id: None,
            salesforce_opportunity_id: None,
            net_payment_terms_days: None,
            rate_card_id: None,
            rate_card_alias: None,
            total_contract_value: None,
            starting_at,
            ending_before: None,
            commits: None,
            credits: None,
            recurring_commits: None,
            recurring_credits: None,
            multiplier_override_prioritization: None,
            overrides: None,
            discounts: None,
            professional_services: None,
            reseller_royalties: None,
            scheduled_charges: None,
            scheduled_charges_on_usage_invoices: None,
            transition: None,
            usage_filter: None,
            usage_statement_schedule: None,
            custom_fields: None,
            billing_provider_configuration: None,
            revenue_system_configuration: None,
            spend_threshold_configuration: None,
            prepaid_balance_threshold_configuration: None,
            spend_trackers: None,
            subscriptions: None,
            hierarchy_configuration: None,
        }
    }
}
/// Defaults to LOWEST_MULTIPLIER, which applies the greatest discount to list prices automatically. EXPLICIT prioritization requires specifying priorities for each multiplier; the one with the lowest priority value will be prioritized first. If tiered overrides are used, prioritization must be explicit.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MultiplierOverridePrioritization {
    #[serde(rename = "LOWEST_MULTIPLIER")]
    LowestMultiplier,
    #[serde(rename = "lowest_multiplier")]
    LowestMultiplier2,
    #[serde(rename = "EXPLICIT")]
    Explicit,
    #[serde(rename = "explicit")]
    Explicit2,
}

impl Default for MultiplierOverridePrioritization {
    fn default() -> MultiplierOverridePrioritization {
        Self::LowestMultiplier
    }
}
/// Determines which scheduled and commit charges to consolidate onto the Contract's usage invoice. The charge's `timestamp` must match the usage invoice's `ending_before` date for consolidation to occur. This field cannot be modified after a Contract has been created. If this field is omitted, charges will appear on a separate invoice from usage charges.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ScheduledChargesOnUsageInvoices {
    #[serde(rename = "ALL")]
    All,
}

impl Default for ScheduledChargesOnUsageInvoices {
    fn default() -> ScheduledChargesOnUsageInvoices {
        Self::All
    }
}

