/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateContractV1200ResponseDataContractHasMore : Indicates whether there are more items than the limit for this endpoint. Use the respective list endpoints to get the full lists.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateContractV1200ResponseDataContractHasMore {
    /// Whether there are more commits on this contract than the limit for this endpoint. Use the /contracts/customerCommits/list endpoint to get the full list of commits.
    #[serde(rename = "commits")]
    pub commits: bool,
    /// Whether there are more credits on this contract than the limit for this endpoint. Use the /contracts/customerCredits/list endpoint to get the full list of credits.
    #[serde(rename = "credits")]
    pub credits: bool,
}

impl CreateContractV1200ResponseDataContractHasMore {
    /// Indicates whether there are more items than the limit for this endpoint. Use the respective list endpoints to get the full lists.
    pub fn new(commits: bool, credits: bool) -> CreateContractV1200ResponseDataContractHasMore {
        CreateContractV1200ResponseDataContractHasMore {
            commits,
            credits,
        }
    }
}

