/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCustomerCommitV1Request {
    #[serde(rename = "customer_id")]
    pub customer_id: uuid::Uuid,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "rate_type", skip_serializing_if = "Option::is_none")]
    pub rate_type: Option<RateType>,
    /// displayed on invoices
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Used only in UI/API. It is not exposed to end customers.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// If multiple credits or commits are applicable, the one with the lower priority will apply first.
    #[serde(rename = "priority")]
    pub priority: f64,
    /// ID of the fixed product associated with the commit. This is required because products are used to invoice the commit amount.
    #[serde(rename = "product_id")]
    pub product_id: uuid::Uuid,
    #[serde(rename = "access_schedule")]
    pub access_schedule: Box<models::CreateContractV1RequestPackageCustomizationsAddCommitsInnerAccessSchedule>,
    #[serde(rename = "invoice_schedule", skip_serializing_if = "Option::is_none")]
    pub invoice_schedule: Option<Box<models::CreateContractV1RequestPackageCustomizationsAddCommitsInnerInvoiceSchedule>>,
    /// The contract that this commit will be billed on. This is required for \"POSTPAID\" commits and for \"PREPAID\" commits unless there is no invoice schedule above (i.e., the commit is 'free'), or if do_not_invoice is set to true.
    #[serde(rename = "invoice_contract_id", skip_serializing_if = "Option::is_none")]
    pub invoice_contract_id: Option<uuid::Uuid>,
    /// Which products the commit applies to. If applicable_product_ids, applicable_product_tags or specifiers are not provided, the commit applies to all products.
    #[serde(rename = "applicable_product_ids", skip_serializing_if = "Option::is_none")]
    pub applicable_product_ids: Option<Vec<uuid::Uuid>>,
    /// Which tags the commit applies to. If applicable_product_ids, applicable_product_tags or specifiers are not provided, the commit applies to all products.
    #[serde(rename = "applicable_product_tags", skip_serializing_if = "Option::is_none")]
    pub applicable_product_tags: Option<Vec<String>>,
    /// Which contract the commit applies to. If not provided, the commit applies to all contracts.
    #[serde(rename = "applicable_contract_ids", skip_serializing_if = "Option::is_none")]
    pub applicable_contract_ids: Option<Vec<String>>,
    /// List of filters that determine what kind of customer usage draws down a commit or credit. A customer's usage needs to meet the condition of at least one of the specifiers to contribute to a commit's or credit's drawdown. This field cannot be used together with `applicable_product_ids` or `applicable_product_tags`.
    #[serde(rename = "specifiers", skip_serializing_if = "Option::is_none")]
    pub specifiers: Option<Vec<models::GetContractV1200ResponseDataInitialCommitsInnerSpecifiersInner>>,
    /// This field's availability is dependent on your client's configuration.
    #[serde(rename = "netsuite_sales_order_id", skip_serializing_if = "Option::is_none")]
    pub netsuite_sales_order_id: Option<String>,
    /// This field's availability is dependent on your client's configuration.
    #[serde(rename = "salesforce_opportunity_id", skip_serializing_if = "Option::is_none")]
    pub salesforce_opportunity_id: Option<String>,
    /// Custom fields to be added eg. { \"key1\": \"value1\", \"key2\": \"value2\" }
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<std::collections::HashMap<String, String>>,
    /// Prevents the creation of duplicates. If a request to create a commit or credit is made with a uniqueness key that was previously used to create a commit or credit, a new record will not be created and the request will fail with a 409 error.
    #[serde(rename = "uniqueness_key", skip_serializing_if = "Option::is_none")]
    pub uniqueness_key: Option<String>,
}

impl CreateCustomerCommitV1Request {
    pub fn new(customer_id: uuid::Uuid, r#type: Type, priority: f64, product_id: uuid::Uuid, access_schedule: models::CreateContractV1RequestPackageCustomizationsAddCommitsInnerAccessSchedule) -> CreateCustomerCommitV1Request {
        CreateCustomerCommitV1Request {
            customer_id,
            r#type,
            rate_type: None,
            name: None,
            description: None,
            priority,
            product_id,
            access_schedule: Box::new(access_schedule),
            invoice_schedule: None,
            invoice_contract_id: None,
            applicable_product_ids: None,
            applicable_product_tags: None,
            applicable_contract_ids: None,
            specifiers: None,
            netsuite_sales_order_id: None,
            salesforce_opportunity_id: None,
            custom_fields: None,
            uniqueness_key: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "PREPAID")]
    Prepaid,
    #[serde(rename = "prepaid")]
    Prepaid2,
    #[serde(rename = "POSTPAID")]
    Postpaid,
    #[serde(rename = "postpaid")]
    Postpaid2,
}

impl Default for Type {
    fn default() -> Type {
        Self::Prepaid
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RateType {
    #[serde(rename = "COMMIT_RATE")]
    CommitRate,
    #[serde(rename = "commit_rate")]
    CommitRate2,
    #[serde(rename = "LIST_RATE")]
    ListRate,
    #[serde(rename = "list_rate")]
    ListRate2,
}

impl Default for RateType {
    fn default() -> RateType {
        Self::CommitRate
    }
}

