/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateContractV1RequestPackageCustomizationsAddSpendTrackersInner {
    /// Human-readable identifier, unique per contract.
    #[serde(rename = "alias")]
    pub alias: String,
    #[serde(rename = "credit_type_id")]
    pub credit_type_id: uuid::Uuid,
    #[serde(rename = "reset_frequency")]
    pub reset_frequency: ResetFrequency,
    #[serde(rename = "applicable_spend_specifiers")]
    pub applicable_spend_specifiers: Vec<models::GetContractV1200ResponseDataInitialSpendTrackersInnerApplicableSpendSpecifiersInner>,
}

impl CreateContractV1RequestPackageCustomizationsAddSpendTrackersInner {
    pub fn new(alias: String, credit_type_id: uuid::Uuid, reset_frequency: ResetFrequency, applicable_spend_specifiers: Vec<models::GetContractV1200ResponseDataInitialSpendTrackersInnerApplicableSpendSpecifiersInner>) -> CreateContractV1RequestPackageCustomizationsAddSpendTrackersInner {
        CreateContractV1RequestPackageCustomizationsAddSpendTrackersInner {
            alias,
            credit_type_id,
            reset_frequency,
            applicable_spend_specifiers,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ResetFrequency {
    #[serde(rename = "BILLING_PERIOD")]
    BillingPeriod,
}

impl Default for ResetFrequency {
    fn default() -> ResetFrequency {
        Self::BillingPeriod
    }
}

