/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreditLedgerEntry {
    /// an amount representing the change to the customer's credit balance
    #[serde(rename = "amount")]
    pub amount: f64,
    #[serde(rename = "reason")]
    pub reason: String,
    /// the running balance for this credit type at the time of the ledger entry, including all preceding charges
    #[serde(rename = "running_balance")]
    pub running_balance: f64,
    #[serde(rename = "effective_at")]
    pub effective_at: String,
    #[serde(rename = "created_by")]
    pub created_by: String,
    /// the credit grant this entry is related to
    #[serde(rename = "credit_grant_id")]
    pub credit_grant_id: uuid::Uuid,
    /// if this entry is a deduction, the Metronome ID of the invoice where the credit deduction was consumed; if this entry is a grant, the Metronome ID of the invoice where the grant's paid_amount was charged
    #[serde(rename = "invoice_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub invoice_id: Option<Option<uuid::Uuid>>,
}

impl CreditLedgerEntry {
    pub fn new(amount: f64, reason: String, running_balance: f64, effective_at: String, created_by: String, credit_grant_id: uuid::Uuid) -> CreditLedgerEntry {
        CreditLedgerEntry {
            amount,
            reason,
            running_balance,
            effective_at,
            created_by,
            credit_grant_id,
            invoice_id: None,
        }
    }
}

