/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreditSegmentStartLedgerEntry {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "timestamp")]
    pub timestamp: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "amount")]
    pub amount: f64,
    #[serde(rename = "segment_id")]
    pub segment_id: uuid::Uuid,
}

impl CreditSegmentStartLedgerEntry {
    pub fn new(r#type: Type, timestamp: chrono::DateTime<chrono::FixedOffset>, amount: f64, segment_id: uuid::Uuid) -> CreditSegmentStartLedgerEntry {
        CreditSegmentStartLedgerEntry {
            r#type,
            timestamp,
            amount,
            segment_id,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "CREDIT_SEGMENT_START")]
    CreditSegmentStart,
}

impl Default for Type {
    fn default() -> Type {
        Self::CreditSegmentStart
    }
}

