/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreditTypeLedgerStartingBalance {
    /// the starting balance, including all posted grants, deductions, and expirations that happened at or before the effective_at timestamp
    #[serde(rename = "excluding_pending")]
    pub excluding_pending: f64,
    /// the excluding_pending balance plus any pending activity that has not been posted at the time of the query
    #[serde(rename = "including_pending")]
    pub including_pending: f64,
    /// the starting_on request parameter (if supplied) or the first credit grant's effective_at date
    #[serde(rename = "effective_at")]
    pub effective_at: chrono::DateTime<chrono::FixedOffset>,
}

impl CreditTypeLedgerStartingBalance {
    pub fn new(excluding_pending: f64, including_pending: f64, effective_at: chrono::DateTime<chrono::FixedOffset>) -> CreditTypeLedgerStartingBalance {
        CreditTypeLedgerStartingBalance {
            excluding_pending,
            including_pending,
            effective_at,
        }
    }
}

