/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreditType {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
}

impl CreditType {
    pub fn new(name: String, id: uuid::Uuid) -> CreditType {
        CreditType {
            name,
            id,
        }
    }
}

