/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerAndContract {
    /// the Metronome ID of the customer
    #[serde(rename = "customer_id")]
    pub customer_id: uuid::Uuid,
    /// aliases for this customer that can be used instead of the Metronome customer ID in usage events
    #[serde(rename = "ingest_aliases")]
    pub ingest_aliases: Vec<String>,
    #[serde(rename = "customer_name")]
    pub customer_name: String,
    /// Custom fields to be added eg. { \"key1\": \"value1\", \"key2\": \"value2\" }
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "contract_id")]
    pub contract_id: uuid::Uuid,
}

impl CustomerAndContract {
    pub fn new(customer_id: uuid::Uuid, ingest_aliases: Vec<String>, customer_name: String, contract_id: uuid::Uuid) -> CustomerAndContract {
        CustomerAndContract {
            customer_id,
            ingest_aliases,
            customer_name,
            custom_fields: None,
            contract_id,
        }
    }
}

