/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerConfigPayload {
    /// The Salesforce account ID for the customer
    #[serde(rename = "salesforce_account_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub salesforce_account_id: Option<Option<String>>,
}

impl CustomerConfigPayload {
    pub fn new() -> CustomerConfigPayload {
        CustomerConfigPayload {
            salesforce_account_id: None,
        }
    }
}

