/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerContractNamedScheduleSegmentsInner {
    #[serde(rename = "value", deserialize_with = "Option::deserialize")]
    pub value: Option<serde_json::Value>,
    #[serde(rename = "starting_at")]
    pub starting_at: String,
    #[serde(rename = "ending_before", skip_serializing_if = "Option::is_none")]
    pub ending_before: Option<String>,
}

impl CustomerContractNamedScheduleSegmentsInner {
    pub fn new(value: Option<serde_json::Value>, starting_at: String) -> CustomerContractNamedScheduleSegmentsInner {
        CustomerContractNamedScheduleSegmentsInner {
            value,
            starting_at,
            ending_before: None,
        }
    }
}

