/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerBillingProviderConfigurationOutput {
    /// ID of the created configuration
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "billing_provider", skip_serializing_if = "Option::is_none")]
    pub billing_provider: Option<models::BillingProviderType>,
    /// ID of the customer this configuration is associated with.
    #[serde(rename = "customer_id", skip_serializing_if = "Option::is_none")]
    pub customer_id: Option<uuid::Uuid>,
    /// Configuration for the billing provider. The structure of this object is specific to the billing provider and delivery method combination.
    #[serde(rename = "configuration", skip_serializing_if = "Option::is_none")]
    pub configuration: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// ID of the delivery method used for this customer configuration.
    #[serde(rename = "delivery_method_id", skip_serializing_if = "Option::is_none")]
    pub delivery_method_id: Option<uuid::Uuid>,
    #[serde(rename = "tax_provider", skip_serializing_if = "Option::is_none")]
    pub tax_provider: Option<models::TaxProviderType>,
}

impl CustomerBillingProviderConfigurationOutput {
    pub fn new() -> CustomerBillingProviderConfigurationOutput {
        CustomerBillingProviderConfigurationOutput {
            id: None,
            billing_provider: None,
            customer_id: None,
            configuration: None,
            delivery_method_id: None,
            tax_provider: None,
        }
    }
}

