/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerBillingProviderArchivePayload {
    /// Array of billing provider configuration IDs to archive
    #[serde(rename = "customer_billing_provider_configuration_ids")]
    pub customer_billing_provider_configuration_ids: Vec<uuid::Uuid>,
    /// The customer ID the billing provider configurations belong to
    #[serde(rename = "customer_id")]
    pub customer_id: uuid::Uuid,
}

impl CustomerBillingProviderArchivePayload {
    pub fn new(customer_billing_provider_configuration_ids: Vec<uuid::Uuid>, customer_id: uuid::Uuid) -> CustomerBillingProviderArchivePayload {
        CustomerBillingProviderArchivePayload {
            customer_billing_provider_configuration_ids,
            customer_id,
        }
    }
}

