/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerPlanDetail {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    /// The start date of the plan
    #[serde(rename = "starting_on")]
    pub starting_on: chrono::DateTime<chrono::FixedOffset>,
    /// The end date of the plan
    #[serde(rename = "ending_before", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ending_before: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// Custom fields to be added eg. { \"key1\": \"value1\", \"key2\": \"value2\" }
    #[serde(rename = "custom_fields")]
    pub custom_fields: std::collections::HashMap<String, String>,
    #[serde(rename = "customer_plan_id")]
    pub customer_plan_id: uuid::Uuid,
}

impl CustomerPlanDetail {
    pub fn new(id: uuid::Uuid, name: String, starting_on: chrono::DateTime<chrono::FixedOffset>, custom_fields: std::collections::HashMap<String, String>, customer_plan_id: uuid::Uuid) -> CustomerPlanDetail {
        CustomerPlanDetail {
            id,
            name,
            starting_on,
            ending_before: None,
            custom_fields,
            customer_plan_id,
        }
    }
}

