/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerAlert {
    /// The status of the threshold notification. If the notification is archived, null will be returned.
    #[serde(rename = "customer_status", deserialize_with = "Option::deserialize")]
    pub customer_status: Option<CustomerStatus>,
    /// If present, indicates the reason the threshold notification was triggered.
    #[serde(rename = "triggered_by", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub triggered_by: Option<Option<String>>,
    #[serde(rename = "alert")]
    pub alert: Box<models::Alert>,
}

impl CustomerAlert {
    pub fn new(customer_status: Option<CustomerStatus>, alert: models::Alert) -> CustomerAlert {
        CustomerAlert {
            customer_status,
            triggered_by: None,
            alert: Box::new(alert),
        }
    }
}
/// The status of the threshold notification. If the notification is archived, null will be returned.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CustomerStatus {
    #[serde(rename = "ok")]
    Ok,
    #[serde(rename = "in_alarm")]
    InAlarm,
    #[serde(rename = "evaluating")]
    Evaluating,
}

impl Default for CustomerStatus {
    fn default() -> CustomerStatus {
        Self::Ok
    }
}

