/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerBillingProviderConfigurationInput {
    #[serde(rename = "billing_provider")]
    pub billing_provider: models::BillingProviderType,
    #[serde(rename = "customer_id")]
    pub customer_id: uuid::Uuid,
    #[serde(rename = "tax_provider", skip_serializing_if = "Option::is_none")]
    pub tax_provider: Option<models::TaxProviderType>,
    /// Configuration for the billing provider. The structure of this object is specific to the billing provider and delivery method combination. Defaults to an empty object, however, for most billing provider + delivery method combinations, it will not be a valid configuration.  For AWS marketplace configurations, the aws_is_subscription_product flag can be used to indicate a product with usage-based pricing.  More information can be found [here](https://docs.metronome.com/invoice-customers/solutions/marketplaces/invoice-aws/#provision-aws-marketplace-customers-in-metronome).
    #[serde(rename = "configuration", skip_serializing_if = "Option::is_none")]
    pub configuration: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// ID of the delivery method to use for this customer. If not provided, the `delivery_method` must be provided.
    #[serde(rename = "delivery_method_id", skip_serializing_if = "Option::is_none")]
    pub delivery_method_id: Option<uuid::Uuid>,
    #[serde(rename = "delivery_method", skip_serializing_if = "Option::is_none")]
    pub delivery_method: Option<models::BillingProviderDeliveryMethodType>,
}

impl CustomerBillingProviderConfigurationInput {
    pub fn new(billing_provider: models::BillingProviderType, customer_id: uuid::Uuid) -> CustomerBillingProviderConfigurationInput {
        CustomerBillingProviderConfigurationInput {
            billing_provider,
            customer_id,
            tax_provider: None,
            configuration: None,
            delivery_method_id: None,
            delivery_method: None,
        }
    }
}

