/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditNotificationConfigPayload {
    /// The ID of the notification configuration to edit. Not provided when updating the configuration for system events 
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// Set to true to enable webhook messages for the notification indicated in the policy, false to disable. Only supported by system lifecycle events. 
    #[serde(rename = "is_enabled", skip_serializing_if = "Option::is_none")]
    pub is_enabled: Option<bool>,
    #[serde(rename = "policy")]
    pub policy: Box<models::EditNotificationConfigPayloadPolicy>,
}

impl EditNotificationConfigPayload {
    pub fn new(policy: models::EditNotificationConfigPayloadPolicy) -> EditNotificationConfigPayload {
        EditNotificationConfigPayload {
            id: None,
            is_enabled: None,
            policy: Box::new(policy),
        }
    }
}

