/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditCreditV2Request {
    /// ID of the customer whose credit is being edited
    #[serde(rename = "customer_id")]
    pub customer_id: uuid::Uuid,
    /// ID of the credit to edit
    #[serde(rename = "credit_id")]
    pub credit_id: uuid::Uuid,
    /// Updated name for the credit
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Updated description for the credit
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "access_schedule", skip_serializing_if = "Option::is_none")]
    pub access_schedule: Option<Box<models::GetContractEditHistoryV2200ResponseDataInnerUpdateCommitsInnerAccessSchedule>>,
    /// Which products the credit applies to. If both applicable_product_ids and applicable_product_tags are not provided, the credit applies to all products.
    #[serde(rename = "applicable_product_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub applicable_product_ids: Option<Option<Vec<uuid::Uuid>>>,
    /// Which tags the credit applies to. If both applicable_product_ids and applicable_product_tags are not provided, the credit applies to all products.
    #[serde(rename = "applicable_product_tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub applicable_product_tags: Option<Option<Vec<String>>>,
    /// Which contracts the customer-level credit applies to. If set to null, the credit applies to all of the customer's contracts. This field cannot be set on a contract-level credit.
    #[serde(rename = "applicable_contract_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub applicable_contract_ids: Option<Option<Vec<uuid::Uuid>>>,
    /// List of filters that determine what kind of customer usage draws down a commit or credit. A customer's usage needs to meet the condition of at least one of the specifiers to contribute to a commit's or credit's drawdown. This field cannot be used together with `applicable_product_ids` or `applicable_product_tags`. Instead, to target usage by product or product tag, pass those values in the body of `specifiers`.
    #[serde(rename = "specifiers", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub specifiers: Option<Option<Vec<models::GetContractV1200ResponseDataInitialCommitsInnerSpecifiersInner>>>,
    #[serde(rename = "product_id", skip_serializing_if = "Option::is_none")]
    pub product_id: Option<uuid::Uuid>,
    /// If multiple commits are applicable, the one with the lower priority will apply first.
    #[serde(rename = "priority", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub priority: Option<Option<f64>>,
    /// If provided, updates the credit to use the specified rate type for current and future invoices. Previously finalized invoices will need to be voided and regenerated to reflect the rate type change.
    #[serde(rename = "rate_type", skip_serializing_if = "Option::is_none")]
    pub rate_type: Option<RateType>,
    #[serde(rename = "hierarchy_configuration", skip_serializing_if = "Option::is_none")]
    pub hierarchy_configuration: Option<Box<models::GetContractV1200ResponseDataInitialCommitsInnerHierarchyConfiguration>>,
}

impl EditCreditV2Request {
    pub fn new(customer_id: uuid::Uuid, credit_id: uuid::Uuid) -> EditCreditV2Request {
        EditCreditV2Request {
            customer_id,
            credit_id,
            name: None,
            description: None,
            access_schedule: None,
            applicable_product_ids: None,
            applicable_product_tags: None,
            applicable_contract_ids: None,
            specifiers: None,
            product_id: None,
            priority: None,
            rate_type: None,
            hierarchy_configuration: None,
        }
    }
}
/// If provided, updates the credit to use the specified rate type for current and future invoices. Previously finalized invoices will need to be voided and regenerated to reflect the rate type change.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RateType {
    #[serde(rename = "LIST_RATE")]
    ListRate,
    #[serde(rename = "list_rate")]
    ListRate2,
    #[serde(rename = "COMMIT_RATE")]
    CommitRate,
    #[serde(rename = "commit_rate")]
    CommitRate2,
}

impl Default for RateType {
    fn default() -> RateType {
        Self::ListRate
    }
}

