/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditContractPayload {
    /// ID of the customer whose contract is being edited
    #[serde(rename = "customer_id")]
    pub customer_id: uuid::Uuid,
    /// ID of the contract being edited
    #[serde(rename = "contract_id")]
    pub contract_id: uuid::Uuid,
    /// Prevents the creation of duplicates. If a request to create a record is made with a previously used uniqueness key, a new record will not be created and the request will fail with a 409 error.
    #[serde(rename = "uniqueness_key", skip_serializing_if = "Option::is_none")]
    pub uniqueness_key: Option<String>,
    #[serde(rename = "add_commits", skip_serializing_if = "Option::is_none")]
    pub add_commits: Option<Vec<models::CommitInputV2>>,
    #[serde(rename = "add_credits", skip_serializing_if = "Option::is_none")]
    pub add_credits: Option<Vec<models::CreditInputV2>>,
    #[serde(rename = "add_recurring_commits", skip_serializing_if = "Option::is_none")]
    pub add_recurring_commits: Option<Vec<models::RecurringCommitInputV2>>,
    #[serde(rename = "add_recurring_credits", skip_serializing_if = "Option::is_none")]
    pub add_recurring_credits: Option<Vec<models::RecurringCreditInputV2>>,
    #[serde(rename = "add_discounts", skip_serializing_if = "Option::is_none")]
    pub add_discounts: Option<Vec<models::DiscountInputV2>>,
    #[serde(rename = "add_overrides", skip_serializing_if = "Option::is_none")]
    pub add_overrides: Option<Vec<models::OverrideInputV2>>,
    #[serde(rename = "add_scheduled_charges", skip_serializing_if = "Option::is_none")]
    pub add_scheduled_charges: Option<Vec<models::ScheduledChargeInputV2>>,
    /// This field's availability is dependent on your client's configuration.
    #[serde(rename = "add_professional_services", skip_serializing_if = "Option::is_none")]
    pub add_professional_services: Option<Vec<models::ProServiceInput>>,
    #[serde(rename = "add_reseller_royalties", skip_serializing_if = "Option::is_none")]
    pub add_reseller_royalties: Option<Vec<models::ResellerRoyaltyOrUpdateInput>>,
    /// Optional list of [subscriptions](https://docs.metronome.com/manage-product-access/create-subscription/) to add to the contract.
    #[serde(rename = "add_subscriptions", skip_serializing_if = "Option::is_none")]
    pub add_subscriptions: Option<Vec<models::SubscriptionInputV2>>,
    #[serde(rename = "add_spend_threshold_configuration", skip_serializing_if = "Option::is_none")]
    pub add_spend_threshold_configuration: Option<Box<models::SpendThresholdConfigurationV2>>,
    #[serde(rename = "add_prepaid_balance_threshold_configuration", skip_serializing_if = "Option::is_none")]
    pub add_prepaid_balance_threshold_configuration: Option<models::PrepaidBalanceThresholdConfigurationV2>,
    #[serde(rename = "add_billing_provider_configuration_update", skip_serializing_if = "Option::is_none")]
    pub add_billing_provider_configuration_update: Option<models::BillingProviderConfigurationUpdate>,
    #[serde(rename = "add_revenue_system_configuration_update", skip_serializing_if = "Option::is_none")]
    pub add_revenue_system_configuration_update: Option<Box<models::RevenueSystemConfigurationUpdate>>,
    /// Spend trackers to add to this contract. Aliases must be unique within a contract.
    #[serde(rename = "add_spend_trackers", skip_serializing_if = "Option::is_none")]
    pub add_spend_trackers: Option<Vec<models::SpendTrackerInput>>,
    /// Value to update the contract name to. If not provided, the contract name will remain unchanged.
    #[serde(rename = "update_contract_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub update_contract_name: Option<Option<String>>,
    #[serde(rename = "update_scheduled_charges", skip_serializing_if = "Option::is_none")]
    pub update_scheduled_charges: Option<Vec<models::UpdateScheduledChargeInput>>,
    #[serde(rename = "update_commits", skip_serializing_if = "Option::is_none")]
    pub update_commits: Option<Vec<models::UpdateCommitInput>>,
    #[serde(rename = "update_credits", skip_serializing_if = "Option::is_none")]
    pub update_credits: Option<Vec<models::UpdateCreditInput>>,
    /// Edits to these recurring commits will only affect commits whose access schedules has not started. Expired commits, and commits with an active access schedule will remain unchanged.
    #[serde(rename = "update_recurring_commits", skip_serializing_if = "Option::is_none")]
    pub update_recurring_commits: Option<Vec<models::UpdateRecurringCommitInput>>,
    /// Edits to these recurring credits will only affect credits whose access schedules has not started. Expired credits, and credits with an active access schedule will remain unchanged.
    #[serde(rename = "update_recurring_credits", skip_serializing_if = "Option::is_none")]
    pub update_recurring_credits: Option<Vec<models::UpdateRecurringCreditInput>>,
    /// Optional list of subscriptions to update.
    #[serde(rename = "update_subscriptions", skip_serializing_if = "Option::is_none")]
    pub update_subscriptions: Option<Vec<models::UpdateSubscriptionInput>>,
    #[serde(rename = "update_spend_threshold_configuration", skip_serializing_if = "Option::is_none")]
    pub update_spend_threshold_configuration: Option<Box<models::UpdateSpendThresholdConfiguration>>,
    #[serde(rename = "update_prepaid_balance_threshold_configuration", skip_serializing_if = "Option::is_none")]
    pub update_prepaid_balance_threshold_configuration: Option<Box<models::UpdatePrepaidBalanceThresholdConfiguration>>,
    /// RFC 3339 timestamp indicating when the contract will end (exclusive).
    #[serde(rename = "update_contract_end_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub update_contract_end_date: Option<Option<String>>,
    /// Number of days after issuance of invoice after which the invoice is due (e.g. Net 30).
    #[serde(rename = "update_net_payment_terms_days", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub update_net_payment_terms_days: Option<Option<f64>>,
    /// If true, allows setting the contract end date earlier than the end_timestamp of existing finalized invoices. Finalized invoices will be unchanged; if you want to incorporate the new end date, you can void and regenerate finalized usage invoices. Defaults to true.
    #[serde(rename = "allow_contract_ending_before_finalized_invoice", skip_serializing_if = "Option::is_none")]
    pub allow_contract_ending_before_finalized_invoice: Option<bool>,
    /// IDs of commits to archive
    #[serde(rename = "archive_commits", skip_serializing_if = "Option::is_none")]
    pub archive_commits: Option<Vec<models::VoidInvoiceV1200ResponseData>>,
    /// IDs of credits to archive
    #[serde(rename = "archive_credits", skip_serializing_if = "Option::is_none")]
    pub archive_credits: Option<Vec<models::VoidInvoiceV1200ResponseData>>,
    /// IDs of scheduled charges to archive
    #[serde(rename = "archive_scheduled_charges", skip_serializing_if = "Option::is_none")]
    pub archive_scheduled_charges: Option<Vec<models::VoidInvoiceV1200ResponseData>>,
    /// Aliases of spend trackers to archive.
    #[serde(rename = "archive_spend_trackers", skip_serializing_if = "Option::is_none")]
    pub archive_spend_trackers: Option<Vec<String>>,
    /// IDs of overrides to remove
    #[serde(rename = "remove_overrides", skip_serializing_if = "Option::is_none")]
    pub remove_overrides: Option<Vec<models::VoidInvoiceV1200ResponseData>>,
}

impl EditContractPayload {
    pub fn new(customer_id: uuid::Uuid, contract_id: uuid::Uuid) -> EditContractPayload {
        EditContractPayload {
            customer_id,
            contract_id,
            uniqueness_key: None,
            add_commits: None,
            add_credits: None,
            add_recurring_commits: None,
            add_recurring_credits: None,
            add_discounts: None,
            add_overrides: None,
            add_scheduled_charges: None,
            add_professional_services: None,
            add_reseller_royalties: None,
            add_subscriptions: None,
            add_spend_threshold_configuration: None,
            add_prepaid_balance_threshold_configuration: None,
            add_billing_provider_configuration_update: None,
            add_revenue_system_configuration_update: None,
            add_spend_trackers: None,
            update_contract_name: None,
            update_scheduled_charges: None,
            update_commits: None,
            update_credits: None,
            update_recurring_commits: None,
            update_recurring_credits: None,
            update_subscriptions: None,
            update_spend_threshold_configuration: None,
            update_prepaid_balance_threshold_configuration: None,
            update_contract_end_date: None,
            update_net_payment_terms_days: None,
            allow_contract_ending_before_finalized_invoice: None,
            archive_commits: None,
            archive_credits: None,
            archive_scheduled_charges: None,
            archive_spend_trackers: None,
            remove_overrides: None,
        }
    }
}

