/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditNotificationConfigV2400Response {
    #[serde(rename = "code")]
    pub code: Code,
    #[serde(rename = "message")]
    pub message: String,
}

impl EditNotificationConfigV2400Response {
    pub fn new(code: Code, message: String) -> EditNotificationConfigV2400Response {
        EditNotificationConfigV2400Response {
            code,
            message,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Code {
    #[serde(rename = "NotificationConfigNotFound")]
    NotificationConfigNotFound,
    #[serde(rename = "BadRequest")]
    BadRequest,
}

impl Default for Code {
    fn default() -> Code {
        Self::NotificationConfigNotFound
    }
}

