/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EditContractV2RequestAddCommitsInnerPaymentGateConfigStripeConfig : Only applicable if using STRIPE as your payment gateway type.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditContractV2RequestAddCommitsInnerPaymentGateConfigStripeConfig {
    /// If left blank, will default to INVOICE
    #[serde(rename = "payment_type")]
    pub payment_type: PaymentType,
    /// Metadata to be added to the Stripe invoice. Only applicable if using INVOICE as your payment type.
    #[serde(rename = "invoice_metadata", skip_serializing_if = "Option::is_none")]
    pub invoice_metadata: Option<std::collections::HashMap<String, String>>,
    /// If true, the payment will be made assuming the customer is present (i.e. on session).   If false, the payment will be made assuming the customer is not present (i.e. off session).  For cardholders from a country with an e-mandate requirement (e.g. India), the payment may be declined.  If left blank, will default to false.
    #[serde(rename = "on_session_payment", skip_serializing_if = "Option::is_none")]
    pub on_session_payment: Option<bool>,
}

impl EditContractV2RequestAddCommitsInnerPaymentGateConfigStripeConfig {
    /// Only applicable if using STRIPE as your payment gateway type.
    pub fn new(payment_type: PaymentType) -> EditContractV2RequestAddCommitsInnerPaymentGateConfigStripeConfig {
        EditContractV2RequestAddCommitsInnerPaymentGateConfigStripeConfig {
            payment_type,
            invoice_metadata: None,
            on_session_payment: None,
        }
    }
}
/// If left blank, will default to INVOICE
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaymentType {
    #[serde(rename = "INVOICE")]
    Invoice,
    #[serde(rename = "PAYMENT_INTENT")]
    PaymentIntent,
}

impl Default for PaymentType {
    fn default() -> PaymentType {
        Self::Invoice
    }
}

