/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExternalInvoice {
    #[serde(rename = "billing_provider_type")]
    pub billing_provider_type: models::BillingProviderType,
    #[serde(rename = "invoice_id", skip_serializing_if = "Option::is_none")]
    pub invoice_id: Option<String>,
    #[serde(rename = "issued_at_timestamp", skip_serializing_if = "Option::is_none")]
    pub issued_at_timestamp: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "external_status", skip_serializing_if = "Option::is_none")]
    pub external_status: Option<models::ExternalInvoiceStatus>,
    /// A URL to the PDF of the invoice, if available from the billing provider.
    #[serde(rename = "pdf_url", skip_serializing_if = "Option::is_none")]
    pub pdf_url: Option<String>,
    #[serde(rename = "tax", skip_serializing_if = "Option::is_none")]
    pub tax: Option<Box<models::ExternalInvoiceTax>>,
    /// The total amount invoiced, if available from the billing provider.
    #[serde(rename = "invoiced_total", skip_serializing_if = "Option::is_none")]
    pub invoiced_total: Option<f64>,
    /// The subtotal amount invoiced, if available from the billing provider.
    #[serde(rename = "invoiced_sub_total", skip_serializing_if = "Option::is_none")]
    pub invoiced_sub_total: Option<f64>,
    /// Error message from the billing provider, if available.
    #[serde(rename = "billing_provider_error", skip_serializing_if = "Option::is_none")]
    pub billing_provider_error: Option<String>,
    /// The ID of the payment in the external system, if available.
    #[serde(rename = "external_payment_id", skip_serializing_if = "Option::is_none")]
    pub external_payment_id: Option<String>,
}

impl ExternalInvoice {
    pub fn new(billing_provider_type: models::BillingProviderType) -> ExternalInvoice {
        ExternalInvoice {
            billing_provider_type,
            invoice_id: None,
            issued_at_timestamp: None,
            external_status: None,
            pdf_url: None,
            tax: None,
            invoiced_total: None,
            invoiced_sub_total: None,
            billing_provider_error: None,
            external_payment_id: None,
        }
    }
}

