/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContractEditHistoryV2200ResponseDataInnerAddResellerRoyaltiesInner {
    #[serde(rename = "reseller_type")]
    pub reseller_type: ResellerType,
    #[serde(rename = "fraction", skip_serializing_if = "Option::is_none")]
    pub fraction: Option<f64>,
    #[serde(rename = "netsuite_reseller_id", skip_serializing_if = "Option::is_none")]
    pub netsuite_reseller_id: Option<String>,
    #[serde(rename = "starting_at", skip_serializing_if = "Option::is_none")]
    pub starting_at: Option<String>,
    #[serde(rename = "ending_before", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ending_before: Option<Option<String>>,
    #[serde(rename = "applicable_product_tags", skip_serializing_if = "Option::is_none")]
    pub applicable_product_tags: Option<Vec<String>>,
    #[serde(rename = "applicable_product_ids", skip_serializing_if = "Option::is_none")]
    pub applicable_product_ids: Option<Vec<String>>,
    #[serde(rename = "reseller_contract_value", skip_serializing_if = "Option::is_none")]
    pub reseller_contract_value: Option<f64>,
    #[serde(rename = "aws_account_number", skip_serializing_if = "Option::is_none")]
    pub aws_account_number: Option<String>,
    #[serde(rename = "aws_payer_reference_id", skip_serializing_if = "Option::is_none")]
    pub aws_payer_reference_id: Option<String>,
    #[serde(rename = "aws_offer_id", skip_serializing_if = "Option::is_none")]
    pub aws_offer_id: Option<String>,
    #[serde(rename = "gcp_account_id", skip_serializing_if = "Option::is_none")]
    pub gcp_account_id: Option<String>,
    #[serde(rename = "gcp_offer_id", skip_serializing_if = "Option::is_none")]
    pub gcp_offer_id: Option<String>,
}

impl GetContractEditHistoryV2200ResponseDataInnerAddResellerRoyaltiesInner {
    pub fn new(reseller_type: ResellerType) -> GetContractEditHistoryV2200ResponseDataInnerAddResellerRoyaltiesInner {
        GetContractEditHistoryV2200ResponseDataInnerAddResellerRoyaltiesInner {
            reseller_type,
            fraction: None,
            netsuite_reseller_id: None,
            starting_at: None,
            ending_before: None,
            applicable_product_tags: None,
            applicable_product_ids: None,
            reseller_contract_value: None,
            aws_account_number: None,
            aws_payer_reference_id: None,
            aws_offer_id: None,
            gcp_account_id: None,
            gcp_offer_id: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ResellerType {
    #[serde(rename = "AWS")]
    Aws,
    #[serde(rename = "AWS_PRO_SERVICE")]
    AwsProService,
    #[serde(rename = "GCP")]
    Gcp,
    #[serde(rename = "GCP_PRO_SERVICE")]
    GcpProService,
}

impl Default for ResellerType {
    fn default() -> ResellerType {
        Self::Aws
    }
}

