/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContractV2200ResponseDataBillingProviderConfigurationScheduleInner {
    #[serde(rename = "billing_provider_configuration", deserialize_with = "Option::deserialize")]
    pub billing_provider_configuration: Option<Box<models::GetContractV2200ResponseDataBillingProviderConfigurationScheduleInnerBillingProviderConfiguration>>,
    /// The date this billing provider configuration became or becomes active.
    #[serde(rename = "effective_at")]
    pub effective_at: chrono::DateTime<chrono::FixedOffset>,
    /// The date this billing provider configuration is superseded by the next entry. Null for the last entry in the schedule.
    #[serde(rename = "effective_until", skip_serializing_if = "Option::is_none")]
    pub effective_until: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl GetContractV2200ResponseDataBillingProviderConfigurationScheduleInner {
    pub fn new(billing_provider_configuration: Option<models::GetContractV2200ResponseDataBillingProviderConfigurationScheduleInnerBillingProviderConfiguration>, effective_at: chrono::DateTime<chrono::FixedOffset>) -> GetContractV2200ResponseDataBillingProviderConfigurationScheduleInner {
        GetContractV2200ResponseDataBillingProviderConfigurationScheduleInner {
            billing_provider_configuration: if let Some(x) = billing_provider_configuration {Some(Box::new(x))} else {None},
            effective_at,
            effective_until: None,
        }
    }
}

