/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetNetBalanceV1Request {
    /// The ID of the customer.
    #[serde(rename = "customer_id")]
    pub customer_id: uuid::Uuid,
    /// The ID of the credit type (can be fiat or a custom pricing unit) to get the balance for. Defaults to USD (cents) if not specified.
    #[serde(rename = "credit_type_id", skip_serializing_if = "Option::is_none")]
    pub credit_type_id: Option<uuid::Uuid>,
    /// Balance filters are OR'd together, so if a given commit or credit matches any of the filters, it will be included in the net balance.
    #[serde(rename = "filters", skip_serializing_if = "Option::is_none")]
    pub filters: Option<Vec<models::BalanceFilter>>,
    /// Controls which invoices are considered when calculating the remaining balance. `FINALIZED` considers only deductions from finalized invoices. `FINALIZED_AND_DRAFT` also includes deductions from pending draft invoices.
    #[serde(rename = "invoice_inclusion_mode", skip_serializing_if = "Option::is_none")]
    pub invoice_inclusion_mode: Option<InvoiceInclusionMode>,
}

impl GetNetBalanceV1Request {
    pub fn new(customer_id: uuid::Uuid) -> GetNetBalanceV1Request {
        GetNetBalanceV1Request {
            customer_id,
            credit_type_id: None,
            filters: None,
            invoice_inclusion_mode: None,
        }
    }
}
/// Controls which invoices are considered when calculating the remaining balance. `FINALIZED` considers only deductions from finalized invoices. `FINALIZED_AND_DRAFT` also includes deductions from pending draft invoices.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InvoiceInclusionMode {
    #[serde(rename = "FINALIZED")]
    Finalized,
    #[serde(rename = "FINALIZED_AND_DRAFT")]
    FinalizedAndDraft,
}

impl Default for InvoiceInclusionMode {
    fn default() -> InvoiceInclusionMode {
        Self::Finalized
    }
}

