/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPackageV1200ResponseDataSubscriptionsInner {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// Custom fields to be added eg. { \"key1\": \"value1\", \"key2\": \"value2\" }
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "subscription_rate")]
    pub subscription_rate: Box<models::GetContractV1200ResponseDataSubscriptionsInnerSubscriptionRate>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "collection_schedule")]
    pub collection_schedule: CollectionSchedule,
    #[serde(rename = "proration")]
    pub proration: Box<models::GetContractV1200ResponseDataSubscriptionsInnerProration>,
    #[serde(rename = "initial_quantity", skip_serializing_if = "Option::is_none")]
    pub initial_quantity: Option<f64>,
    /// Determines how the subscription's quantity is controlled. Defaults to QUANTITY_ONLY. **QUANTITY_ONLY**: The subscription quantity is specified directly on the subscription. `initial_quantity` must be provided with this option. Compatible with recurring commits/credits that use POOLED allocation. **SEAT_BASED**: Use when you want to pass specific seat identifiers (e.g. add user_123) to increment and decrement a subscription quantity, rather than directly providing the quantity. You must use a SEAT_BASED subscription to use a linked recurring credit with an allocation per seat. `seat_config` must be provided with this option.
    #[serde(rename = "quantity_management_mode", skip_serializing_if = "Option::is_none")]
    pub quantity_management_mode: Option<QuantityManagementMode>,
    #[serde(rename = "seat_config", skip_serializing_if = "Option::is_none")]
    pub seat_config: Option<Box<models::GetContractV1200ResponseDataSubscriptionsInnerSeatConfig>>,
    #[serde(rename = "starting_at_offset", skip_serializing_if = "Option::is_none")]
    pub starting_at_offset: Option<Box<models::GetContractV1200ResponseDataInitialPrepaidBalanceThresholdConfigurationCommitAllOfDuration>>,
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<Box<models::GetContractV1200ResponseDataInitialPrepaidBalanceThresholdConfigurationCommitAllOfDuration>>,
    #[serde(rename = "fiat_credit_type_id", skip_serializing_if = "Option::is_none")]
    pub fiat_credit_type_id: Option<uuid::Uuid>,
    #[serde(rename = "billing_cycle_config", skip_serializing_if = "Option::is_none")]
    pub billing_cycle_config: Option<Box<models::GetPackageV1200ResponseDataSubscriptionsInnerBillingCycleConfig>>,
    #[serde(rename = "payment_gate_config", skip_serializing_if = "Option::is_none")]
    pub payment_gate_config: Option<Box<models::GetContractV1200ResponseDataSubscriptionsInnerPaymentGateConfig>>,
}

impl GetPackageV1200ResponseDataSubscriptionsInner {
    pub fn new(subscription_rate: models::GetContractV1200ResponseDataSubscriptionsInnerSubscriptionRate, collection_schedule: CollectionSchedule, proration: models::GetContractV1200ResponseDataSubscriptionsInnerProration) -> GetPackageV1200ResponseDataSubscriptionsInner {
        GetPackageV1200ResponseDataSubscriptionsInner {
            id: None,
            custom_fields: None,
            subscription_rate: Box::new(subscription_rate),
            name: None,
            description: None,
            collection_schedule,
            proration: Box::new(proration),
            initial_quantity: None,
            quantity_management_mode: None,
            seat_config: None,
            starting_at_offset: None,
            duration: None,
            fiat_credit_type_id: None,
            billing_cycle_config: None,
            payment_gate_config: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CollectionSchedule {
    #[serde(rename = "ADVANCE")]
    Advance,
    #[serde(rename = "ARREARS")]
    Arrears,
    #[serde(rename = "advance")]
    Advance2,
    #[serde(rename = "arrears")]
    Arrears2,
}

impl Default for CollectionSchedule {
    fn default() -> CollectionSchedule {
        Self::Advance
    }
}
/// Determines how the subscription's quantity is controlled. Defaults to QUANTITY_ONLY. **QUANTITY_ONLY**: The subscription quantity is specified directly on the subscription. `initial_quantity` must be provided with this option. Compatible with recurring commits/credits that use POOLED allocation. **SEAT_BASED**: Use when you want to pass specific seat identifiers (e.g. add user_123) to increment and decrement a subscription quantity, rather than directly providing the quantity. You must use a SEAT_BASED subscription to use a linked recurring credit with an allocation per seat. `seat_config` must be provided with this option.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum QuantityManagementMode {
    #[serde(rename = "SEAT_BASED")]
    SeatBased,
    #[serde(rename = "seat_based")]
    SeatBased2,
    #[serde(rename = "QUANTITY_ONLY")]
    QuantityOnly,
    #[serde(rename = "quantity_only")]
    QuantityOnly2,
}

impl Default for QuantityManagementMode {
    fn default() -> QuantityManagementMode {
        Self::SeatBased
    }
}

