/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContractV1200ResponseDataInitialRecurringCommitsInnerAllOfProrationRoundingAccess {
    #[serde(rename = "rounding_method")]
    pub rounding_method: RoundingMethod,
    /// Number of decimal places to round to. Applied directly to the stored monetary representation. Negative values round to powers of 10 (e.g., -2 rounds to nearest 100 in the stored unit. For USD, this means rounding to the nearest dollar).
    #[serde(rename = "decimal_places")]
    pub decimal_places: f64,
}

impl GetContractV1200ResponseDataInitialRecurringCommitsInnerAllOfProrationRoundingAccess {
    pub fn new(rounding_method: RoundingMethod, decimal_places: f64) -> GetContractV1200ResponseDataInitialRecurringCommitsInnerAllOfProrationRoundingAccess {
        GetContractV1200ResponseDataInitialRecurringCommitsInnerAllOfProrationRoundingAccess {
            rounding_method,
            decimal_places,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RoundingMethod {
    #[serde(rename = "HALF_UP")]
    HalfUp,
    #[serde(rename = "FLOOR")]
    Floor,
    #[serde(rename = "CEILING")]
    Ceiling,
    #[serde(rename = "half_up")]
    HalfUp2,
    #[serde(rename = "floor")]
    Floor2,
    #[serde(rename = "ceiling")]
    Ceiling2,
}

impl Default for RoundingMethod {
    fn default() -> RoundingMethod {
        Self::HalfUp
    }
}

