/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetContractV1200ResponseDataInitialRecurringCommitsInnerAllOfAccessAmount : The amount of commit to grant.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContractV1200ResponseDataInitialRecurringCommitsInnerAllOfAccessAmount {
    #[serde(rename = "unit_price")]
    pub unit_price: f64,
    #[serde(rename = "quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<f64>,
    #[serde(rename = "credit_type_id")]
    pub credit_type_id: uuid::Uuid,
}

impl GetContractV1200ResponseDataInitialRecurringCommitsInnerAllOfAccessAmount {
    /// The amount of commit to grant.
    pub fn new(unit_price: f64, credit_type_id: uuid::Uuid) -> GetContractV1200ResponseDataInitialRecurringCommitsInnerAllOfAccessAmount {
        GetContractV1200ResponseDataInitialRecurringCommitsInnerAllOfAccessAmount {
            unit_price,
            quantity: None,
            credit_type_id,
        }
    }
}

