/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProductV1200ResponseDataUpdatesInner {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "starting_at", skip_serializing_if = "Option::is_none")]
    pub starting_at: Option<String>,
    #[serde(rename = "is_refundable", skip_serializing_if = "Option::is_none")]
    pub is_refundable: Option<bool>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "created_by")]
    pub created_by: String,
    #[serde(rename = "billable_metric_id", skip_serializing_if = "Option::is_none")]
    pub billable_metric_id: Option<uuid::Uuid>,
    #[serde(rename = "quantity_conversion", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub quantity_conversion: Option<Option<Box<models::GetProductV1200ResponseDataInitialQuantityConversion>>>,
    #[serde(rename = "quantity_rounding", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub quantity_rounding: Option<Option<Box<models::GetProductV1200ResponseDataInitialQuantityRounding>>>,
    /// This field's availability is dependent on your client's configuration.
    #[serde(rename = "netsuite_internal_item_id", skip_serializing_if = "Option::is_none")]
    pub netsuite_internal_item_id: Option<String>,
    /// This field's availability is dependent on your client's configuration.
    #[serde(rename = "netsuite_overage_item_id", skip_serializing_if = "Option::is_none")]
    pub netsuite_overage_item_id: Option<String>,
    #[serde(rename = "composite_product_ids", skip_serializing_if = "Option::is_none")]
    pub composite_product_ids: Option<Vec<uuid::Uuid>>,
    #[serde(rename = "composite_tags", skip_serializing_if = "Option::is_none")]
    pub composite_tags: Option<Vec<String>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "exclude_free_usage", skip_serializing_if = "Option::is_none")]
    pub exclude_free_usage: Option<bool>,
    /// Only for composite products. If true, allows a composite to incorporate spend from other composite products. Defaults to false
    #[serde(rename = "include_composite_spend", skip_serializing_if = "Option::is_none")]
    pub include_composite_spend: Option<bool>,
    /// For USAGE products only. If set, pricing for this product will be determined for each pricing_group_key value, as opposed to the product as a whole. The superset of values in the pricing group key and presentation group key must be set as one compound group key on the billable metric.
    #[serde(rename = "pricing_group_key", skip_serializing_if = "Option::is_none")]
    pub pricing_group_key: Option<Vec<String>>,
    /// For USAGE products only. Groups usage line items on invoices. The superset of values in the pricing group key and presentation group key must be set as one compound group key on the billable metric.
    #[serde(rename = "presentation_group_key", skip_serializing_if = "Option::is_none")]
    pub presentation_group_key: Option<Vec<String>>,
}

impl GetProductV1200ResponseDataUpdatesInner {
    pub fn new(created_at: String, created_by: String) -> GetProductV1200ResponseDataUpdatesInner {
        GetProductV1200ResponseDataUpdatesInner {
            name: None,
            starting_at: None,
            is_refundable: None,
            created_at,
            created_by,
            billable_metric_id: None,
            quantity_conversion: None,
            quantity_rounding: None,
            netsuite_internal_item_id: None,
            netsuite_overage_item_id: None,
            composite_product_ids: None,
            composite_tags: None,
            tags: None,
            exclude_free_usage: None,
            include_composite_spend: None,
            pricing_group_key: None,
            presentation_group_key: None,
        }
    }
}

