/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContractV2200ResponseData {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "customer_id")]
    pub customer_id: uuid::Uuid,
    /// (BETA) ID of the package this contract was created from, if applicable.
    #[serde(rename = "package_id", skip_serializing_if = "Option::is_none")]
    pub package_id: Option<uuid::Uuid>,
    /// Optional uniqueness key to prevent duplicate contract creations.
    #[serde(rename = "uniqueness_key", skip_serializing_if = "Option::is_none")]
    pub uniqueness_key: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// This field's availability is dependent on your client's configuration.
    #[serde(rename = "salesforce_opportunity_id", skip_serializing_if = "Option::is_none")]
    pub salesforce_opportunity_id: Option<String>,
    #[serde(rename = "rate_card_id", skip_serializing_if = "Option::is_none")]
    pub rate_card_id: Option<uuid::Uuid>,
    #[serde(rename = "starting_at")]
    pub starting_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "commits")]
    pub commits: Vec<models::GetContractV2200ResponseDataCommitsInner>,
    #[serde(rename = "credits", skip_serializing_if = "Option::is_none")]
    pub credits: Option<Vec<models::GetContractV2200ResponseDataCreditsInner>>,
    #[serde(rename = "has_more", skip_serializing_if = "Option::is_none")]
    pub has_more: Option<Box<models::CreateContractV1200ResponseDataContractHasMore>>,
    #[serde(rename = "overrides")]
    pub overrides: Vec<models::GetContractV2200ResponseDataOverridesInner>,
    /// This field's availability is dependent on your client's configuration.
    #[serde(rename = "discounts", skip_serializing_if = "Option::is_none")]
    pub discounts: Option<Vec<models::GetContractV1200ResponseDataInitialDiscountsInner>>,
    /// This field's availability is dependent on your client's configuration.
    #[serde(rename = "professional_services", skip_serializing_if = "Option::is_none")]
    pub professional_services: Option<Vec<models::GetContractV1200ResponseDataInitialProfessionalServicesInner>>,
    #[serde(rename = "scheduled_charges")]
    pub scheduled_charges: Vec<models::GetContractV1200ResponseDataInitialScheduledChargesInner>,
    /// Determines which scheduled and commit charges to consolidate onto the Contract's usage invoice. The charge's `timestamp` must match the usage invoice's `ending_before` date for consolidation to occur. This field cannot be modified after a Contract has been created. If this field is omitted, charges will appear on a separate invoice from usage charges.
    #[serde(rename = "scheduled_charges_on_usage_invoices", skip_serializing_if = "Option::is_none")]
    pub scheduled_charges_on_usage_invoices: Option<ScheduledChargesOnUsageInvoices>,
    #[serde(rename = "transitions")]
    pub transitions: Vec<models::GetContractV1200ResponseDataInitialTransitionsInner>,
    /// This field's availability is dependent on your client's configuration.
    #[serde(rename = "reseller_royalties", skip_serializing_if = "Option::is_none")]
    pub reseller_royalties: Option<Vec<models::GetContractV2200ResponseDataResellerRoyaltiesInner>>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "created_by")]
    pub created_by: String,
    /// This field's availability is dependent on your client's configuration.
    #[serde(rename = "netsuite_sales_order_id", skip_serializing_if = "Option::is_none")]
    pub netsuite_sales_order_id: Option<String>,
    #[serde(rename = "net_payment_terms_days", skip_serializing_if = "Option::is_none")]
    pub net_payment_terms_days: Option<f64>,
    #[serde(rename = "ending_before", skip_serializing_if = "Option::is_none")]
    pub ending_before: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "archived_at", skip_serializing_if = "Option::is_none")]
    pub archived_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "total_contract_value", skip_serializing_if = "Option::is_none")]
    pub total_contract_value: Option<f64>,
    #[serde(rename = "usage_filter")]
    pub usage_filter: Vec<models::CreateContractV1200ResponseDataContractUsageFilterInner>,
    #[serde(rename = "usage_statement_schedule")]
    pub usage_statement_schedule: Box<models::GetContractV1200ResponseDataInitialUsageStatementSchedule>,
    /// Defaults to LOWEST_MULTIPLIER, which applies the greatest discount to list prices automatically. EXPLICIT prioritization requires specifying priorities for each multiplier; the one with the lowest priority value will be prioritized first.
    #[serde(rename = "multiplier_override_prioritization", skip_serializing_if = "Option::is_none")]
    pub multiplier_override_prioritization: Option<MultiplierOverridePrioritization>,
    /// Custom fields to be added eg. { \"key1\": \"value1\", \"key2\": \"value2\" }
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "customer_billing_provider_configuration", skip_serializing_if = "Option::is_none")]
    pub customer_billing_provider_configuration: Option<Box<models::GetCustomerBillingProviderConfigurationsV1200ResponseDataInner>>,
    /// The schedule of billing provider configuration changes on the contract, ordered by effective_at ascending.
    #[serde(rename = "billing_provider_configuration_schedule", skip_serializing_if = "Option::is_none")]
    pub billing_provider_configuration_schedule: Option<Vec<models::GetContractV2200ResponseDataBillingProviderConfigurationScheduleInner>>,
    /// The schedule of revenue system configuration changes on the contract, ordered by effective_at ascending.
    #[serde(rename = "revenue_system_configuration_schedule", skip_serializing_if = "Option::is_none")]
    pub revenue_system_configuration_schedule: Option<Vec<models::GetContractV2200ResponseDataRevenueSystemConfigurationScheduleInner>>,
    #[serde(rename = "recurring_commits", skip_serializing_if = "Option::is_none")]
    pub recurring_commits: Option<Vec<models::GetContractV2200ResponseDataRecurringCommitsInner>>,
    #[serde(rename = "recurring_credits", skip_serializing_if = "Option::is_none")]
    pub recurring_credits: Option<Vec<models::GetContractV2200ResponseDataRecurringCreditsInner>>,
    #[serde(rename = "spend_threshold_configuration", skip_serializing_if = "Option::is_none")]
    pub spend_threshold_configuration: Option<Box<models::GetContractV1200ResponseDataInitialSpendThresholdConfiguration>>,
    #[serde(rename = "prepaid_balance_threshold_configuration", skip_serializing_if = "Option::is_none")]
    pub prepaid_balance_threshold_configuration: Option<Box<models::GetContractV2200ResponseDataPrepaidBalanceThresholdConfiguration>>,
    /// Spend trackers attached to this contract.
    #[serde(rename = "spend_trackers", skip_serializing_if = "Option::is_none")]
    pub spend_trackers: Option<Vec<models::GetContractV1200ResponseDataInitialSpendTrackersInner>>,
    /// List of subscriptions on the contract.
    #[serde(rename = "subscriptions", skip_serializing_if = "Option::is_none")]
    pub subscriptions: Option<Vec<models::GetContractV1200ResponseDataSubscriptionsInner>>,
    #[serde(rename = "hierarchy_configuration", skip_serializing_if = "Option::is_none")]
    pub hierarchy_configuration: Option<Box<models::GetContractV1200ResponseDataInitialHierarchyConfiguration>>,
    /// Priority of the contract.
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<f64>,
}

impl GetContractV2200ResponseData {
    pub fn new(id: uuid::Uuid, customer_id: uuid::Uuid, starting_at: chrono::DateTime<chrono::FixedOffset>, commits: Vec<models::GetContractV2200ResponseDataCommitsInner>, overrides: Vec<models::GetContractV2200ResponseDataOverridesInner>, scheduled_charges: Vec<models::GetContractV1200ResponseDataInitialScheduledChargesInner>, transitions: Vec<models::GetContractV1200ResponseDataInitialTransitionsInner>, created_at: chrono::DateTime<chrono::FixedOffset>, created_by: String, usage_filter: Vec<models::CreateContractV1200ResponseDataContractUsageFilterInner>, usage_statement_schedule: models::GetContractV1200ResponseDataInitialUsageStatementSchedule) -> GetContractV2200ResponseData {
        GetContractV2200ResponseData {
            id,
            customer_id,
            package_id: None,
            uniqueness_key: None,
            name: None,
            salesforce_opportunity_id: None,
            rate_card_id: None,
            starting_at,
            commits,
            credits: None,
            has_more: None,
            overrides,
            discounts: None,
            professional_services: None,
            scheduled_charges,
            scheduled_charges_on_usage_invoices: None,
            transitions,
            reseller_royalties: None,
            created_at,
            created_by,
            netsuite_sales_order_id: None,
            net_payment_terms_days: None,
            ending_before: None,
            archived_at: None,
            total_contract_value: None,
            usage_filter,
            usage_statement_schedule: Box::new(usage_statement_schedule),
            multiplier_override_prioritization: None,
            custom_fields: None,
            customer_billing_provider_configuration: None,
            billing_provider_configuration_schedule: None,
            revenue_system_configuration_schedule: None,
            recurring_commits: None,
            recurring_credits: None,
            spend_threshold_configuration: None,
            prepaid_balance_threshold_configuration: None,
            spend_trackers: None,
            subscriptions: None,
            hierarchy_configuration: None,
            priority: None,
        }
    }
}
/// Determines which scheduled and commit charges to consolidate onto the Contract's usage invoice. The charge's `timestamp` must match the usage invoice's `ending_before` date for consolidation to occur. This field cannot be modified after a Contract has been created. If this field is omitted, charges will appear on a separate invoice from usage charges.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ScheduledChargesOnUsageInvoices {
    #[serde(rename = "ALL")]
    All,
}

impl Default for ScheduledChargesOnUsageInvoices {
    fn default() -> ScheduledChargesOnUsageInvoices {
        Self::All
    }
}
/// Defaults to LOWEST_MULTIPLIER, which applies the greatest discount to list prices automatically. EXPLICIT prioritization requires specifying priorities for each multiplier; the one with the lowest priority value will be prioritized first.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MultiplierOverridePrioritization {
    #[serde(rename = "LOWEST_MULTIPLIER")]
    LowestMultiplier,
    #[serde(rename = "lowest_multiplier")]
    LowestMultiplier2,
    #[serde(rename = "EXPLICIT")]
    Explicit,
    #[serde(rename = "explicit")]
    Explicit2,
}

impl Default for MultiplierOverridePrioritization {
    fn default() -> MultiplierOverridePrioritization {
        Self::LowestMultiplier
    }
}

