/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContractV1200ResponseDataInitialCommitsInnerLedgerInnerOneOf5 {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "amount")]
    pub amount: f64,
    #[serde(rename = "segment_id")]
    pub segment_id: uuid::Uuid,
    #[serde(rename = "invoice_id")]
    pub invoice_id: uuid::Uuid,
    #[serde(rename = "contract_id", skip_serializing_if = "Option::is_none")]
    pub contract_id: Option<uuid::Uuid>,
}

impl GetContractV1200ResponseDataInitialCommitsInnerLedgerInnerOneOf5 {
    pub fn new(r#type: Type, timestamp: String, amount: f64, segment_id: uuid::Uuid, invoice_id: uuid::Uuid) -> GetContractV1200ResponseDataInitialCommitsInnerLedgerInnerOneOf5 {
        GetContractV1200ResponseDataInitialCommitsInnerLedgerInnerOneOf5 {
            r#type,
            timestamp,
            amount,
            segment_id,
            invoice_id,
            contract_id: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "PREPAID_COMMIT_CREDITED")]
    PrepaidCommitCredited,
}

impl Default for Type {
    fn default() -> Type {
        Self::PrepaidCommitCredited
    }
}

