/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContractV1200ResponseDataInitialSpendTrackersInner {
    /// Human-readable identifier, unique per contract.
    #[serde(rename = "alias")]
    pub alias: String,
    #[serde(rename = "credit_type_id")]
    pub credit_type_id: uuid::Uuid,
    #[serde(rename = "reset_frequency")]
    pub reset_frequency: ResetFrequency,
    #[serde(rename = "applicable_spend_specifiers")]
    pub applicable_spend_specifiers: Vec<models::GetContractV1200ResponseDataInitialSpendTrackersInnerApplicableSpendSpecifiersInner>,
    #[serde(rename = "accumulated_spend", skip_serializing_if = "Option::is_none")]
    pub accumulated_spend: Option<Box<models::GetContractV1200ResponseDataInitialSpendTrackersInnerAccumulatedSpend>>,
}

impl GetContractV1200ResponseDataInitialSpendTrackersInner {
    pub fn new(alias: String, credit_type_id: uuid::Uuid, reset_frequency: ResetFrequency, applicable_spend_specifiers: Vec<models::GetContractV1200ResponseDataInitialSpendTrackersInnerApplicableSpendSpecifiersInner>) -> GetContractV1200ResponseDataInitialSpendTrackersInner {
        GetContractV1200ResponseDataInitialSpendTrackersInner {
            alias,
            credit_type_id,
            reset_frequency,
            applicable_spend_specifiers,
            accumulated_spend: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ResetFrequency {
    #[serde(rename = "BILLING_PERIOD")]
    BillingPeriod,
}

impl Default for ResetFrequency {
    fn default() -> ResetFrequency {
        Self::BillingPeriod
    }
}

