/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPagedUsageV1Request {
    #[serde(rename = "customer_id")]
    pub customer_id: uuid::Uuid,
    #[serde(rename = "billable_metric_id")]
    pub billable_metric_id: uuid::Uuid,
    /// A window_size of \"day\" or \"hour\" will return the usage for the specified period segmented into daily or hourly aggregates. A window_size of \"none\" will return a single usage aggregate for the entirety of the specified period.
    #[serde(rename = "window_size")]
    pub window_size: WindowSize,
    /// Must be aligned to UTC midnight, e.g. `2024-01-01T00:00:00Z`.
    #[serde(rename = "starting_on", skip_serializing_if = "Option::is_none")]
    pub starting_on: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Must be aligned to UTC midnight and at least one day after `starting_on`.
    #[serde(rename = "ending_before", skip_serializing_if = "Option::is_none")]
    pub ending_before: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "group_by", skip_serializing_if = "Option::is_none")]
    pub group_by: Option<Box<models::GetPagedUsageV1RequestGroupBy>>,
    /// Group key to group usage by. Supports both simple (single key) and compound (multiple keys) group keys.  For simple group keys, provide a single key e.g. `[\"region\"]`. For compound group keys, provide multiple keys e.g. `[\"region\", \"team\"]`.  For streaming metrics, the keys must be defined as a simple or compound group key on the billable metric. For compound group keys, all keys must match an exact compound group key definition — partial matches are not allowed.  Cannot be used together with `group_by`. 
    #[serde(rename = "group_key", skip_serializing_if = "Option::is_none")]
    pub group_key: Option<Vec<String>>,
    /// Object mapping group keys to arrays of values to filter on. Only usage matching these filter values will be returned. Keys must be present in group_key. Omit a key or use an empty array to include all values for that dimension. 
    #[serde(rename = "group_filters", skip_serializing_if = "Option::is_none")]
    pub group_filters: Option<std::collections::HashMap<String, Vec<String>>>,
}

impl GetPagedUsageV1Request {
    pub fn new(customer_id: uuid::Uuid, billable_metric_id: uuid::Uuid, window_size: WindowSize) -> GetPagedUsageV1Request {
        GetPagedUsageV1Request {
            customer_id,
            billable_metric_id,
            window_size,
            starting_on: None,
            ending_before: None,
            group_by: None,
            group_key: None,
            group_filters: None,
        }
    }
}
/// A window_size of \"day\" or \"hour\" will return the usage for the specified period segmented into daily or hourly aggregates. A window_size of \"none\" will return a single usage aggregate for the entirety of the specified period.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WindowSize {
    #[serde(rename = "hour")]
    Hour,
    #[serde(rename = "day")]
    Day,
    #[serde(rename = "none")]
    None,
    #[serde(rename = "HOUR")]
    Hour2,
    #[serde(rename = "DAY")]
    Day2,
    #[serde(rename = "NONE")]
    None2,
    #[serde(rename = "Hour")]
    Hour3,
    #[serde(rename = "Day")]
    Day3,
    #[serde(rename = "None")]
    None3,
}

impl Default for WindowSize {
    fn default() -> WindowSize {
        Self::Hour
    }
}

