/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContractRateSchedulePayload {
    /// ID of the customer for whose contract to get the rate schedule for.
    #[serde(rename = "customer_id")]
    pub customer_id: uuid::Uuid,
    /// ID of the contract to get the rate schedule for.
    #[serde(rename = "contract_id")]
    pub contract_id: uuid::Uuid,
    /// optional timestamp which overlaps with the returned rate schedule segments. When not specified, the current timestamp will be used.
    #[serde(rename = "at", skip_serializing_if = "Option::is_none")]
    pub at: Option<String>,
    /// List of rate selectors, rates matching ANY of the selectors will be included in the response. Passing no selectors will result in all rates being returned.
    #[serde(rename = "selectors", skip_serializing_if = "Option::is_none")]
    pub selectors: Option<Vec<models::RateSelectorWithProductTags>>,
}

impl GetContractRateSchedulePayload {
    pub fn new(customer_id: uuid::Uuid, contract_id: uuid::Uuid) -> GetContractRateSchedulePayload {
        GetContractRateSchedulePayload {
            customer_id,
            contract_id,
            at: None,
            selectors: None,
        }
    }
}

