/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetContractV2200ResponseDataSpendThresholdConfigurationPaymentGateConfigStripeConfig : Only applicable if using STRIPE as your payment gateway type.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContractV2200ResponseDataSpendThresholdConfigurationPaymentGateConfigStripeConfig {
    /// If left blank, will default to INVOICE
    #[serde(rename = "payment_type")]
    pub payment_type: PaymentType,
    /// Metadata to be added to the Stripe invoice. Only applicable if using INVOICE as your payment type.
    #[serde(rename = "invoice_metadata", skip_serializing_if = "Option::is_none")]
    pub invoice_metadata: Option<std::collections::HashMap<String, String>>,
}

impl GetContractV2200ResponseDataSpendThresholdConfigurationPaymentGateConfigStripeConfig {
    /// Only applicable if using STRIPE as your payment gateway type.
    pub fn new(payment_type: PaymentType) -> GetContractV2200ResponseDataSpendThresholdConfigurationPaymentGateConfigStripeConfig {
        GetContractV2200ResponseDataSpendThresholdConfigurationPaymentGateConfigStripeConfig {
            payment_type,
            invoice_metadata: None,
        }
    }
}
/// If left blank, will default to INVOICE
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaymentType {
    #[serde(rename = "INVOICE")]
    Invoice,
    #[serde(rename = "PAYMENT_INTENT")]
    PaymentIntent,
}

impl Default for PaymentType {
    fn default() -> PaymentType {
        Self::Invoice
    }
}

