/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContractEditHistoryV2200ResponseDataInnerUpdateDiscountsInner {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "netsuite_sales_order_id", skip_serializing_if = "Option::is_none")]
    pub netsuite_sales_order_id: Option<String>,
    #[serde(rename = "schedule", skip_serializing_if = "Option::is_none")]
    pub schedule: Option<Box<models::GetContractEditHistoryV2200ResponseDataInnerUpdateDiscountsInnerSchedule>>,
    /// Custom fields to be added eg. { \"key1\": \"value1\", \"key2\": \"value2\" }
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<std::collections::HashMap<String, String>>,
}

impl GetContractEditHistoryV2200ResponseDataInnerUpdateDiscountsInner {
    pub fn new(id: uuid::Uuid) -> GetContractEditHistoryV2200ResponseDataInnerUpdateDiscountsInner {
        GetContractEditHistoryV2200ResponseDataInnerUpdateDiscountsInner {
            id,
            name: None,
            netsuite_sales_order_id: None,
            schedule: None,
            custom_fields: None,
        }
    }
}

