/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContractEditHistoryV2200ResponseDataInnerUpdateRecurringCommitsInner {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "ending_before", skip_serializing_if = "Option::is_none")]
    pub ending_before: Option<String>,
    #[serde(rename = "access_amount", skip_serializing_if = "Option::is_none")]
    pub access_amount: Option<Box<models::GetContractEditHistoryV2200ResponseDataInnerUpdateRecurringCommitsInnerAllOfAccessAmount>>,
    #[serde(rename = "rate_type", skip_serializing_if = "Option::is_none")]
    pub rate_type: Option<RateType>,
    #[serde(rename = "invoice_amount", skip_serializing_if = "Option::is_none")]
    pub invoice_amount: Option<Box<models::GetContractEditHistoryV2200ResponseDataInnerUpdateRecurringCommitsInnerAllOfAccessAmount>>,
    #[serde(rename = "proration_rounding", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub proration_rounding: Option<Option<Box<models::GetContractV2200ResponseDataRecurringCommitsInnerAllOfProrationRounding>>>,
}

impl GetContractEditHistoryV2200ResponseDataInnerUpdateRecurringCommitsInner {
    pub fn new(id: uuid::Uuid) -> GetContractEditHistoryV2200ResponseDataInnerUpdateRecurringCommitsInner {
        GetContractEditHistoryV2200ResponseDataInnerUpdateRecurringCommitsInner {
            id,
            ending_before: None,
            access_amount: None,
            rate_type: None,
            invoice_amount: None,
            proration_rounding: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RateType {
    #[serde(rename = "LIST_RATE")]
    ListRate,
    #[serde(rename = "list_rate")]
    ListRate2,
    #[serde(rename = "COMMIT_RATE")]
    CommitRate,
    #[serde(rename = "commit_rate")]
    CommitRate2,
}

impl Default for RateType {
    fn default() -> RateType {
        Self::ListRate
    }
}

