/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContractEditHistoryV2200ResponseDataInner {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Prevents the creation of duplicates. If a request to create a record is made with a previously used uniqueness key, a new record will not be created and the request will fail with a 409 error.
    #[serde(rename = "uniqueness_key", skip_serializing_if = "Option::is_none")]
    pub uniqueness_key: Option<String>,
    #[serde(rename = "add_overrides", skip_serializing_if = "Option::is_none")]
    pub add_overrides: Option<Vec<models::GetContractV2200ResponseDataOverridesInner>>,
    #[serde(rename = "add_pro_services", skip_serializing_if = "Option::is_none")]
    pub add_pro_services: Option<Vec<models::GetContractV1200ResponseDataInitialProfessionalServicesInner>>,
    #[serde(rename = "add_reseller_royalties", skip_serializing_if = "Option::is_none")]
    pub add_reseller_royalties: Option<Vec<models::GetContractEditHistoryV2200ResponseDataInnerAddResellerRoyaltiesInner>>,
    #[serde(rename = "add_discounts", skip_serializing_if = "Option::is_none")]
    pub add_discounts: Option<Vec<models::GetContractV1200ResponseDataInitialDiscountsInner>>,
    #[serde(rename = "add_scheduled_charges", skip_serializing_if = "Option::is_none")]
    pub add_scheduled_charges: Option<Vec<models::GetContractEditHistoryV2200ResponseDataInnerAddScheduledChargesInner>>,
    #[serde(rename = "add_commits", skip_serializing_if = "Option::is_none")]
    pub add_commits: Option<Vec<models::GetContractEditHistoryV2200ResponseDataInnerAddCommitsInner>>,
    #[serde(rename = "add_credits", skip_serializing_if = "Option::is_none")]
    pub add_credits: Option<Vec<models::GetContractEditHistoryV2200ResponseDataInnerAddCreditsInner>>,
    #[serde(rename = "add_recurring_commits", skip_serializing_if = "Option::is_none")]
    pub add_recurring_commits: Option<Vec<models::GetContractV2200ResponseDataRecurringCommitsInner>>,
    #[serde(rename = "add_recurring_credits", skip_serializing_if = "Option::is_none")]
    pub add_recurring_credits: Option<Vec<models::GetContractV2200ResponseDataRecurringCreditsInner>>,
    #[serde(rename = "add_usage_filters", skip_serializing_if = "Option::is_none")]
    pub add_usage_filters: Option<Vec<models::CreateContractV1200ResponseDataContractUsageFilterInner>>,
    /// List of subscriptions on the contract.
    #[serde(rename = "add_subscriptions", skip_serializing_if = "Option::is_none")]
    pub add_subscriptions: Option<Vec<models::GetContractV1200ResponseDataSubscriptionsInner>>,
    #[serde(rename = "add_prepaid_balance_threshold_configuration", skip_serializing_if = "Option::is_none")]
    pub add_prepaid_balance_threshold_configuration: Option<Box<models::GetContractV2200ResponseDataPrepaidBalanceThresholdConfiguration>>,
    #[serde(rename = "add_spend_threshold_configuration", skip_serializing_if = "Option::is_none")]
    pub add_spend_threshold_configuration: Option<Box<models::GetContractV1200ResponseDataInitialSpendThresholdConfiguration>>,
    /// Value to update the contract name to. If not provided, the contract name will remain unchanged.
    #[serde(rename = "update_contract_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub update_contract_name: Option<Option<String>>,
    #[serde(rename = "update_discounts", skip_serializing_if = "Option::is_none")]
    pub update_discounts: Option<Vec<models::GetContractEditHistoryV2200ResponseDataInnerUpdateDiscountsInner>>,
    #[serde(rename = "update_scheduled_charges", skip_serializing_if = "Option::is_none")]
    pub update_scheduled_charges: Option<Vec<models::GetContractEditHistoryV2200ResponseDataInnerUpdateScheduledChargesInner>>,
    #[serde(rename = "update_commits", skip_serializing_if = "Option::is_none")]
    pub update_commits: Option<Vec<models::GetContractEditHistoryV2200ResponseDataInnerUpdateCommitsInner>>,
    #[serde(rename = "update_credits", skip_serializing_if = "Option::is_none")]
    pub update_credits: Option<Vec<models::GetContractEditHistoryV2200ResponseDataInnerUpdateCreditsInner>>,
    #[serde(rename = "update_recurring_commits", skip_serializing_if = "Option::is_none")]
    pub update_recurring_commits: Option<Vec<models::GetContractEditHistoryV2200ResponseDataInnerUpdateRecurringCommitsInner>>,
    #[serde(rename = "update_recurring_credits", skip_serializing_if = "Option::is_none")]
    pub update_recurring_credits: Option<Vec<models::GetContractEditHistoryV2200ResponseDataInnerUpdateRecurringCreditsInner>>,
    #[serde(rename = "update_contract_end_date", skip_serializing_if = "Option::is_none")]
    pub update_contract_end_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "update_refund_invoices", skip_serializing_if = "Option::is_none")]
    pub update_refund_invoices: Option<Vec<models::GetContractEditHistoryV2200ResponseDataInnerUpdateRefundInvoicesInner>>,
    /// Optional list of subscriptions to update.
    #[serde(rename = "update_subscriptions", skip_serializing_if = "Option::is_none")]
    pub update_subscriptions: Option<Vec<models::GetContractEditHistoryV2200ResponseDataInnerUpdateSubscriptionsInner>>,
    #[serde(rename = "update_prepaid_balance_threshold_configuration", skip_serializing_if = "Option::is_none")]
    pub update_prepaid_balance_threshold_configuration: Option<Box<models::GetContractEditHistoryV2200ResponseDataInnerUpdatePrepaidBalanceThresholdConfiguration>>,
    #[serde(rename = "update_spend_threshold_configuration", skip_serializing_if = "Option::is_none")]
    pub update_spend_threshold_configuration: Option<Box<models::GetContractEditHistoryV2200ResponseDataInnerUpdateSpendThresholdConfiguration>>,
    #[serde(rename = "archive_commits", skip_serializing_if = "Option::is_none")]
    pub archive_commits: Option<Vec<models::ArchiveAlertV1200ResponseData>>,
    #[serde(rename = "archive_credits", skip_serializing_if = "Option::is_none")]
    pub archive_credits: Option<Vec<models::ArchiveAlertV1200ResponseData>>,
    #[serde(rename = "archive_scheduled_charges", skip_serializing_if = "Option::is_none")]
    pub archive_scheduled_charges: Option<Vec<models::ArchiveAlertV1200ResponseData>>,
    #[serde(rename = "remove_overrides", skip_serializing_if = "Option::is_none")]
    pub remove_overrides: Option<Vec<models::ArchiveAlertV1200ResponseData>>,
}

impl GetContractEditHistoryV2200ResponseDataInner {
    pub fn new(id: uuid::Uuid) -> GetContractEditHistoryV2200ResponseDataInner {
        GetContractEditHistoryV2200ResponseDataInner {
            id,
            timestamp: None,
            uniqueness_key: None,
            add_overrides: None,
            add_pro_services: None,
            add_reseller_royalties: None,
            add_discounts: None,
            add_scheduled_charges: None,
            add_commits: None,
            add_credits: None,
            add_recurring_commits: None,
            add_recurring_credits: None,
            add_usage_filters: None,
            add_subscriptions: None,
            add_prepaid_balance_threshold_configuration: None,
            add_spend_threshold_configuration: None,
            update_contract_name: None,
            update_discounts: None,
            update_scheduled_charges: None,
            update_commits: None,
            update_credits: None,
            update_recurring_commits: None,
            update_recurring_credits: None,
            update_contract_end_date: None,
            update_refund_invoices: None,
            update_subscriptions: None,
            update_prepaid_balance_threshold_configuration: None,
            update_spend_threshold_configuration: None,
            archive_commits: None,
            archive_credits: None,
            archive_scheduled_charges: None,
            remove_overrides: None,
        }
    }
}

