/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContractEditHistoryV2200ResponseDataInnerUpdateSubscriptionsInnerSeatUpdatesAddUnassignedSeatsInner {
    /// The number of unassigned seats on the subscription will increase/decrease by this delta. Must be greater than 0.
    #[serde(rename = "quantity")]
    pub quantity: f64,
    /// Unassigned seats will be updated starting at this date.
    #[serde(rename = "starting_at")]
    pub starting_at: String,
}

impl GetContractEditHistoryV2200ResponseDataInnerUpdateSubscriptionsInnerSeatUpdatesAddUnassignedSeatsInner {
    pub fn new(quantity: f64, starting_at: String) -> GetContractEditHistoryV2200ResponseDataInnerUpdateSubscriptionsInnerSeatUpdatesAddUnassignedSeatsInner {
        GetContractEditHistoryV2200ResponseDataInnerUpdateSubscriptionsInnerSeatUpdatesAddUnassignedSeatsInner {
            quantity,
            starting_at,
        }
    }
}

