/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetContractV1200ResponseDataInitialRecurringCommitsInnerAllOfInvoiceAmount : The amount the customer should be billed for the commit. Not required.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContractV1200ResponseDataInitialRecurringCommitsInnerAllOfInvoiceAmount {
    #[serde(rename = "unit_price")]
    pub unit_price: f64,
    #[serde(rename = "quantity")]
    pub quantity: f64,
    #[serde(rename = "credit_type_id")]
    pub credit_type_id: uuid::Uuid,
}

impl GetContractV1200ResponseDataInitialRecurringCommitsInnerAllOfInvoiceAmount {
    /// The amount the customer should be billed for the commit. Not required.
    pub fn new(unit_price: f64, quantity: f64, credit_type_id: uuid::Uuid) -> GetContractV1200ResponseDataInitialRecurringCommitsInnerAllOfInvoiceAmount {
        GetContractV1200ResponseDataInitialRecurringCommitsInnerAllOfInvoiceAmount {
            unit_price,
            quantity,
            credit_type_id,
        }
    }
}

