/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCustomerV1200ResponseDataCustomerConfig {
    /// The Salesforce account ID for the customer
    #[serde(rename = "salesforce_account_id", deserialize_with = "Option::deserialize")]
    pub salesforce_account_id: Option<String>,
}

impl GetCustomerV1200ResponseDataCustomerConfig {
    pub fn new(salesforce_account_id: Option<String>) -> GetCustomerV1200ResponseDataCustomerConfig {
        GetCustomerV1200ResponseDataCustomerConfig {
            salesforce_account_id,
        }
    }
}

