/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSubscriptionSeatsHistoryV1Request {
    #[serde(rename = "customer_id")]
    pub customer_id: uuid::Uuid,
    #[serde(rename = "contract_id")]
    pub contract_id: uuid::Uuid,
    #[serde(rename = "subscription_id")]
    pub subscription_id: uuid::Uuid,
    /// Maximum number of seat schedule entries to return. Defaults to 10. Required range: 1 <= x <= 10.
    #[serde(rename = "limit", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub limit: Option<Option<i32>>,
    /// Cursor for pagination. Use the value from the `next_page` field of the previous response to retrieve the next page of results.
    #[serde(rename = "cursor", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<Option<String>>,
    /// Get the seats history segment for the covering date. Cannot be used with `starting_at` or `ending_before`.
    #[serde(rename = "covering_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub covering_date: Option<Option<String>>,
    /// Include seats history segments that are active at or after this timestamp. Use with `ending_before` to get a specific time range. If not set, there's no lower bound.
    #[serde(rename = "starting_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub starting_at: Option<Option<String>>,
    /// Include seats history segments that are active at or before this timestamp. Use with `starting_at` to get a specific time range. If not set, there's no upper bound.
    #[serde(rename = "ending_before", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ending_before: Option<Option<String>>,
}

impl GetSubscriptionSeatsHistoryV1Request {
    pub fn new(customer_id: uuid::Uuid, contract_id: uuid::Uuid, subscription_id: uuid::Uuid) -> GetSubscriptionSeatsHistoryV1Request {
        GetSubscriptionSeatsHistoryV1Request {
            customer_id,
            contract_id,
            subscription_id,
            limit: None,
            cursor: None,
            covering_date: None,
            starting_at: None,
            ending_before: None,
        }
    }
}

