/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContractRateScheduleV1200Response {
    #[serde(rename = "next_page", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub next_page: Option<Option<String>>,
    #[serde(rename = "data")]
    pub data: Vec<models::GetContractRateScheduleV1200ResponseDataInner>,
}

impl GetContractRateScheduleV1200Response {
    pub fn new(data: Vec<models::GetContractRateScheduleV1200ResponseDataInner>) -> GetContractRateScheduleV1200Response {
        GetContractRateScheduleV1200Response {
            next_page: None,
            data,
        }
    }
}

