/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetServicesV1200Response {
    #[serde(rename = "services")]
    pub services: Vec<models::GetServicesV1200ResponseServicesInner>,
}

impl GetServicesV1200Response {
    pub fn new(services: Vec<models::GetServicesV1200ResponseServicesInner>) -> GetServicesV1200Response {
        GetServicesV1200Response {
            services,
        }
    }
}

