/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContractEditHistoryV2200ResponseDataInnerUpdatePrepaidBalanceThresholdConfigurationCommit {
    /// The commit product that will be used to generate the line item for commit payment.
    #[serde(rename = "product_id", skip_serializing_if = "Option::is_none")]
    pub product_id: Option<String>,
    /// Specify the name of the line item for the threshold charge. If left blank, it will default to the commit product name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The priority of the commit, used to determine drawdown order. Lower priority commits are consumed first. Defaults to 100 if not specified. On updates, set to null to clear a previously configured priority.
    #[serde(rename = "priority", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub priority: Option<Option<f64>>,
    /// Which products the threshold commit applies to. If both applicable_product_ids and applicable_product_tags are not provided, the commit applies to all products.
    #[serde(rename = "applicable_product_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub applicable_product_ids: Option<Option<Vec<uuid::Uuid>>>,
    /// Which tags the threshold commit applies to. If both applicable_product_ids and applicable_product_tags are not provided, the commit applies to all products.
    #[serde(rename = "applicable_product_tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub applicable_product_tags: Option<Option<Vec<String>>>,
    /// List of filters that determine what kind of customer usage draws down a commit or credit. A customer's usage needs to meet the condition of at least one of the specifiers to contribute to a commit's or credit's drawdown. This field cannot be used together with `applicable_product_ids` or `applicable_product_tags`. Instead, to target usage by product or product tag, pass those values in the body of `specifiers`.
    #[serde(rename = "specifiers", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub specifiers: Option<Option<Vec<models::GetContractV1200ResponseDataInitialCommitsInnerSpecifiersInner>>>,
    #[serde(rename = "duration", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub duration: Option<Option<Box<models::GetContractEditHistoryV2200ResponseDataInnerUpdatePrepaidBalanceThresholdConfigurationCommitAllOfDuration>>>,
    /// Fraction of the created commit's unused balance that will roll over. Must be between 0 and 1. Set to null to clear a previously configured rollover fraction.
    #[serde(rename = "rollover_fraction", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rollover_fraction: Option<Option<f64>>,
    /// Whether the created commits will be charged at commit rate or list rate. Set to null to clear a previously configured rate type.
    #[serde(rename = "rate_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rate_type: Option<Option<RateType>>,
}

impl GetContractEditHistoryV2200ResponseDataInnerUpdatePrepaidBalanceThresholdConfigurationCommit {
    pub fn new() -> GetContractEditHistoryV2200ResponseDataInnerUpdatePrepaidBalanceThresholdConfigurationCommit {
        GetContractEditHistoryV2200ResponseDataInnerUpdatePrepaidBalanceThresholdConfigurationCommit {
            product_id: None,
            name: None,
            description: None,
            priority: None,
            applicable_product_ids: None,
            applicable_product_tags: None,
            specifiers: None,
            duration: None,
            rollover_fraction: None,
            rate_type: None,
        }
    }
}
/// Whether the created commits will be charged at commit rate or list rate. Set to null to clear a previously configured rate type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RateType {
    #[serde(rename = "COMMIT_RATE")]
    CommitRate,
    #[serde(rename = "commit_rate")]
    CommitRate2,
    #[serde(rename = "LIST_RATE")]
    ListRate,
    #[serde(rename = "list_rate")]
    ListRate2,
}

impl Default for RateType {
    fn default() -> RateType {
        Self::CommitRate
    }
}

