/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContractV1200ResponseDataInitialProfessionalServicesInner {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "product_id")]
    pub product_id: uuid::Uuid,
    /// This field's availability is dependent on your client's configuration.
    #[serde(rename = "netsuite_sales_order_id", skip_serializing_if = "Option::is_none")]
    pub netsuite_sales_order_id: Option<String>,
    /// Unit price for the charge. Will be multiplied by quantity to determine the amount and must be specified.
    #[serde(rename = "unit_price")]
    pub unit_price: f64,
    /// Quantity for the charge. Will be multiplied by unit_price to determine the amount.
    #[serde(rename = "quantity")]
    pub quantity: f64,
    /// Maximum amount for the term.
    #[serde(rename = "max_amount")]
    pub max_amount: f64,
    /// Custom fields to be added eg. { \"key1\": \"value1\", \"key2\": \"value2\" }
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<std::collections::HashMap<String, String>>,
}

impl GetContractV1200ResponseDataInitialProfessionalServicesInner {
    pub fn new(id: uuid::Uuid, product_id: uuid::Uuid, unit_price: f64, quantity: f64, max_amount: f64) -> GetContractV1200ResponseDataInitialProfessionalServicesInner {
        GetContractV1200ResponseDataInitialProfessionalServicesInner {
            id,
            description: None,
            product_id,
            netsuite_sales_order_id: None,
            unit_price,
            quantity,
            max_amount,
            custom_fields: None,
        }
    }
}

