/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContractV1200ResponseDataInitialCommitsInnerSpecifiersInnerExcludeInner {
    /// If provided, the specifier will not apply to products with all the specified tags.
    #[serde(rename = "product_tags", skip_serializing_if = "Option::is_none")]
    pub product_tags: Option<Vec<String>>,
}

impl GetContractV1200ResponseDataInitialCommitsInnerSpecifiersInnerExcludeInner {
    pub fn new() -> GetContractV1200ResponseDataInitialCommitsInnerSpecifiersInnerExcludeInner {
        GetContractV1200ResponseDataInitialCommitsInnerSpecifiersInnerExcludeInner {
            product_tags: None,
        }
    }
}

