/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetContractV1200ResponseDataInitialSpendThresholdConfigurationDiscountConfigurationCap : If provided, the discount stops applying once the spend tracker has accumulated this much spend in the billing period.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContractV1200ResponseDataInitialSpendThresholdConfigurationDiscountConfigurationCap {
    /// Alias of the spend tracker this cap is measured against.
    #[serde(rename = "spend_tracker_alias")]
    pub spend_tracker_alias: String,
    /// Accumulated spend ceiling above which the discount stops applying.
    #[serde(rename = "amount")]
    pub amount: f64,
}

impl GetContractV1200ResponseDataInitialSpendThresholdConfigurationDiscountConfigurationCap {
    /// If provided, the discount stops applying once the spend tracker has accumulated this much spend in the billing period.
    pub fn new(spend_tracker_alias: String, amount: f64) -> GetContractV1200ResponseDataInitialSpendThresholdConfigurationDiscountConfigurationCap {
        GetContractV1200ResponseDataInitialSpendThresholdConfigurationDiscountConfigurationCap {
            spend_tracker_alias,
            amount,
        }
    }
}

