/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetContractV1200ResponseDataInitialCreditsInnerLedgerInner {
    GetContractV1200ResponseDataInitialCreditsInnerLedgerInnerOneOf(Box<models::GetContractV1200ResponseDataInitialCreditsInnerLedgerInnerOneOf>),
    GetContractV1200ResponseDataInitialCreditsInnerLedgerInnerOneOf1(Box<models::GetContractV1200ResponseDataInitialCreditsInnerLedgerInnerOneOf1>),
    GetContractV1200ResponseDataInitialCreditsInnerLedgerInnerOneOf2(Box<models::GetContractV1200ResponseDataInitialCreditsInnerLedgerInnerOneOf2>),
    GetContractV1200ResponseDataInitialCreditsInnerLedgerInnerOneOf3(Box<models::GetContractV1200ResponseDataInitialCreditsInnerLedgerInnerOneOf3>),
    GetContractV1200ResponseDataInitialCreditsInnerLedgerInnerOneOf4(Box<models::GetContractV1200ResponseDataInitialCreditsInnerLedgerInnerOneOf4>),
    GetContractV1200ResponseDataInitialCreditsInnerLedgerInnerOneOf5(Box<models::GetContractV1200ResponseDataInitialCreditsInnerLedgerInnerOneOf5>),
    GetContractV1200ResponseDataInitialCreditsInnerLedgerInnerOneOf6(Box<models::GetContractV1200ResponseDataInitialCreditsInnerLedgerInnerOneOf6>),
    GetContractV1200ResponseDataInitialCreditsInnerLedgerInnerOneOf7(Box<models::GetContractV1200ResponseDataInitialCreditsInnerLedgerInnerOneOf7>),
}

impl Default for GetContractV1200ResponseDataInitialCreditsInnerLedgerInner {
    fn default() -> Self {
        Self::GetContractV1200ResponseDataInitialCreditsInnerLedgerInnerOneOf(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "CREDIT_SEGMENT_START")]
    CreditSegmentStart,
    #[serde(rename = "CREDIT_AUTOMATED_INVOICE_DEDUCTION")]
    CreditAutomatedInvoiceDeduction,
    #[serde(rename = "CREDIT_EXPIRATION")]
    CreditExpiration,
    #[serde(rename = "CREDIT_CANCELED")]
    CreditCanceled,
    #[serde(rename = "CREDIT_CREDITED")]
    CreditCredited,
    #[serde(rename = "CREDIT_MANUAL")]
    CreditManual,
    #[serde(rename = "CREDIT_SEAT_BASED_ADJUSTMENT")]
    CreditSeatBasedAdjustment,
    #[serde(rename = "CREDIT_ROLLOVER")]
    CreditRollover,
}

impl Default for Type {
    fn default() -> Type {
        Self::CreditSegmentStart
    }
}

