/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContractNamedSchedulePayload {
    /// ID of the customer whose named schedule is to be retrieved
    #[serde(rename = "customer_id")]
    pub customer_id: uuid::Uuid,
    /// ID of the contract whose named schedule is to be retrieved
    #[serde(rename = "contract_id")]
    pub contract_id: uuid::Uuid,
    /// The identifier for the schedule to be retrieved
    #[serde(rename = "schedule_name")]
    pub schedule_name: String,
    /// If provided, at most one schedule segment will be returned (the one that covers this date). If not provided, all segments will be returned.
    #[serde(rename = "covering_date", skip_serializing_if = "Option::is_none")]
    pub covering_date: Option<String>,
    /// A set of key-value pairs that qualifies which schedule should be applied when looking up a schedule by name.
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<std::collections::HashMap<String, String>>,
}

impl GetContractNamedSchedulePayload {
    pub fn new(customer_id: uuid::Uuid, contract_id: uuid::Uuid, schedule_name: String) -> GetContractNamedSchedulePayload {
        GetContractNamedSchedulePayload {
            customer_id,
            contract_id,
            schedule_name,
            covering_date: None,
            properties: None,
        }
    }
}

