/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContractV1200ResponseDataInitialDiscountsInnerSchedule {
    #[serde(rename = "credit_type", skip_serializing_if = "Option::is_none")]
    pub credit_type: Option<Box<models::ChargeSeatsV1200ResponseCreditType>>,
    #[serde(rename = "schedule_items", skip_serializing_if = "Option::is_none")]
    pub schedule_items: Option<Vec<models::GetContractV1200ResponseDataInitialCommitsInnerInvoiceScheduleScheduleItemsInner>>,
    /// This field is only applicable to commit invoice schedules. If true, this schedule will not generate an invoice.
    #[serde(rename = "do_not_invoice", skip_serializing_if = "Option::is_none")]
    pub do_not_invoice: Option<bool>,
}

impl GetContractV1200ResponseDataInitialDiscountsInnerSchedule {
    pub fn new() -> GetContractV1200ResponseDataInitialDiscountsInnerSchedule {
        GetContractV1200ResponseDataInitialDiscountsInnerSchedule {
            credit_type: None,
            schedule_items: None,
            do_not_invoice: None,
        }
    }
}

