/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPackageV1200ResponseDataUsageStatementSchedule {
    #[serde(rename = "frequency")]
    pub frequency: Frequency,
    #[serde(rename = "day", skip_serializing_if = "Option::is_none")]
    pub day: Option<Day>,
}

impl GetPackageV1200ResponseDataUsageStatementSchedule {
    pub fn new(frequency: Frequency) -> GetPackageV1200ResponseDataUsageStatementSchedule {
        GetPackageV1200ResponseDataUsageStatementSchedule {
            frequency,
            day: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Frequency {
    #[serde(rename = "MONTHLY")]
    Monthly,
    #[serde(rename = "QUARTERLY")]
    Quarterly,
    #[serde(rename = "ANNUAL")]
    Annual,
    #[serde(rename = "WEEKLY")]
    Weekly,
}

impl Default for Frequency {
    fn default() -> Frequency {
        Self::Monthly
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Day {
    #[serde(rename = "FIRST_OF_MONTH")]
    FirstOfMonth,
    #[serde(rename = "CONTRACT_START")]
    ContractStart,
}

impl Default for Day {
    fn default() -> Day {
        Self::FirstOfMonth
    }
}

