/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPackageV1Request {
    #[serde(rename = "package_id")]
    pub package_id: uuid::Uuid,
}

impl GetPackageV1Request {
    pub fn new(package_id: uuid::Uuid) -> GetPackageV1Request {
        GetPackageV1Request {
            package_id,
        }
    }
}

