/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetPackageV1200ResponseDataCommitsInnerInvoiceSchedule : The schedule that the customer will be invoiced for this commit.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPackageV1200ResponseDataCommitsInnerInvoiceSchedule {
    #[serde(rename = "credit_type")]
    pub credit_type: Box<models::ChargeSeatsV1200ResponseCreditType>,
    #[serde(rename = "schedule_items")]
    pub schedule_items: Vec<models::GetPackageV1200ResponseDataCommitsInnerInvoiceScheduleAllOfScheduleItemsInner>,
    /// If true, this schedule will not generate an invoice.
    #[serde(rename = "do_not_invoice")]
    pub do_not_invoice: bool,
}

impl GetPackageV1200ResponseDataCommitsInnerInvoiceSchedule {
    /// The schedule that the customer will be invoiced for this commit.
    pub fn new(credit_type: models::ChargeSeatsV1200ResponseCreditType, schedule_items: Vec<models::GetPackageV1200ResponseDataCommitsInnerInvoiceScheduleAllOfScheduleItemsInner>, do_not_invoice: bool) -> GetPackageV1200ResponseDataCommitsInnerInvoiceSchedule {
        GetPackageV1200ResponseDataCommitsInnerInvoiceSchedule {
            credit_type: Box::new(credit_type),
            schedule_items,
            do_not_invoice,
        }
    }
}

