/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetContractV1200ResponseDataInitialRecurringCommitsInnerAllOfHierarchyConfiguration : Optional configuration for recurring commit/credit hierarchy access control
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContractV1200ResponseDataInitialRecurringCommitsInnerAllOfHierarchyConfiguration {
    #[serde(rename = "child_access")]
    pub child_access: Box<models::GetContractV1200ResponseDataInitialCommitsInnerHierarchyConfigurationChildAccess>,
}

impl GetContractV1200ResponseDataInitialRecurringCommitsInnerAllOfHierarchyConfiguration {
    /// Optional configuration for recurring commit/credit hierarchy access control
    pub fn new(child_access: models::GetContractV1200ResponseDataInitialCommitsInnerHierarchyConfigurationChildAccess) -> GetContractV1200ResponseDataInitialRecurringCommitsInnerAllOfHierarchyConfiguration {
        GetContractV1200ResponseDataInitialRecurringCommitsInnerAllOfHierarchyConfiguration {
            child_access: Box::new(child_access),
        }
    }
}

