/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetContractV1200ResponseDataInitialCreditsInnerAccessSchedule : The schedule that the customer will gain access to the credits.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContractV1200ResponseDataInitialCreditsInnerAccessSchedule {
    #[serde(rename = "credit_type", skip_serializing_if = "Option::is_none")]
    pub credit_type: Option<Box<models::ChargeSeatsV1200ResponseCreditType>>,
    #[serde(rename = "schedule_items")]
    pub schedule_items: Vec<models::GetContractV1200ResponseDataInitialCommitsInnerAccessScheduleScheduleItemsInner>,
}

impl GetContractV1200ResponseDataInitialCreditsInnerAccessSchedule {
    /// The schedule that the customer will gain access to the credits.
    pub fn new(schedule_items: Vec<models::GetContractV1200ResponseDataInitialCommitsInnerAccessScheduleScheduleItemsInner>) -> GetContractV1200ResponseDataInitialCreditsInnerAccessSchedule {
        GetContractV1200ResponseDataInitialCreditsInnerAccessSchedule {
            credit_type: None,
            schedule_items,
        }
    }
}

