/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContractEditHistoryV2200ResponseDataInnerAddScheduledChargesInner {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "product")]
    pub product: Box<models::GetContractV1200ResponseDataInitialCommitsInnerProduct>,
    #[serde(rename = "schedule")]
    pub schedule: Box<models::GetContractV1200ResponseDataInitialCommitsInnerInvoiceSchedule>,
    /// displayed on invoices
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// This field's availability is dependent on your client's configuration.
    #[serde(rename = "netsuite_sales_order_id", skip_serializing_if = "Option::is_none")]
    pub netsuite_sales_order_id: Option<String>,
}

impl GetContractEditHistoryV2200ResponseDataInnerAddScheduledChargesInner {
    pub fn new(id: uuid::Uuid, product: models::GetContractV1200ResponseDataInitialCommitsInnerProduct, schedule: models::GetContractV1200ResponseDataInitialCommitsInnerInvoiceSchedule) -> GetContractEditHistoryV2200ResponseDataInnerAddScheduledChargesInner {
        GetContractEditHistoryV2200ResponseDataInnerAddScheduledChargesInner {
            id,
            product: Box::new(product),
            schedule: Box::new(schedule),
            name: None,
            netsuite_sales_order_id: None,
        }
    }
}

