/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetContractV1200ResponseDataInitialCommitsInnerInvoiceContract : The contract that this commit will be billed on.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContractV1200ResponseDataInitialCommitsInnerInvoiceContract {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
}

impl GetContractV1200ResponseDataInitialCommitsInnerInvoiceContract {
    /// The contract that this commit will be billed on.
    pub fn new(id: uuid::Uuid) -> GetContractV1200ResponseDataInitialCommitsInnerInvoiceContract {
        GetContractV1200ResponseDataInitialCommitsInnerInvoiceContract {
            id,
        }
    }
}

