/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HierarchyLink {
    #[serde(rename = "contract_id")]
    pub contract_id: uuid::Uuid,
    #[serde(rename = "customer_id")]
    pub customer_id: uuid::Uuid,
}

impl HierarchyLink {
    pub fn new(contract_id: uuid::Uuid, customer_id: uuid::Uuid) -> HierarchyLink {
        HierarchyLink {
            contract_id,
            customer_id,
        }
    }
}

