/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HierarchyConfigurationV2 : Either a **parent** configuration with a list of children or a **child** configuration with a single parent. 
/// Either a **parent** configuration with a list of children or a **child** configuration with a single parent. 
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum HierarchyConfigurationV2 {
    ParentHierarchyConfiguration(Box<models::ParentHierarchyConfiguration>),
    ChildHierarchyConfigurationV2(Box<models::ChildHierarchyConfigurationV2>),
}

impl Default for HierarchyConfigurationV2 {
    fn default() -> Self {
        Self::ParentHierarchyConfiguration(Default::default())
    }
}
/// Indicates which customer should pay for the child's invoice charges **SELF**: The child pays for its own invoice charges **PARENT**: The parent pays for the child's invoice charges
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Payer {
    #[serde(rename = "SELF")]
    VariantSelf,
    #[serde(rename = "PARENT")]
    Parent,
}

impl Default for Payer {
    fn default() -> Payer {
        Self::VariantSelf
    }
}
/// Indicates the behavior of the child's invoice statements on the parent's invoices.  **CONSOLIDATE**: Child's invoice statements will be added to parent's consolidated invoices  **SEPARATE**: Child's invoice statements will appear not appear on parent's consolidated invoices
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UsageStatementBehavior {
    #[serde(rename = "CONSOLIDATE")]
    Consolidate,
    #[serde(rename = "SEPARATE")]
    Separate,
}

impl Default for UsageStatementBehavior {
    fn default() -> UsageStatementBehavior {
        Self::Consolidate
    }
}

