/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvoiceResellerRoyaltyGcpOptions {
    #[serde(rename = "gcp_account_id", skip_serializing_if = "Option::is_none")]
    pub gcp_account_id: Option<String>,
    #[serde(rename = "gcp_offer_id", skip_serializing_if = "Option::is_none")]
    pub gcp_offer_id: Option<String>,
}

impl InvoiceResellerRoyaltyGcpOptions {
    pub fn new() -> InvoiceResellerRoyaltyGcpOptions {
        InvoiceResellerRoyaltyGcpOptions {
            gcp_account_id: None,
            gcp_offer_id: None,
        }
    }
}

