/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InvoiceLineItemOrigin : Present on line items from invoices with type USAGE_CONSOLIDATED. Indicates the original customer, contract, invoice and line item from which this line item was copied.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvoiceLineItemOrigin {
    #[serde(rename = "line_item_id")]
    pub line_item_id: uuid::Uuid,
    #[serde(rename = "invoice_id")]
    pub invoice_id: uuid::Uuid,
    #[serde(rename = "customer_id")]
    pub customer_id: uuid::Uuid,
    #[serde(rename = "contract_id")]
    pub contract_id: uuid::Uuid,
}

impl InvoiceLineItemOrigin {
    /// Present on line items from invoices with type USAGE_CONSOLIDATED. Indicates the original customer, contract, invoice and line item from which this line item was copied.
    pub fn new(line_item_id: uuid::Uuid, invoice_id: uuid::Uuid, customer_id: uuid::Uuid, contract_id: uuid::Uuid) -> InvoiceLineItemOrigin {
        InvoiceLineItemOrigin {
            line_item_id,
            invoice_id,
            customer_id,
            contract_id,
        }
    }
}

