/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvoiceCorrectionRecord {
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "memo")]
    pub memo: String,
    #[serde(rename = "corrected_invoice_id")]
    pub corrected_invoice_id: uuid::Uuid,
    #[serde(rename = "corrected_external_invoice", skip_serializing_if = "Option::is_none")]
    pub corrected_external_invoice: Option<Box<models::ExternalInvoice>>,
}

impl InvoiceCorrectionRecord {
    pub fn new(reason: String, memo: String, corrected_invoice_id: uuid::Uuid) -> InvoiceCorrectionRecord {
        InvoiceCorrectionRecord {
            reason,
            memo,
            corrected_invoice_id,
            corrected_external_invoice: None,
        }
    }
}

