/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvoiceResellerRoyaltyAwsOptions {
    #[serde(rename = "aws_account_number", skip_serializing_if = "Option::is_none")]
    pub aws_account_number: Option<String>,
    #[serde(rename = "aws_payer_reference_id", skip_serializing_if = "Option::is_none")]
    pub aws_payer_reference_id: Option<String>,
    #[serde(rename = "aws_offer_id", skip_serializing_if = "Option::is_none")]
    pub aws_offer_id: Option<String>,
}

impl InvoiceResellerRoyaltyAwsOptions {
    pub fn new() -> InvoiceResellerRoyaltyAwsOptions {
        InvoiceResellerRoyaltyAwsOptions {
            aws_account_number: None,
            aws_payer_reference_id: None,
            aws_offer_id: None,
        }
    }
}

