/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LifecycleEventOffsetPolicy {
    /// The type of lifecycle event that this offset is based on. 
    #[serde(rename = "type")]
    pub r#type: String,
    /// ISO-8601 duration string indicating how much time before or after the base event this notification should be sent. Positive values indicate notifications after the event, negative values indicate notifications before the event. Examples: \"P1D\" (1 day after), \"-PT2H\" (2 hours before) 
    #[serde(rename = "offset")]
    pub offset: String,
}

impl LifecycleEventOffsetPolicy {
    pub fn new(r#type: String, offset: String) -> LifecycleEventOffsetPolicy {
        LifecycleEventOffsetPolicy {
            r#type,
            offset,
        }
    }
}

