/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LifecycleEventOffsetNotificationConfig {
    /// ID for this offset notification configuration
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// The name for this offset notification configuration. 
    #[serde(rename = "name")]
    pub name: String,
    /// Indicates this is an offset lifecycle event notification
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "policy")]
    pub policy: Box<models::LifecycleEventOffsetPolicy>,
    /// The environment type where this notification configuration was created. 
    #[serde(rename = "environment_type")]
    pub environment_type: String,
    /// RFC 3339 timestamp when this notification configuration was created. 
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    /// Who created this notification configuration
    #[serde(rename = "created_by")]
    pub created_by: String,
    /// When this notification configuration was archived
    #[serde(rename = "archived_at", deserialize_with = "Option::deserialize")]
    pub archived_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl LifecycleEventOffsetNotificationConfig {
    pub fn new(id: uuid::Uuid, name: String, r#type: String, policy: models::LifecycleEventOffsetPolicy, environment_type: String, created_at: chrono::DateTime<chrono::FixedOffset>, created_by: String, archived_at: Option<chrono::DateTime<chrono::FixedOffset>>) -> LifecycleEventOffsetNotificationConfig {
        LifecycleEventOffsetNotificationConfig {
            id,
            name,
            r#type,
            policy: Box::new(policy),
            environment_type,
            created_at,
            created_by,
            archived_at,
        }
    }
}

