/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListContractsV2Request {
    #[serde(rename = "customer_id")]
    pub customer_id: uuid::Uuid,
    /// Include commit/credit ledgers in the response. Setting this flag may cause the response to be slower.
    #[serde(rename = "include_ledgers", skip_serializing_if = "Option::is_none")]
    pub include_ledgers: Option<bool>,
    /// Include archived contracts in the response.
    #[serde(rename = "include_archived", skip_serializing_if = "Option::is_none")]
    pub include_archived: Option<bool>,
    /// Include the balance of credits and commits in the response. Setting this flag may cause the response to be slower.
    #[serde(rename = "include_balance", skip_serializing_if = "Option::is_none")]
    pub include_balance: Option<bool>,
    /// Optional RFC 3339 timestamp. Only include contracts that started on or after this date. This cannot be provided if covering_date filter is provided.
    #[serde(rename = "starting_at", skip_serializing_if = "Option::is_none")]
    pub starting_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Optional RFC 3339 timestamp. Only include contracts active on the provided date. This cannot be provided if starting_at filter is provided.
    #[serde(rename = "covering_date", skip_serializing_if = "Option::is_none")]
    pub covering_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Max number of contracts to return per page. Range: 1-20. Default: 20.
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<f64>,
    /// Cursor from a previous response to fetch the next page of contracts.
    #[serde(rename = "cursor", skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
}

impl ListContractsV2Request {
    pub fn new(customer_id: uuid::Uuid) -> ListContractsV2Request {
        ListContractsV2Request {
            customer_id,
            include_ledgers: None,
            include_archived: None,
            include_balance: None,
            starting_at: None,
            covering_date: None,
            limit: None,
            cursor: None,
        }
    }
}

