/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListCustomerBalancesV1200ResponseDataInner {
    Commit(Box<models::Commit>),
    Credit(Box<models::Credit>),
}

impl Default for ListCustomerBalancesV1200ResponseDataInner {
    fn default() -> Self {
        Self::Commit(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "PREPAID")]
    Prepaid,
    #[serde(rename = "POSTPAID")]
    Postpaid,
    #[serde(rename = "CREDIT")]
    Credit,
}

impl Default for Type {
    fn default() -> Type {
        Self::Prepaid
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RateType {
    #[serde(rename = "COMMIT_RATE")]
    CommitRate,
    #[serde(rename = "LIST_RATE")]
    ListRate,
}

impl Default for RateType {
    fn default() -> RateType {
        Self::CommitRate
    }
}

