/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListCustomerBalancesV1Request {
    #[serde(rename = "customer_id")]
    pub customer_id: uuid::Uuid,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// Return only balances that have access schedules that \"cover\" the provided date
    #[serde(rename = "covering_date", skip_serializing_if = "Option::is_none")]
    pub covering_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Include only balances that have any access on or after the provided date
    #[serde(rename = "starting_at", skip_serializing_if = "Option::is_none")]
    pub starting_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Include only balances that have any access before the provided date (exclusive)
    #[serde(rename = "effective_before", skip_serializing_if = "Option::is_none")]
    pub effective_before: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Include balances on the contract level.
    #[serde(rename = "include_contract_balances", skip_serializing_if = "Option::is_none")]
    pub include_contract_balances: Option<bool>,
    /// Include archived credits and credits from archived contracts.
    #[serde(rename = "include_archived", skip_serializing_if = "Option::is_none")]
    pub include_archived: Option<bool>,
    /// Include ledgers in the response. Setting this flag may cause the query to be slower.
    #[serde(rename = "include_ledgers", skip_serializing_if = "Option::is_none")]
    pub include_ledgers: Option<bool>,
    /// Include the balance of credits and commits in the response. Setting this flag may cause the query to be slower.
    #[serde(rename = "include_balance", skip_serializing_if = "Option::is_none")]
    pub include_balance: Option<bool>,
    /// The next page token from a previous response.
    #[serde(rename = "next_page", skip_serializing_if = "Option::is_none")]
    pub next_page: Option<String>,
    /// The maximum number of commits to return. Defaults to 25.
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    /// Exclude balances with zero amounts from the response.
    #[serde(rename = "exclude_zero_balances", skip_serializing_if = "Option::is_none")]
    pub exclude_zero_balances: Option<bool>,
    /// Indicates that this API request was triggered by a webhook notification with the provided ID.
    #[serde(rename = "webhook_notification_id", skip_serializing_if = "Option::is_none")]
    pub webhook_notification_id: Option<String>,
}

impl ListCustomerBalancesV1Request {
    pub fn new(customer_id: uuid::Uuid) -> ListCustomerBalancesV1Request {
        ListCustomerBalancesV1Request {
            customer_id,
            id: None,
            covering_date: None,
            starting_at: None,
            effective_before: None,
            include_contract_balances: None,
            include_archived: None,
            include_ledgers: None,
            include_balance: None,
            next_page: None,
            limit: None,
            exclude_zero_balances: None,
            webhook_notification_id: None,
        }
    }
}

