/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListConfiguredBillingProvidersV1200ResponseDataInner {
    /// The billing provider set for this configuration.
    #[serde(rename = "billing_provider")]
    pub billing_provider: BillingProvider,
    /// ID of the delivery method to use for this customer.
    #[serde(rename = "delivery_method_id")]
    pub delivery_method_id: uuid::Uuid,
    /// The method to use for delivering invoices to this customer.
    #[serde(rename = "delivery_method")]
    pub delivery_method: DeliveryMethod,
    /// Configuration for the delivery method. The structure of this object is specific to the delivery method. Some configuration may be omitted for security reasons.
    #[serde(rename = "delivery_method_configuration")]
    pub delivery_method_configuration: std::collections::HashMap<String, serde_json::Value>,
}

impl ListConfiguredBillingProvidersV1200ResponseDataInner {
    pub fn new(billing_provider: BillingProvider, delivery_method_id: uuid::Uuid, delivery_method: DeliveryMethod, delivery_method_configuration: std::collections::HashMap<String, serde_json::Value>) -> ListConfiguredBillingProvidersV1200ResponseDataInner {
        ListConfiguredBillingProvidersV1200ResponseDataInner {
            billing_provider,
            delivery_method_id,
            delivery_method,
            delivery_method_configuration,
        }
    }
}
/// The billing provider set for this configuration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BillingProvider {
    #[serde(rename = "aws_marketplace")]
    AwsMarketplace,
    #[serde(rename = "stripe")]
    Stripe,
    #[serde(rename = "netsuite")]
    Netsuite,
    #[serde(rename = "custom")]
    Custom,
    #[serde(rename = "azure_marketplace")]
    AzureMarketplace,
    #[serde(rename = "quickbooks_online")]
    QuickbooksOnline,
    #[serde(rename = "workday")]
    Workday,
    #[serde(rename = "gcp_marketplace")]
    GcpMarketplace,
    #[serde(rename = "metronome")]
    Metronome,
}

impl Default for BillingProvider {
    fn default() -> BillingProvider {
        Self::AwsMarketplace
    }
}
/// The method to use for delivering invoices to this customer.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeliveryMethod {
    #[serde(rename = "direct_to_billing_provider")]
    DirectToBillingProvider,
    #[serde(rename = "aws_sqs")]
    AwsSqs,
    #[serde(rename = "tackle")]
    Tackle,
    #[serde(rename = "aws_sns")]
    AwsSns,
}

impl Default for DeliveryMethod {
    fn default() -> DeliveryMethod {
        Self::DirectToBillingProvider
    }
}

