/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListContractsV1200Response {
    #[serde(rename = "data")]
    pub data: Vec<models::GetContractV1200ResponseData>,
    /// Pass this value as `cursor` in a subsequent request to fetch the next page of contracts. Null if there are no more contracts.
    #[serde(rename = "cursor", deserialize_with = "Option::deserialize")]
    pub cursor: Option<String>,
}

impl ListContractsV1200Response {
    pub fn new(data: Vec<models::GetContractV1200ResponseData>, cursor: Option<String>) -> ListContractsV1200Response {
        ListContractsV1200Response {
            data,
            cursor,
        }
    }
}

