/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListSeatBalancesV1200ResponseDataInnerBalancesInner {
    #[serde(rename = "credit_type_id")]
    pub credit_type_id: uuid::Uuid,
    /// The total balance across all commits and credits for this seat, of this credit type.
    #[serde(rename = "balance")]
    pub balance: f64,
    /// The total initial balances of all commits and credits for this seat, of this credit type.
    #[serde(rename = "starting_balance")]
    pub starting_balance: f64,
}

impl ListSeatBalancesV1200ResponseDataInnerBalancesInner {
    pub fn new(credit_type_id: uuid::Uuid, balance: f64, starting_balance: f64) -> ListSeatBalancesV1200ResponseDataInnerBalancesInner {
        ListSeatBalancesV1200ResponseDataInnerBalancesInner {
            credit_type_id,
            balance,
            starting_balance,
        }
    }
}

