/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListContractsOnPackageV1400Response {
    #[serde(rename = "code")]
    pub code: Code,
    #[serde(rename = "message")]
    pub message: String,
}

impl ListContractsOnPackageV1400Response {
    pub fn new(code: Code, message: String) -> ListContractsOnPackageV1400Response {
        ListContractsOnPackageV1400Response {
            code,
            message,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Code {
    #[serde(rename = "PackageNotFound")]
    PackageNotFound,
}

impl Default for Code {
    fn default() -> Code {
        Self::PackageNotFound
    }
}

