/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListContractsNamedSchedulesPage {
    #[serde(rename = "data")]
    pub data: Vec<models::CustomerContractNamedSchedule>,
    /// Cursor for the next page of results.
    #[serde(rename = "next_page", deserialize_with = "Option::deserialize")]
    pub next_page: Option<String>,
}

impl ListContractsNamedSchedulesPage {
    pub fn new(data: Vec<models::CustomerContractNamedSchedule>, next_page: Option<String>) -> ListContractsNamedSchedulesPage {
        ListContractsNamedSchedulesPage {
            data,
            next_page,
        }
    }
}

