/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListApprovalRequestsV1200ResponseDataInnerResponse {
    #[serde(rename = "response_status", deserialize_with = "Option::deserialize")]
    pub response_status: Option<f64>,
    #[serde(rename = "response_body", deserialize_with = "Option::deserialize")]
    pub response_body: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl ListApprovalRequestsV1200ResponseDataInnerResponse {
    pub fn new(response_status: Option<f64>, response_body: Option<std::collections::HashMap<String, serde_json::Value>>) -> ListApprovalRequestsV1200ResponseDataInnerResponse {
        ListApprovalRequestsV1200ResponseDataInnerResponse {
            response_status,
            response_body,
        }
    }
}

