/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListSpendBreakdownInvoicesV1200Response {
    #[serde(rename = "data")]
    pub data: Vec<models::SpendBreakdownInvoice>,
    #[serde(rename = "next_page", deserialize_with = "Option::deserialize")]
    pub next_page: Option<String>,
}

impl ListSpendBreakdownInvoicesV1200Response {
    pub fn new(data: Vec<models::SpendBreakdownInvoice>, next_page: Option<String>) -> ListSpendBreakdownInvoicesV1200Response {
        ListSpendBreakdownInvoicesV1200Response {
            data,
            next_page,
        }
    }
}

