/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListSeatBalancesV1200ResponseDataInnerCreditsInnerLedgerEntriesInner {
    /// Credit ledger type
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Amount of the ledger entry
    #[serde(rename = "amount")]
    pub amount: f64,
    /// The datetime when the ledger is created
    #[serde(rename = "timestamp")]
    pub timestamp: chrono::DateTime<chrono::FixedOffset>,
}

impl ListSeatBalancesV1200ResponseDataInnerCreditsInnerLedgerEntriesInner {
    pub fn new(r#type: Type, amount: f64, timestamp: chrono::DateTime<chrono::FixedOffset>) -> ListSeatBalancesV1200ResponseDataInnerCreditsInnerLedgerEntriesInner {
        ListSeatBalancesV1200ResponseDataInnerCreditsInnerLedgerEntriesInner {
            r#type,
            amount,
            timestamp,
        }
    }
}
/// Credit ledger type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "CREDIT_SEGMENT_START")]
    CreditSegmentStart,
    #[serde(rename = "CREDIT_AUTOMATED_INVOICE_DEDUCTION")]
    CreditAutomatedInvoiceDeduction,
    #[serde(rename = "CREDIT_EXPIRATION")]
    CreditExpiration,
    #[serde(rename = "CREDIT_CANCELED")]
    CreditCanceled,
    #[serde(rename = "CREDIT_CREDITED")]
    CreditCredited,
    #[serde(rename = "CREDIT_MANUAL")]
    CreditManual,
    #[serde(rename = "CREDIT_SEAT_BASED_ADJUSTMENT")]
    CreditSeatBasedAdjustment,
    #[serde(rename = "CREDIT_ROLLOVER")]
    CreditRollover,
}

impl Default for Type {
    fn default() -> Type {
        Self::CreditSegmentStart
    }
}

