/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListCustomerCommitsV1Request {
    #[serde(rename = "customer_id")]
    pub customer_id: uuid::Uuid,
    #[serde(rename = "commit_id", skip_serializing_if = "Option::is_none")]
    pub commit_id: Option<uuid::Uuid>,
    /// Include only commits that have access schedules that \"cover\" the provided date
    #[serde(rename = "covering_date", skip_serializing_if = "Option::is_none")]
    pub covering_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Include only commits that have any access on or after the provided date
    #[serde(rename = "starting_at", skip_serializing_if = "Option::is_none")]
    pub starting_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Include only commits that have any access before the provided date (exclusive)
    #[serde(rename = "effective_before", skip_serializing_if = "Option::is_none")]
    pub effective_before: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Include commits on the contract level.
    #[serde(rename = "include_contract_commits", skip_serializing_if = "Option::is_none")]
    pub include_contract_commits: Option<bool>,
    /// Include archived commits and commits from archived contracts.
    #[serde(rename = "include_archived", skip_serializing_if = "Option::is_none")]
    pub include_archived: Option<bool>,
    /// Include commit ledgers in the response. Setting this flag may cause the query to be slower.
    #[serde(rename = "include_ledgers", skip_serializing_if = "Option::is_none")]
    pub include_ledgers: Option<bool>,
    /// Include the balance in the response. Setting this flag may cause the query to be slower.
    #[serde(rename = "include_balance", skip_serializing_if = "Option::is_none")]
    pub include_balance: Option<bool>,
    /// The next page token from a previous response.
    #[serde(rename = "next_page", skip_serializing_if = "Option::is_none")]
    pub next_page: Option<String>,
    /// The maximum number of commits to return. Defaults to 25.
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
}

impl ListCustomerCommitsV1Request {
    pub fn new(customer_id: uuid::Uuid) -> ListCustomerCommitsV1Request {
        ListCustomerCommitsV1Request {
            customer_id,
            commit_id: None,
            covering_date: None,
            starting_at: None,
            effective_before: None,
            include_contract_commits: None,
            include_archived: None,
            include_ledgers: None,
            include_balance: None,
            next_page: None,
            limit: None,
        }
    }
}

