/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListContractsOnPackageV1Request {
    #[serde(rename = "package_id")]
    pub package_id: uuid::Uuid,
    /// Optional RFC 3339 timestamp. Only include contracts that started on or after this date. This cannot be provided if covering_date filter is provided.
    #[serde(rename = "starting_at", skip_serializing_if = "Option::is_none")]
    pub starting_at: Option<String>,
    /// Optional RFC 3339 timestamp. Only include contracts active on the provided date. This cannot be provided if starting_at filter is provided.
    #[serde(rename = "covering_date", skip_serializing_if = "Option::is_none")]
    pub covering_date: Option<String>,
    /// Default false. Determines whether to include archived contracts in the results
    #[serde(rename = "include_archived", skip_serializing_if = "Option::is_none")]
    pub include_archived: Option<bool>,
}

impl ListContractsOnPackageV1Request {
    pub fn new(package_id: uuid::Uuid) -> ListContractsOnPackageV1Request {
        ListContractsOnPackageV1Request {
            package_id,
            starting_at: None,
            covering_date: None,
            include_archived: None,
        }
    }
}

