/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MoveToHistoryResponse {
    /// Number of commits successfully moved to historical in this request
    #[serde(rename = "historical_count")]
    pub historical_count: f64,
    /// IDs of the commits that were moved to historical
    #[serde(rename = "historical_commit_ids")]
    pub historical_commit_ids: Vec<uuid::Uuid>,
    /// Number of commits that were skipped due to ineligibility
    #[serde(rename = "skipped_count")]
    pub skipped_count: f64,
    /// Per-commit details on why specific commits were not moved to historical
    #[serde(rename = "skipped_reasons")]
    pub skipped_reasons: Vec<models::MoveToHistoryResponseSkippedReasonsInner>,
}

impl MoveToHistoryResponse {
    pub fn new(historical_count: f64, historical_commit_ids: Vec<uuid::Uuid>, skipped_count: f64, skipped_reasons: Vec<models::MoveToHistoryResponseSkippedReasonsInner>) -> MoveToHistoryResponse {
        MoveToHistoryResponse {
            historical_count,
            historical_commit_ids,
            skipped_count,
            skipped_reasons,
        }
    }
}

