/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MoveRateCardProductsPayloadProductMovesInner {
    /// ID of the product to move
    #[serde(rename = "product_id")]
    pub product_id: uuid::Uuid,
    /// 0-based index of the new position of the product
    #[serde(rename = "position")]
    pub position: f64,
}

impl MoveRateCardProductsPayloadProductMovesInner {
    pub fn new(product_id: uuid::Uuid, position: f64) -> MoveRateCardProductsPayloadProductMovesInner {
        MoveRateCardProductsPayloadProductMovesInner {
            product_id,
            position,
        }
    }
}

