/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MoveRateCardProductsPayload {
    /// ID of the rate card to update
    #[serde(rename = "rate_card_id")]
    pub rate_card_id: uuid::Uuid,
    #[serde(rename = "product_moves")]
    pub product_moves: Vec<models::MoveRateCardProductsPayloadProductMovesInner>,
}

impl MoveRateCardProductsPayload {
    pub fn new(rate_card_id: uuid::Uuid, product_moves: Vec<models::MoveRateCardProductsPayloadProductMovesInner>) -> MoveRateCardProductsPayload {
        MoveRateCardProductsPayload {
            rate_card_id,
            product_moves,
        }
    }
}

