/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OverrideInput {
    /// RFC 3339 timestamp indicating when the override will start applying (inclusive)
    #[serde(rename = "starting_at")]
    pub starting_at: chrono::DateTime<chrono::FixedOffset>,
    /// RFC 3339 timestamp indicating when the override will stop applying (exclusive)
    #[serde(rename = "ending_before", skip_serializing_if = "Option::is_none")]
    pub ending_before: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "entitled", skip_serializing_if = "Option::is_none")]
    pub entitled: Option<bool>,
    /// Overwrites are prioritized over multipliers and tiered overrides.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    /// Required for MULTIPLIER type. Must be >=0.
    #[serde(rename = "multiplier", skip_serializing_if = "Option::is_none")]
    pub multiplier: Option<f64>,
    /// Required for EXPLICIT multiplier prioritization scheme and all TIERED overrides. Under EXPLICIT prioritization, overwrites are prioritized first, and then tiered and multiplier overrides are prioritized by their priority value (lowest first). Must be > 0.
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<f64>,
    #[serde(rename = "overwrite_rate", skip_serializing_if = "Option::is_none")]
    pub overwrite_rate: Option<Box<models::OverwriteRateInput>>,
    /// ID of the product whose rate is being overridden. Cannot be used in conjunction with override_specifiers.
    #[serde(rename = "product_id", skip_serializing_if = "Option::is_none")]
    pub product_id: Option<uuid::Uuid>,
    /// tags identifying products whose rates are being overridden. Cannot be used in conjunction with override_specifiers.
    #[serde(rename = "applicable_product_tags", skip_serializing_if = "Option::is_none")]
    pub applicable_product_tags: Option<Vec<String>>,
    /// Cannot be used in conjunction with product_id or applicable_product_tags. If provided, the override will apply to all products with the specified specifiers.
    #[serde(rename = "override_specifiers", skip_serializing_if = "Option::is_none")]
    pub override_specifiers: Option<Vec<models::OverrideSpecifierInput>>,
    /// Required for TIERED type. Must have at least one tier.
    #[serde(rename = "tiers", skip_serializing_if = "Option::is_none")]
    pub tiers: Option<Vec<models::OverrideTierInput>>,
    /// Indicates whether the override should only apply to commits. Defaults to `false`. If `true` you can specify relevant commits in `override_specifiers` by passing `commit_ids`, `recurring_commit_ids`, or `any_commit_or_credit_ids`.  If you do not specify any of these fields, the override will apply when consuming any prepaid commit, postpaid commit, or credit
    #[serde(rename = "is_commit_specific", skip_serializing_if = "Option::is_none")]
    pub is_commit_specific: Option<bool>,
    /// Indicates whether the override applies to commit rates or list rates. Can only be used for overrides that have `is_commit_specific` set to `true`. Defaults to `\"LIST_RATE\"`.
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<Target>,
}

impl OverrideInput {
    pub fn new(starting_at: chrono::DateTime<chrono::FixedOffset>) -> OverrideInput {
        OverrideInput {
            starting_at,
            ending_before: None,
            entitled: None,
            r#type: None,
            multiplier: None,
            priority: None,
            overwrite_rate: None,
            product_id: None,
            applicable_product_tags: None,
            override_specifiers: None,
            tiers: None,
            is_commit_specific: None,
            target: None,
        }
    }
}
/// Overwrites are prioritized over multipliers and tiered overrides.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "OVERWRITE")]
    Overwrite,
    #[serde(rename = "overwrite")]
    Overwrite2,
    #[serde(rename = "MULTIPLIER")]
    Multiplier,
    #[serde(rename = "multiplier")]
    Multiplier2,
    #[serde(rename = "TIERED")]
    Tiered,
    #[serde(rename = "tiered")]
    Tiered2,
}

impl Default for Type {
    fn default() -> Type {
        Self::Overwrite
    }
}
/// Indicates whether the override applies to commit rates or list rates. Can only be used for overrides that have `is_commit_specific` set to `true`. Defaults to `\"LIST_RATE\"`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Target {
    #[serde(rename = "COMMIT_RATE")]
    CommitRate,
    #[serde(rename = "commit_rate")]
    CommitRate2,
    #[serde(rename = "LIST_RATE")]
    ListRate,
    #[serde(rename = "list_rate")]
    ListRate2,
}

impl Default for Target {
    fn default() -> Target {
        Self::CommitRate
    }
}

