/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PackageSubscriptionCustomization {
    /// ID of the template subscription on the package to customize.
    #[serde(rename = "template_subscription_id")]
    pub template_subscription_id: uuid::Uuid,
    /// The initial quantity for the subscription. Must be a non-negative value. Provide for a QUANTITY_ONLY subscription.
    #[serde(rename = "initial_quantity", skip_serializing_if = "Option::is_none")]
    pub initial_quantity: Option<f64>,
    /// Seat identifiers to assign at the start of a SEAT_BASED subscription.
    #[serde(rename = "initial_seat_ids", skip_serializing_if = "Option::is_none")]
    pub initial_seat_ids: Option<Vec<String>>,
    /// Number of unassigned seats to provision at the start of a SEAT_BASED subscription.
    #[serde(rename = "initial_unassigned_seats", skip_serializing_if = "Option::is_none")]
    pub initial_unassigned_seats: Option<f64>,
}

impl PackageSubscriptionCustomization {
    pub fn new(template_subscription_id: uuid::Uuid) -> PackageSubscriptionCustomization {
        PackageSubscriptionCustomization {
            template_subscription_id,
            initial_quantity: None,
            initial_seat_ids: None,
            initial_unassigned_seats: None,
        }
    }
}

