/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParentHierarchyConfiguration {
    /// List of contracts that belong to this parent.
    #[serde(rename = "children")]
    pub children: Vec<models::HierarchyLink>,
    #[serde(rename = "parent_behavior", skip_serializing_if = "Option::is_none")]
    pub parent_behavior: Option<Box<models::ParentHierarchyConfigurationParentBehavior>>,
}

impl ParentHierarchyConfiguration {
    pub fn new(children: Vec<models::HierarchyLink>) -> ParentHierarchyConfiguration {
        ParentHierarchyConfiguration {
            children,
            parent_behavior: None,
        }
    }
}

