/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PrepaidGrantOptionsStripeOptions : Options for prepaid credits using Stripe
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrepaidGrantOptionsStripeOptions {
    /// Whether to calculate tax for the prepaid invoice Defaults to false if not provided.
    #[serde(rename = "calculate_tax", skip_serializing_if = "Option::is_none")]
    pub calculate_tax: Option<bool>,
    #[serde(rename = "tax_platform", skip_serializing_if = "Option::is_none")]
    pub tax_platform: Option<models::TaxPlatform>,
    /// Whether to skip tax calculation if the tax platform returns an error. Defaults to true if not provided.
    #[serde(rename = "skip_tax_on_tax_platform_error", skip_serializing_if = "Option::is_none")]
    pub skip_tax_on_tax_platform_error: Option<bool>,
    /// The tax amount to use for the prepaid invoice. If provided, this will be used instead of calculating tax. Not applicable for recharge settings. Decimal numbers are not supported and the value is the smallest denomination of the currency (e.g. cents).
    #[serde(rename = "precalculated_tax", skip_serializing_if = "Option::is_none")]
    pub precalculated_tax: Option<f64>,
    /// Optional Stripe product ID to use for the tax line item in Stripe. If omitted a random Stripe product will be created and used for the invoice.
    #[serde(rename = "tax_product_id", skip_serializing_if = "Option::is_none")]
    pub tax_product_id: Option<String>,
    /// The URL to redirect the user to after they have corrected a billing issue
    #[serde(rename = "redirect_url", skip_serializing_if = "Option::is_none")]
    pub redirect_url: Option<String>,
    /// Custom fields to add to the prepaid invoice
    #[serde(rename = "invoice_custom_fields", skip_serializing_if = "Option::is_none")]
    pub invoice_custom_fields: Option<Vec<models::NameValuePair>>,
    /// Invoice metadata to add to the prepaid invoice
    #[serde(rename = "invoice_metadata", skip_serializing_if = "Option::is_none")]
    pub invoice_metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Optional Stripe payment method ID to use.
    #[serde(rename = "payment_method_id", skip_serializing_if = "Option::is_none")]
    pub payment_method_id: Option<String>,
    /// Optional Stripe product ID for the invoice line item. This will be passed to Stripe on the associated credit grant invoice line item and other tax platforms if applicable.
    #[serde(rename = "product_id", skip_serializing_if = "Option::is_none")]
    pub product_id: Option<String>,
    /// Optional Radar session ID to send to Stripe when creating the payment intent.
    #[serde(rename = "radar_session_id", skip_serializing_if = "Option::is_none")]
    pub radar_session_id: Option<String>,
}

impl PrepaidGrantOptionsStripeOptions {
    /// Options for prepaid credits using Stripe
    pub fn new() -> PrepaidGrantOptionsStripeOptions {
        PrepaidGrantOptionsStripeOptions {
            calculate_tax: None,
            tax_platform: None,
            skip_tax_on_tax_platform_error: None,
            precalculated_tax: None,
            tax_product_id: None,
            redirect_url: None,
            invoice_custom_fields: None,
            invoice_metadata: None,
            payment_method_id: None,
            product_id: None,
            radar_session_id: None,
        }
    }
}

