/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QuantityRounding : Optional. Only valid for USAGE products. If provided, the quantity will be rounded using the provided rounding method and decimal places. For example, if the method is \"round up\" and the decimal places is 0, then the quantity will be rounded up to the nearest integer.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuantityRounding {
    #[serde(rename = "rounding_method")]
    pub rounding_method: RoundingMethod,
    #[serde(rename = "decimal_places")]
    pub decimal_places: f64,
}

impl QuantityRounding {
    /// Optional. Only valid for USAGE products. If provided, the quantity will be rounded using the provided rounding method and decimal places. For example, if the method is \"round up\" and the decimal places is 0, then the quantity will be rounded up to the nearest integer.
    pub fn new(rounding_method: RoundingMethod, decimal_places: f64) -> QuantityRounding {
        QuantityRounding {
            rounding_method,
            decimal_places,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RoundingMethod {
    #[serde(rename = "round_up")]
    RoundUp,
    #[serde(rename = "round_down")]
    RoundDown,
    #[serde(rename = "round_half_up")]
    RoundHalfUp,
    #[serde(rename = "ROUND_UP")]
    RoundUp2,
    #[serde(rename = "ROUND_DOWN")]
    RoundDown2,
    #[serde(rename = "ROUND_HALF_UP")]
    RoundHalfUp2,
}

impl Default for RoundingMethod {
    fn default() -> RoundingMethod {
        Self::RoundUp
    }
}

