/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecurringCommitSubscriptionConfig {
    #[serde(rename = "allocation")]
    pub allocation: models::SubscriptionConfigAllocation,
    #[serde(rename = "apply_seat_increase_config")]
    pub apply_seat_increase_config: Box<models::ApplySeatIncreaseConfigForRecurringCommit>,
    #[serde(rename = "subscription_id")]
    pub subscription_id: uuid::Uuid,
}

impl RecurringCommitSubscriptionConfig {
    pub fn new(allocation: models::SubscriptionConfigAllocation, apply_seat_increase_config: models::ApplySeatIncreaseConfigForRecurringCommit, subscription_id: uuid::Uuid) -> RecurringCommitSubscriptionConfig {
        RecurringCommitSubscriptionConfig {
            allocation,
            apply_seat_increase_config: Box::new(apply_seat_increase_config),
            subscription_id,
        }
    }
}

