/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RecurringCreditInputV2AllOfProrationRounding : Optional rounding configuration for prorated recurring credit amounts.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecurringCreditInputV2AllOfProrationRounding {
    #[serde(rename = "access", skip_serializing_if = "Option::is_none")]
    pub access: Option<Box<models::ProrationRoundingConfigV2>>,
}

impl RecurringCreditInputV2AllOfProrationRounding {
    /// Optional rounding configuration for prorated recurring credit amounts.
    pub fn new() -> RecurringCreditInputV2AllOfProrationRounding {
        RecurringCreditInputV2AllOfProrationRounding {
            access: None,
        }
    }
}

