/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RecurringScheduleFrequency {
    #[serde(rename = "MONTHLY")]
    Monthly,
    #[serde(rename = "monthly")]
    Monthly2,
    #[serde(rename = "QUARTERLY")]
    Quarterly,
    #[serde(rename = "quarterly")]
    Quarterly2,
    #[serde(rename = "SEMI_ANNUAL")]
    SemiAnnual,
    #[serde(rename = "semi_annual")]
    SemiAnnual2,
    #[serde(rename = "ANNUAL")]
    Annual,
    #[serde(rename = "annual")]
    Annual2,

}

impl std::fmt::Display for RecurringScheduleFrequency {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Monthly => write!(f, "MONTHLY"),
            Self::Monthly2 => write!(f, "monthly"),
            Self::Quarterly => write!(f, "QUARTERLY"),
            Self::Quarterly2 => write!(f, "quarterly"),
            Self::SemiAnnual => write!(f, "SEMI_ANNUAL"),
            Self::SemiAnnual2 => write!(f, "semi_annual"),
            Self::Annual => write!(f, "ANNUAL"),
            Self::Annual2 => write!(f, "annual"),
        }
    }
}

impl Default for RecurringScheduleFrequency {
    fn default() -> RecurringScheduleFrequency {
        Self::Monthly
    }
}

