/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecurringCommitOrCreditUpdateBase {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "ending_before", skip_serializing_if = "Option::is_none")]
    pub ending_before: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "access_amount", skip_serializing_if = "Option::is_none")]
    pub access_amount: Option<Box<models::RecurringCommitOrCreditUpdateBaseAccessAmount>>,
    #[serde(rename = "rate_type", skip_serializing_if = "Option::is_none")]
    pub rate_type: Option<RateType>,
}

impl RecurringCommitOrCreditUpdateBase {
    pub fn new(id: uuid::Uuid) -> RecurringCommitOrCreditUpdateBase {
        RecurringCommitOrCreditUpdateBase {
            id,
            ending_before: None,
            access_amount: None,
            rate_type: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RateType {
    #[serde(rename = "LIST_RATE")]
    ListRate,
    #[serde(rename = "list_rate")]
    ListRate2,
    #[serde(rename = "COMMIT_RATE")]
    CommitRate,
    #[serde(rename = "commit_rate")]
    CommitRate2,
}

impl Default for RateType {
    fn default() -> RateType {
        Self::ListRate
    }
}

