/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RecurringCommitOrCreditBaseCommitDuration : The amount of time the created commits will be valid for
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecurringCommitOrCreditBaseCommitDuration {
    #[serde(rename = "value")]
    pub value: f64,
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<Unit>,
}

impl RecurringCommitOrCreditBaseCommitDuration {
    /// The amount of time the created commits will be valid for
    pub fn new(value: f64) -> RecurringCommitOrCreditBaseCommitDuration {
        RecurringCommitOrCreditBaseCommitDuration {
            value,
            unit: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Unit {
    #[serde(rename = "periods")]
    Periods,
    #[serde(rename = "PERIODS")]
    Periods2,
}

impl Default for Unit {
    fn default() -> Unit {
        Self::Periods
    }
}

