/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RecurringCommitV2AllOfProrationRounding : Rounding configuration for prorated recurring commit amounts.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecurringCommitV2AllOfProrationRounding {
    #[serde(rename = "access", skip_serializing_if = "Option::is_none")]
    pub access: Option<Box<models::ProrationRoundingConfigV2>>,
    #[serde(rename = "invoice", skip_serializing_if = "Option::is_none")]
    pub invoice: Option<Box<models::ProrationRoundingConfigV2>>,
}

impl RecurringCommitV2AllOfProrationRounding {
    /// Rounding configuration for prorated recurring commit amounts.
    pub fn new() -> RecurringCommitV2AllOfProrationRounding {
        RecurringCommitV2AllOfProrationRounding {
            access: None,
            invoice: None,
        }
    }
}

