/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ResellerType {
    #[serde(rename = "AWS")]
    Aws,
    #[serde(rename = "AWS_PRO_SERVICE")]
    AwsProService,
    #[serde(rename = "GCP")]
    Gcp,
    #[serde(rename = "GCP_PRO_SERVICE")]
    GcpProService,

}

impl std::fmt::Display for ResellerType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Aws => write!(f, "AWS"),
            Self::AwsProService => write!(f, "AWS_PRO_SERVICE"),
            Self::Gcp => write!(f, "GCP"),
            Self::GcpProService => write!(f, "GCP_PRO_SERVICE"),
        }
    }
}

impl Default for ResellerType {
    fn default() -> ResellerType {
        Self::Aws
    }
}

