/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RetireCommitsPayload {
    /// ID of the customer whose commits are being retired
    #[serde(rename = "customer_id")]
    pub customer_id: uuid::Uuid,
    /// ID of the contract containing the commits
    #[serde(rename = "contract_id")]
    pub contract_id: uuid::Uuid,
    /// IDs of the commits to retire
    #[serde(rename = "commit_ids")]
    pub commit_ids: Vec<uuid::Uuid>,
    /// If true, previews which commits would be retired and which would be skipped, without making changes
    #[serde(rename = "dry_run", skip_serializing_if = "Option::is_none")]
    pub dry_run: Option<bool>,
}

impl RetireCommitsPayload {
    pub fn new(customer_id: uuid::Uuid, contract_id: uuid::Uuid, commit_ids: Vec<uuid::Uuid>) -> RetireCommitsPayload {
        RetireCommitsPayload {
            customer_id,
            contract_id,
            commit_ids,
            dry_run: None,
        }
    }
}

