/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RevenueSystemConfigurationUpdateSchedule {
    #[serde(rename = "effective_at")]
    pub effective_at: models::RevenueSystemConfigurationUpdateEffectiveAtType,
}

impl RevenueSystemConfigurationUpdateSchedule {
    pub fn new(effective_at: models::RevenueSystemConfigurationUpdateEffectiveAtType) -> RevenueSystemConfigurationUpdateSchedule {
        RevenueSystemConfigurationUpdateSchedule {
            effective_at,
        }
    }
}

