/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RevenueSystemConfigurationUpdateRevenueSystemConfiguration {
    #[serde(rename = "revenue_system_configuration_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub revenue_system_configuration_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "provider", skip_serializing_if = "Option::is_none")]
    pub provider: Option<models::RevenueSystemProviderTypeV2>,
    #[serde(rename = "delivery_method", skip_serializing_if = "Option::is_none")]
    pub delivery_method: Option<models::BillingProviderDeliveryMethodType>,
}

impl RevenueSystemConfigurationUpdateRevenueSystemConfiguration {
    pub fn new() -> RevenueSystemConfigurationUpdateRevenueSystemConfiguration {
        RevenueSystemConfigurationUpdateRevenueSystemConfiguration {
            revenue_system_configuration_id: None,
            provider: None,
            delivery_method: None,
        }
    }
}

