/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RolloverAmountMaxPercentage {
    /// Rollover up to a percentage of the original credit grant amount.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The maximum percentage (0-1) of the original credit grant to rollover.
    #[serde(rename = "value")]
    pub value: f64,
}

impl RolloverAmountMaxPercentage {
    pub fn new(r#type: Type, value: f64) -> RolloverAmountMaxPercentage {
        RolloverAmountMaxPercentage {
            r#type,
            value,
        }
    }
}
/// Rollover up to a percentage of the original credit grant amount.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "MAX_PERCENTAGE")]
    MaxPercentage,
}

impl Default for Type {
    fn default() -> Type {
        Self::MaxPercentage
    }
}

