/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SchedulePointInTimeInputScheduleItemsInner {
    /// Unit price for the charge. Will be multiplied by quantity to determine the amount and must be specified with quantity. If specified amount cannot be provided.
    #[serde(rename = "unit_price", skip_serializing_if = "Option::is_none")]
    pub unit_price: Option<f64>,
    /// Quantity for the charge. Will be multiplied by unit_price to determine the amount and must be specified with unit_price. If specified amount cannot be provided.
    #[serde(rename = "quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<f64>,
    /// Amount for the charge. Can be provided instead of unit_price and quantity. If amount is sent, the unit_price is assumed to be the amount and quantity is inferred to be 1.
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<f64>,
    /// timestamp of the scheduled event
    #[serde(rename = "timestamp")]
    pub timestamp: chrono::DateTime<chrono::FixedOffset>,
}

impl SchedulePointInTimeInputScheduleItemsInner {
    pub fn new(timestamp: chrono::DateTime<chrono::FixedOffset>) -> SchedulePointInTimeInputScheduleItemsInner {
        SchedulePointInTimeInputScheduleItemsInner {
            unit_price: None,
            quantity: None,
            amount: None,
            timestamp,
        }
    }
}

