/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ScheduleProServicesInvoiceV1RequestLineItemsInner : Describes the line item for a professional service charge on an invoice.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduleProServicesInvoiceV1RequestLineItemsInner {
    #[serde(rename = "professional_service_id")]
    pub professional_service_id: uuid::Uuid,
    /// If the professional_service_id was added on an amendment, this is required.
    #[serde(rename = "amendment_id", skip_serializing_if = "Option::is_none")]
    pub amendment_id: Option<uuid::Uuid>,
    /// If specified, this overrides the unit price on the pro service term. Must also provide quantity (but not amount) if providing unit_price.
    #[serde(rename = "unit_price", skip_serializing_if = "Option::is_none")]
    pub unit_price: Option<f64>,
    /// Quantity for the charge. Will be multiplied by unit_price to determine the amount.
    #[serde(rename = "quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<f64>,
    /// Amount for the term on the new invoice.
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<f64>,
    /// The start date for the billing period on the invoice.
    #[serde(rename = "netsuite_invoice_billing_start", skip_serializing_if = "Option::is_none")]
    pub netsuite_invoice_billing_start: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// The end date for the billing period on the invoice.
    #[serde(rename = "netsuite_invoice_billing_end", skip_serializing_if = "Option::is_none")]
    pub netsuite_invoice_billing_end: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// For client use.
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<String>,
}

impl ScheduleProServicesInvoiceV1RequestLineItemsInner {
    /// Describes the line item for a professional service charge on an invoice.
    pub fn new(professional_service_id: uuid::Uuid) -> ScheduleProServicesInvoiceV1RequestLineItemsInner {
        ScheduleProServicesInvoiceV1RequestLineItemsInner {
            professional_service_id,
            amendment_id: None,
            unit_price: None,
            quantity: None,
            amount: None,
            netsuite_invoice_billing_start: None,
            netsuite_invoice_billing_end: None,
            metadata: None,
        }
    }
}

