/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchEventsV1Request {
    /// The transaction IDs of the events to retrieve
    #[serde(rename = "transactionIds")]
    pub transaction_ids: Vec<String>,
}

impl SearchEventsV1Request {
    pub fn new(transaction_ids: Vec<String>) -> SearchEventsV1Request {
        SearchEventsV1Request {
            transaction_ids,
        }
    }
}

