/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SeatBalance {
    /// The unique identifier for the seat
    #[serde(rename = "seat_id")]
    pub seat_id: String,
    #[serde(rename = "balances")]
    pub balances: Vec<models::SeatBalanceByCreditType>,
    /// Array of commits applicable to this seat with their balances
    #[serde(rename = "commits", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub commits: Option<Option<Vec<models::SeatCommitBalance>>>,
    /// Array of credits applicable to this seat with their balances
    #[serde(rename = "credits", skip_serializing_if = "Option::is_none")]
    pub credits: Option<Vec<models::SeatCreditBalance>>,
}

impl SeatBalance {
    pub fn new(seat_id: String, balances: Vec<models::SeatBalanceByCreditType>) -> SeatBalance {
        SeatBalance {
            seat_id,
            balances,
            commits: None,
            credits: None,
        }
    }
}

