/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SeatCreditBalance {
    /// The credit ID
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// The current balance for this credit for this specific seat
    #[serde(rename = "balance")]
    pub balance: f64,
    /// The datetime when the credit becomes active
    #[serde(rename = "start_date")]
    pub start_date: chrono::DateTime<chrono::FixedOffset>,
    /// The datetime when the credit expires
    #[serde(rename = "end_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// Transaction history for this credit for this seat (only included if include_ledgers=true)
    #[serde(rename = "ledger_entries", skip_serializing_if = "Option::is_none")]
    pub ledger_entries: Option<Vec<models::SeatBalanceCreditLedger>>,
}

impl SeatCreditBalance {
    pub fn new(id: uuid::Uuid, balance: f64, start_date: chrono::DateTime<chrono::FixedOffset>) -> SeatCreditBalance {
        SeatCreditBalance {
            id,
            balance,
            start_date,
            end_date: None,
            ledger_entries: None,
        }
    }
}

