/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetCustomerBillableStatusV1200ResponseData {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "current_billable_status")]
    pub current_billable_status: CurrentBillableStatus,
}

impl SetCustomerBillableStatusV1200ResponseData {
    pub fn new(id: uuid::Uuid, current_billable_status: CurrentBillableStatus) -> SetCustomerBillableStatusV1200ResponseData {
        SetCustomerBillableStatusV1200ResponseData {
            id,
            current_billable_status,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CurrentBillableStatus {
    #[serde(rename = "billable")]
    Billable,
    #[serde(rename = "unbillable")]
    Unbillable,
}

impl Default for CurrentBillableStatus {
    fn default() -> CurrentBillableStatus {
        Self::Billable
    }
}

