/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetUpBillingProviderV1200Response {
    #[serde(rename = "data")]
    pub data: Box<models::SetUpBillingProviderV1200ResponseData>,
}

impl SetUpBillingProviderV1200Response {
    pub fn new(data: models::SetUpBillingProviderV1200ResponseData) -> SetUpBillingProviderV1200Response {
        SetUpBillingProviderV1200Response {
            data: Box::new(data),
        }
    }
}

