/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetCustomerRevenueSystemConfigurationsV1RequestDataInner {
    /// The revenue system provider (e.g. netsuite).
    #[serde(rename = "provider")]
    pub provider: Provider,
    #[serde(rename = "customer_id")]
    pub customer_id: uuid::Uuid,
    /// Configuration for the revenue system. The structure of this object is specific to the provider.
    #[serde(rename = "configuration")]
    pub configuration: std::collections::HashMap<String, serde_json::Value>,
    /// Optional ID of the delivery method to use for this customer configuration, if multiple delivery methods are configured for the same provider.
    #[serde(rename = "delivery_method_id", skip_serializing_if = "Option::is_none")]
    pub delivery_method_id: Option<uuid::Uuid>,
}

impl SetCustomerRevenueSystemConfigurationsV1RequestDataInner {
    pub fn new(provider: Provider, customer_id: uuid::Uuid, configuration: std::collections::HashMap<String, serde_json::Value>) -> SetCustomerRevenueSystemConfigurationsV1RequestDataInner {
        SetCustomerRevenueSystemConfigurationsV1RequestDataInner {
            provider,
            customer_id,
            configuration,
            delivery_method_id: None,
        }
    }
}
/// The revenue system provider (e.g. netsuite).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Provider {
    #[serde(rename = "netsuite")]
    Netsuite,
}

impl Default for Provider {
    fn default() -> Provider {
        Self::Netsuite
    }
}

