/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpendBreakdownInvoice {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "customer_id")]
    pub customer_id: uuid::Uuid,
    #[serde(rename = "credit_type")]
    pub credit_type: Box<models::CreditType>,
    #[serde(rename = "line_items")]
    pub line_items: Vec<models::InvoiceLineItem>,
    /// Beginning of the usage period this invoice covers (UTC)
    #[serde(rename = "start_timestamp", skip_serializing_if = "Option::is_none")]
    pub start_timestamp: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// End of the usage period this invoice covers (UTC)
    #[serde(rename = "end_timestamp", skip_serializing_if = "Option::is_none")]
    pub end_timestamp: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// When the invoice was issued (UTC)
    #[serde(rename = "issued_at", skip_serializing_if = "Option::is_none")]
    pub issued_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// When the invoice was created (UTC). This field is present for correction invoices only.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "contract_id", skip_serializing_if = "Option::is_none")]
    pub contract_id: Option<uuid::Uuid>,
    #[serde(rename = "breakdown_start_timestamp")]
    pub breakdown_start_timestamp: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "breakdown_end_timestamp")]
    pub breakdown_end_timestamp: chrono::DateTime<chrono::FixedOffset>,
}

impl SpendBreakdownInvoice {
    pub fn new(id: uuid::Uuid, customer_id: uuid::Uuid, credit_type: models::CreditType, line_items: Vec<models::InvoiceLineItem>, status: String, r#type: String, breakdown_start_timestamp: chrono::DateTime<chrono::FixedOffset>, breakdown_end_timestamp: chrono::DateTime<chrono::FixedOffset>) -> SpendBreakdownInvoice {
        SpendBreakdownInvoice {
            id,
            customer_id,
            credit_type: Box::new(credit_type),
            line_items,
            start_timestamp: None,
            end_timestamp: None,
            issued_at: None,
            created_at: None,
            status,
            r#type,
            contract_id: None,
            breakdown_start_timestamp,
            breakdown_end_timestamp,
        }
    }
}

