/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpendTrackerAttributesInput {
    /// If true, this commit will be included in spend trackers with discounted set to DISCOUNTED_ONLY
    #[serde(rename = "counts_as_discounted")]
    pub counts_as_discounted: bool,
}

impl SpendTrackerAttributesInput {
    pub fn new(counts_as_discounted: bool) -> SpendTrackerAttributesInput {
        SpendTrackerAttributesInput {
            counts_as_discounted,
        }
    }
}

