/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpendThresholdConfiguration {
    /// When set to false, the contract will not be evaluated against the threshold_amount. Toggling to true will result an immediate evaluation, regardless of prior state.
    #[serde(rename = "is_enabled")]
    pub is_enabled: bool,
    /// Specify the threshold amount for the contract. Each time the contract's usage hits this amount, a threshold charge will be initiated.
    #[serde(rename = "threshold_amount")]
    pub threshold_amount: f64,
    #[serde(rename = "commit")]
    pub commit: Box<models::SpendThresholdCommit>,
    #[serde(rename = "payment_gate_config")]
    pub payment_gate_config: Box<models::PaymentGateConfig>,
    #[serde(rename = "discount_configuration", skip_serializing_if = "Option::is_none")]
    pub discount_configuration: Option<Box<models::DiscountConfiguration>>,
}

impl SpendThresholdConfiguration {
    pub fn new(is_enabled: bool, threshold_amount: f64, commit: models::SpendThresholdCommit, payment_gate_config: models::PaymentGateConfig) -> SpendThresholdConfiguration {
        SpendThresholdConfiguration {
            is_enabled,
            threshold_amount,
            commit: Box::new(commit),
            payment_gate_config: Box::new(payment_gate_config),
            discount_configuration: None,
        }
    }
}

