/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpendTrackerAccumulatedSpend {
    #[serde(rename = "amount")]
    pub amount: f64,
    #[serde(rename = "period_starting_at")]
    pub period_starting_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "period_ending_before")]
    pub period_ending_before: chrono::DateTime<chrono::FixedOffset>,
}

impl SpendTrackerAccumulatedSpend {
    pub fn new(amount: f64, period_starting_at: chrono::DateTime<chrono::FixedOffset>, period_ending_before: chrono::DateTime<chrono::FixedOffset>) -> SpendTrackerAccumulatedSpend {
        SpendTrackerAccumulatedSpend {
            amount,
            period_starting_at,
            period_ending_before,
        }
    }
}

