/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpendThresholdCommit {
    /// The commit product that will be used to generate the line item for commit payment.
    #[serde(rename = "product_id")]
    pub product_id: String,
    /// Specify the name of the line item for the threshold charge. If left blank, it will default to the commit product name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The priority of the commit, used to determine drawdown order. Lower priority commits are consumed first. Defaults to 100 if not specified.
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<f64>,
}

impl SpendThresholdCommit {
    pub fn new(product_id: String) -> SpendThresholdCommit {
        SpendThresholdCommit {
            product_id,
            name: None,
            description: None,
            priority: None,
        }
    }
}

