/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmitApprovalRequestsV1Request {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    /// The API path of the operation being requested (e.g. /v1/contracts/create).
    #[serde(rename = "request_type")]
    pub request_type: String,
    /// The full request body of the operation being requested.
    #[serde(rename = "request_payload")]
    pub request_payload: std::collections::HashMap<String, serde_json::Value>,
}

impl SubmitApprovalRequestsV1Request {
    pub fn new(name: String, description: String, request_type: String, request_payload: std::collections::HashMap<String, serde_json::Value>) -> SubmitApprovalRequestsV1Request {
        SubmitApprovalRequestsV1Request {
            name,
            description,
            request_type,
            request_payload,
        }
    }
}

