/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscriptionQuantityHistory {
    #[serde(rename = "subscription_id", skip_serializing_if = "Option::is_none")]
    pub subscription_id: Option<uuid::Uuid>,
    #[serde(rename = "fiat_credit_type_id", skip_serializing_if = "Option::is_none")]
    pub fiat_credit_type_id: Option<uuid::Uuid>,
    /// The pricing unit for history prices when present. Otherwise prices use fiat_credit_type_id.
    #[serde(rename = "custom_credit_type_id", skip_serializing_if = "Option::is_none")]
    pub custom_credit_type_id: Option<uuid::Uuid>,
    #[serde(rename = "history", skip_serializing_if = "Option::is_none")]
    pub history: Option<Vec<models::SubscriptionQuantityHistoryHistoryInner>>,
}

impl SubscriptionQuantityHistory {
    pub fn new() -> SubscriptionQuantityHistory {
        SubscriptionQuantityHistory {
            subscription_id: None,
            fiat_credit_type_id: None,
            custom_credit_type_id: None,
            history: None,
        }
    }
}

