/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SubscriptionConfigAllocation {
    #[serde(rename = "INDIVIDUAL")]
    Individual,
    #[serde(rename = "POOLED")]
    Pooled,

}

impl std::fmt::Display for SubscriptionConfigAllocation {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Individual => write!(f, "INDIVIDUAL"),
            Self::Pooled => write!(f, "POOLED"),
        }
    }
}

impl Default for SubscriptionConfigAllocation {
    fn default() -> SubscriptionConfigAllocation {
        Self::Individual
    }
}

