/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscriptionSeatsScheduleEntry {
    /// The start time of this seat schedule period
    #[serde(rename = "starting_at")]
    pub starting_at: String,
    /// The end time of this seat schedule period (null if ongoing)
    #[serde(rename = "ending_before", deserialize_with = "Option::deserialize")]
    pub ending_before: Option<String>,
    /// Total number of assigned and unassigned seats in this period
    #[serde(rename = "total_quantity")]
    pub total_quantity: i32,
    /// Array of seat IDs that are assigned in this period
    #[serde(rename = "assigned_seat_ids")]
    pub assigned_seat_ids: Vec<String>,
}

impl SubscriptionSeatsScheduleEntry {
    pub fn new(starting_at: String, ending_before: Option<String>, total_quantity: i32, assigned_seat_ids: Vec<String>) -> SubscriptionSeatsScheduleEntry {
        SubscriptionSeatsScheduleEntry {
            starting_at,
            ending_before,
            total_quantity,
            assigned_seat_ids,
        }
    }
}

