/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscriptionProrationInputV2 {
    /// Indicates if the partial period will be prorated or charged a full amount.
    #[serde(rename = "is_prorated", skip_serializing_if = "Option::is_none")]
    pub is_prorated: Option<bool>,
    /// Indicates how mid-period quantity adjustments are invoiced. **BILL_IMMEDIATELY**: Only available when collection schedule is `ADVANCE`. The quantity increase will be billed immediately on the scheduled date. **BILL_ON_NEXT_COLLECTION_DATE**: The quantity increase will be billed for in-arrears at the end of the period. 
    #[serde(rename = "invoice_behavior", skip_serializing_if = "Option::is_none")]
    pub invoice_behavior: Option<InvoiceBehavior>,
    #[serde(rename = "rounding", skip_serializing_if = "Option::is_none")]
    pub rounding: Option<Box<models::ProrationRoundingConfigV2>>,
}

impl SubscriptionProrationInputV2 {
    pub fn new() -> SubscriptionProrationInputV2 {
        SubscriptionProrationInputV2 {
            is_prorated: None,
            invoice_behavior: None,
            rounding: None,
        }
    }
}
/// Indicates how mid-period quantity adjustments are invoiced. **BILL_IMMEDIATELY**: Only available when collection schedule is `ADVANCE`. The quantity increase will be billed immediately on the scheduled date. **BILL_ON_NEXT_COLLECTION_DATE**: The quantity increase will be billed for in-arrears at the end of the period. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InvoiceBehavior {
    #[serde(rename = "BILL_IMMEDIATELY")]
    BillImmediately,
    #[serde(rename = "BILL_ON_NEXT_COLLECTION_DATE")]
    BillOnNextCollectionDate,
    #[serde(rename = "bill_immediately")]
    BillImmediately2,
    #[serde(rename = "bill_on_next_collection_date")]
    BillOnNextCollectionDate2,
}

impl Default for InvoiceBehavior {
    fn default() -> InvoiceBehavior {
        Self::BillImmediately
    }
}

