/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ThresholdBalanceSpecifier {
    #[serde(rename = "exclude")]
    pub exclude: Vec<models::ExcludeThresholdBalanceSpecifier>,
}

impl ThresholdBalanceSpecifier {
    pub fn new(exclude: Vec<models::ExcludeThresholdBalanceSpecifier>) -> ThresholdBalanceSpecifier {
        ThresholdBalanceSpecifier {
            exclude,
        }
    }
}

