/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateRecurringCommitInputProrationRounding : If provided, updates the rounding config on the recurring commit. Set to null to clear rounding. Omit to leave unchanged.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateRecurringCommitInputProrationRounding {
    #[serde(rename = "access", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub access: Option<Option<Box<models::NullableProrationRoundingConfig>>>,
    #[serde(rename = "invoice", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub invoice: Option<Option<Box<models::NullableProrationRoundingConfig>>>,
}

impl UpdateRecurringCommitInputProrationRounding {
    /// If provided, updates the rounding config on the recurring commit. Set to null to clear rounding. Omit to leave unchanged.
    pub fn new() -> UpdateRecurringCommitInputProrationRounding {
        UpdateRecurringCommitInputProrationRounding {
            access: None,
            invoice: None,
        }
    }
}

