/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateProductListItemPayload {
    /// ID of the product to update
    #[serde(rename = "product_id")]
    pub product_id: uuid::Uuid,
    /// displayed on invoices. If not provided, defaults to product's current name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Timestamp representing when the update should go into effect. It must be on an hour boundary (e.g. 1:00, not 1:30).
    #[serde(rename = "starting_at")]
    pub starting_at: chrono::DateTime<chrono::FixedOffset>,
    /// Defaults to product's current refundability status. This field's availability is dependent on your client's configuration.
    #[serde(rename = "is_refundable", skip_serializing_if = "Option::is_none")]
    pub is_refundable: Option<bool>,
    /// Beta feature only available for composite products. If true, products with $0 will not be included when computing composite usage. Defaults to false
    #[serde(rename = "exclude_free_usage", skip_serializing_if = "Option::is_none")]
    pub exclude_free_usage: Option<bool>,
    /// Only for composite products. If true, allows a composite to incorporate spend from other composite products. Defaults to false
    #[serde(rename = "include_composite_spend", skip_serializing_if = "Option::is_none")]
    pub include_composite_spend: Option<bool>,
    /// Available for USAGE products only. If not provided, defaults to product's current billable metric.
    #[serde(rename = "billable_metric_id", skip_serializing_if = "Option::is_none")]
    pub billable_metric_id: Option<uuid::Uuid>,
    /// Defines the breakdown behavior when calculating usage from SQL Billable Metrics. If set to 'service_period' (default), the usage will be evaluated once for all events the invoice service period and the usage will be applied at the last instant of the invoice. If set to 'hour', it will be broken down and evaluated for each hour. For most use cases, 'hour' is recommended. The setting has no effect for Streaming Billable Metrics.
    #[serde(rename = "sql_breakdown_granularity", skip_serializing_if = "Option::is_none")]
    pub sql_breakdown_granularity: Option<SqlBreakdownGranularity>,
    /// If not provided, defaults to product's current netsuite_internal_item_id. This field's availability is dependent on your client's configuration.
    #[serde(rename = "netsuite_internal_item_id", skip_serializing_if = "Option::is_none")]
    pub netsuite_internal_item_id: Option<String>,
    /// Available for USAGE and COMPOSITE products only. If not provided, defaults to product's current netsuite_overage_item_id. This field's availability is dependent on your client's configuration.
    #[serde(rename = "netsuite_overage_item_id", skip_serializing_if = "Option::is_none")]
    pub netsuite_overage_item_id: Option<String>,
    /// Available for COMPOSITE products only. If not provided, defaults to product's current composite_product_ids.
    #[serde(rename = "composite_product_ids", skip_serializing_if = "Option::is_none")]
    pub composite_product_ids: Option<Vec<uuid::Uuid>>,
    #[serde(rename = "quantity_conversion", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub quantity_conversion: Option<Option<Box<models::QuantityConversion>>>,
    #[serde(rename = "quantity_rounding", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub quantity_rounding: Option<Option<Box<models::QuantityRounding>>>,
    /// If not provided, defaults to product's current tags
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    /// Available for COMPOSITE products only. If not provided, defaults to product's current composite_tags.
    #[serde(rename = "composite_tags", skip_serializing_if = "Option::is_none")]
    pub composite_tags: Option<Vec<String>>,
    /// For USAGE products only. If set, pricing for this product will be determined for each pricing_group_key value, as opposed to the product as a whole. The superset of values in the pricing group key and presentation group key must be set as one compound group key on the billable metric.
    #[serde(rename = "pricing_group_key", skip_serializing_if = "Option::is_none")]
    pub pricing_group_key: Option<Vec<String>>,
    /// For USAGE products only. Groups usage line items on invoices. The superset of values in the pricing group key and presentation group key must be set as one compound group key on the billable metric.
    #[serde(rename = "presentation_group_key", skip_serializing_if = "Option::is_none")]
    pub presentation_group_key: Option<Vec<String>>,
}

impl UpdateProductListItemPayload {
    pub fn new(product_id: uuid::Uuid, starting_at: chrono::DateTime<chrono::FixedOffset>) -> UpdateProductListItemPayload {
        UpdateProductListItemPayload {
            product_id,
            name: None,
            starting_at,
            is_refundable: None,
            exclude_free_usage: None,
            include_composite_spend: None,
            billable_metric_id: None,
            sql_breakdown_granularity: None,
            netsuite_internal_item_id: None,
            netsuite_overage_item_id: None,
            composite_product_ids: None,
            quantity_conversion: None,
            quantity_rounding: None,
            tags: None,
            composite_tags: None,
            pricing_group_key: None,
            presentation_group_key: None,
        }
    }
}
/// Defines the breakdown behavior when calculating usage from SQL Billable Metrics. If set to 'service_period' (default), the usage will be evaluated once for all events the invoice service period and the usage will be applied at the last instant of the invoice. If set to 'hour', it will be broken down and evaluated for each hour. For most use cases, 'hour' is recommended. The setting has no effect for Streaming Billable Metrics.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SqlBreakdownGranularity {
    #[serde(rename = "HOUR")]
    Hour,
    #[serde(rename = "hour")]
    Hour2,
    #[serde(rename = "SERVICE_PERIOD")]
    ServicePeriod,
    #[serde(rename = "service_period")]
    ServicePeriod2,
}

impl Default for SqlBreakdownGranularity {
    fn default() -> SqlBreakdownGranularity {
        Self::Hour
    }
}

