/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateSubscriptionInputQuantityUpdatesInner {
    /// The new quantity for the subscription. Must be provided if quantity_delta is not provided. Must be non-negative.
    #[serde(rename = "quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<f64>,
    /// The delta to add to the subscription's quantity. Must be provided if quantity is not provided. Can't be zero. It also can't result in a negative quantity on the subscription.
    #[serde(rename = "quantity_delta", skip_serializing_if = "Option::is_none")]
    pub quantity_delta: Option<f64>,
    #[serde(rename = "starting_at")]
    pub starting_at: chrono::DateTime<chrono::FixedOffset>,
}

impl UpdateSubscriptionInputQuantityUpdatesInner {
    pub fn new(starting_at: chrono::DateTime<chrono::FixedOffset>) -> UpdateSubscriptionInputQuantityUpdatesInner {
        UpdateSubscriptionInputQuantityUpdatesInner {
            quantity: None,
            quantity_delta: None,
            starting_at,
        }
    }
}

