/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateBillableMetricV1Request {
    /// The new name of the metric
    #[serde(rename = "name")]
    pub name: String,
}

impl UpdateBillableMetricV1Request {
    pub fn new(name: String) -> UpdateBillableMetricV1Request {
        UpdateBillableMetricV1Request {
            name,
        }
    }
}

