/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateScheduledChargeInput {
    #[serde(rename = "scheduled_charge_id")]
    pub scheduled_charge_id: uuid::Uuid,
    #[serde(rename = "netsuite_sales_order_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub netsuite_sales_order_id: Option<Option<String>>,
    #[serde(rename = "invoice_schedule", skip_serializing_if = "Option::is_none")]
    pub invoice_schedule: Option<Box<models::UpdateInvoiceScheduleInput>>,
}

impl UpdateScheduledChargeInput {
    pub fn new(scheduled_charge_id: uuid::Uuid) -> UpdateScheduledChargeInput {
        UpdateScheduledChargeInput {
            scheduled_charge_id,
            netsuite_sales_order_id: None,
            invoice_schedule: None,
        }
    }
}

