/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateSubscriptionInputQuantityManagementModeUpdate : Update the subscription's quantity management mode from QUANTITY_ONLY to SEAT_BASED with the provided seat_group_key.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateSubscriptionInputQuantityManagementModeUpdate {
    #[serde(rename = "quantity_management_mode")]
    pub quantity_management_mode: QuantityManagementMode,
    #[serde(rename = "seat_config")]
    pub seat_config: Box<models::UpdateSubscriptionInputQuantityManagementModeUpdateSeatConfig>,
}

impl UpdateSubscriptionInputQuantityManagementModeUpdate {
    /// Update the subscription's quantity management mode from QUANTITY_ONLY to SEAT_BASED with the provided seat_group_key.
    pub fn new(quantity_management_mode: QuantityManagementMode, seat_config: models::UpdateSubscriptionInputQuantityManagementModeUpdateSeatConfig) -> UpdateSubscriptionInputQuantityManagementModeUpdate {
        UpdateSubscriptionInputQuantityManagementModeUpdate {
            quantity_management_mode,
            seat_config: Box::new(seat_config),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum QuantityManagementMode {
    #[serde(rename = "SEAT_BASED")]
    SeatBased,
    #[serde(rename = "seat_based")]
    SeatBased2,
}

impl Default for QuantityManagementMode {
    fn default() -> QuantityManagementMode {
        Self::SeatBased
    }
}

