/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageFilterV2 {
    #[serde(rename = "group_key")]
    pub group_key: String,
    #[serde(rename = "group_values")]
    pub group_values: Vec<String>,
    /// This will match contract starting_at value if usage filter is active from the beginning of the contract.
    #[serde(rename = "starting_at")]
    pub starting_at: String,
    /// This will match contract ending_before value if usage filter is active until the end of the contract. It will be undefined if the contract is open-ended.
    #[serde(rename = "ending_before", skip_serializing_if = "Option::is_none")]
    pub ending_before: Option<String>,
}

impl UsageFilterV2 {
    pub fn new(group_key: String, group_values: Vec<String>, starting_at: String) -> UsageFilterV2 {
        UsageFilterV2 {
            group_key,
            group_values,
            starting_at,
            ending_before: None,
        }
    }
}

