/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VoidInvoiceV1Request {
    /// The invoice id to void
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
}

impl VoidInvoiceV1Request {
    pub fn new(id: uuid::Uuid) -> VoidInvoiceV1Request {
        VoidInvoiceV1Request {
            id,
        }
    }
}

