/*
 * Metronome
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookDeliveryDetail {
    /// ID of the triggered notification.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// ID of the webhook destination.
    #[serde(rename = "webhook_id")]
    pub webhook_id: uuid::Uuid,
    #[serde(rename = "customer_id", deserialize_with = "Option::deserialize")]
    pub customer_id: Option<uuid::Uuid>,
    /// ID of the notification configuration, when applicable.
    #[serde(rename = "notification_id", deserialize_with = "Option::deserialize")]
    pub notification_id: Option<String>,
    #[serde(rename = "notification_type")]
    pub notification_type: String,
    /// The exact payload sent to the webhook destination.
    #[serde(rename = "notification_payload")]
    pub notification_payload: String,
    /// Delivery attempts ordered from oldest to newest.
    #[serde(rename = "attempts")]
    pub attempts: Vec<models::WebhookDeliveryAttempt>,
}

impl WebhookDeliveryDetail {
    pub fn new(id: uuid::Uuid, webhook_id: uuid::Uuid, customer_id: Option<uuid::Uuid>, notification_id: Option<String>, notification_type: String, notification_payload: String, attempts: Vec<models::WebhookDeliveryAttempt>) -> WebhookDeliveryDetail {
        WebhookDeliveryDetail {
            id,
            webhook_id,
            customer_id,
            notification_id,
            notification_type,
            notification_payload,
            attempts,
        }
    }
}

